# Makefile.win for QtGSI example on Win32
# Author: Bertrand Bellenot, 03/04/2006

include $(ROOTSYS)/config/Makefile.config

####### Compiler, tools and options

is_debug := $(findstring debug,$(strip $(shell root-config --config)))
QT4      := $(findstring QtCore, $(QTINCDIR))

OutPutOpt     = -out:
CXX           = cl
LD            = link

ifdef is_debug
# Debugging:
OPTIMIZE  := -Z7
LINKDEBUG := -debug
else
# Full optimization:
OPTIMIZE  := -Ox
endif

QTCXXFLAGS   := -GR $(OPTIMIZE) -W3 -nologo $(shell root-config --cflags) -FIw32pragma.h -D_CRT_SECURE_NO_DEPRECATE -DQT_DLL -DQT_THREAD_SUPPORT -DQT3_SUPPORT $(QTINCDIR:%=-I%)
LFLAGS       := -nologo -machine:ix86 $(LINKDEBUG)
ROOTGLIBS    := $(shell root-config --glibs)
QTGSILIBS    := $(QTLIB) $(ROOTGLIBS) '$(ROOTSYS)\lib\libqtgsi.lib'

ifeq (,$(QT4))
UIC         = '$(QTDIR)\bin\uic.exe'
else
UIC         = '$(QTDIR)\bin\uic3.exe'
endif

####### Files

SOURCES  := main.cpp
OBJECTS  := main.obj qtrootexample1.obj qmake_image_collection.obj
FORMS    := qtrootexample1.ui
UICDECLS := qtrootexample1.h
UICIMPLS := qtrootexample1.cpp
SRCMOC   := moc_qtrootexample1.cpp
OBJMOC   := moc_qtrootexample1.obj
TARGET   := qtrootexample.exe

PROGRAMS      = $(TARGET)

#------------------------------------------------------------------------------

.SUFFIXES: .cpp .obj .exe

all:            $(PROGRAMS)

$(TARGET):  $(OBJECTS) $(OBJMOC)
		$(LD) $(LFLAGS) $^ $(QTGSILIBS) $(OutPutOpt)$@

uiclean:
		@rm -f qtrootexample1.h
		@rm -f qtrootexample1.cpp
mocclean:
		@rm -f moc_qtrootexample1.cpp
		@rm -f moc_qtrootexample1.obj

clean: uiclean mocclean
		@rm -f main.obj
		@rm -f qtrootexample1.obj
		@rm -f qmake_image_collection.obj
		@rm -f qtrootexample.pdb
		@rm -f qtrootexample.ilk
		@rm -f vc*.pdb
		@rm -f vc*.idb
		@rm -f qmake_image_collection.cpp

FORCE:

distclean: clean
		@rm -f $(TARGET)

####### Implicit rules

.cpp.obj:
		$(CXX) $(QTCXXFLAGS) -c $<

####### Build rules

mocables: $(SRCMOC)
uicables: $(UICIMPLS) $(UICDECLS)


####### Compile

main.obj: main.cpp qtrootexample1.h

qtrootexample1.h: qtrootexample1.ui 
		$(UIC) qtrootexample1.ui -o qtrootexample1.h

qtrootexample1.cpp: qtrootexample1.h qtrootexample1.ui qtrootexample1.ui.h 
		$(UIC) qtrootexample1.ui -i qtrootexample1.h -o qtrootexample1.cpp

qtrootexample1.obj: qtrootexample1.cpp qtrootexample1.ui.h qtrootexample1.h

moc_qtrootexample1.obj: moc_qtrootexample1.cpp  qtrootexample1.h 

moc_qtrootexample1.cpp: $(QTMOCEXE) qtrootexample1.h
		$(QTMOCEXE) qtrootexample1.h -o moc_qtrootexample1.cpp

qmake_image_collection.obj: qmake_image_collection.cpp

qmake_image_collection.cpp: images/qtroot_canvas.png images/h1_t.png images/h2_t.png
		$(UIC) -embed qtrootexample images/qtroot_canvas.png images/h1_t.png images/h2_t.png -o qmake_image_collection.cpp

