.TH hist2workspace 1 
.SH SYNOPSIS
usage: hist2workspace [-h] [-v] [-vv] [-disable_binned_fit_optimization]

.SH DESCRIPTION
hist2workspace is a utility to create RooFit/RooStats workspace from histograms
.SH OPTIONS
.IP -h --help
show this help message and exit
.IP -v
switch HistFactory message stream to INFO level
.IP -vv
switch HistFactory message stream to DEBUG level
.IP -disable_binned_fit_optimization
disable the binned fit optimization used in HistFactory since ROOT 6.28
