//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef ParticleBase_p1_h
#define ParticleBase_p1_h
class ParticleBase_p1;

#include "ElementLink_p1_unsigned_int_.h"
#include "AthenaBarCode_p1.h"

class ParticleBase_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   ElementLink_p1<unsigned int> m_origin;    //
   double                       m_charge;    //
   bool                         m_hasCharge;    //
   int                          m_pdgId;        //
   bool                         m_hasPdgId;     //
   int                          m_dataType;     //
   AthenaBarCode_p1             m_athenabarcode;    //

   ParticleBase_p1();
   ParticleBase_p1(const ParticleBase_p1 & );
   virtual ~ParticleBase_p1();

};
#endif
