//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef Trk__V0Candidate_p1_h
#define Trk__V0Candidate_p1_h
namespace Trk {
class V0Candidate_p1;
} // end of namespace.

#include "Riostream.h"
#include <vector>
#include "TPObjRef.h"

namespace Trk {
class V0Candidate_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<TPObjRef> m_v0Hyp;     //

   V0Candidate_p1();
   V0Candidate_p1(const V0Candidate_p1 & );
   virtual ~V0Candidate_p1();

};
} // namespace
#endif
