CXX = g++ #mpicxx # clang #
CXXFLAGS =  -std=c++11 -fopenmp -O3 # -stdlib=libc++

# some variables
GOOGLE_TEST_LIB=/home/zampieri/Documents/CERN/googletest
XGBOOST_ROOT=/home/zampieri/Documents/CERN/xgboost

GOOGLE_TEST_LIB ?= gtest
GOOGLE_TEST_INCLUDE = /usr/local/include

INCLUDE_DIR=-I$(XGBOOST_ROOT)/include \
			-I$(XGBOOST_ROOT)/dmlc-core/include \
			-I$(XGBOOST_ROOT)/rabit/include
LIB_DIR=-L$(XGBOOST_ROOT)/lib



ROOT_FLAGS = `root-config --cflags --glibs`

LD_FLAGS = -L -L.. -lpthread -Lgtest/lib -lgtest

CPPFLAGS = -I../include \
 -I./include \
 -Wno-deprecated \
 -Igtest/include \
 -I$(GOOGLE_TEST_LIB) \
 #-I$(GOOGLE_TEST_INCLUDE)

OBJS = build/arrayBDT.o  build/helpersBDT.o  build/unique_bdt.o
EXE = arrayBDT.exe helpersBDT.exe forestBDT.exe

.PHONY : all clean distclean

all: $(EXE)

forestBDT.exe: build/forestBDT.o build/unique_bdt.o
		$(CXX) $(CXXFLAGS) -o $@  $^  $(LD_FLAGS) $(ROOT_FLAGS) $(XGBOOST_ROOT)/lib/libxgboost.so

arrayBDT.exe: build/arrayBDT.o build/unique_bdt.o
	$(CXX) $(CXXFLAGS) -o $@  $^  $(LD_FLAGS) $(ROOT_FLAGS) $(XGBOOST_ROOT)/lib/libxgboost.so

helpersBDT.exe: build/helpersBDT.o build/unique_bdt.o
		$(CXX) $(CXXFLAGS) -o $@  $^  $(LD_FLAGS) $(ROOT_FLAGS) $(XGBOOST_ROOT)/lib/libxgboost.so
#$(OBJS): build/%.o: %.cxx $(DEPS)
#		$(CXX) $(CXXFLAGS) $(ROOT_FLAGS) -c $< -o $@ $(CPPFLAGS)


build/forestBDT.o: forestBDT.cxx
		$(CXX) $(CXXFLAGS) $(ROOT_FLAGS) -c $< -o $@ $(CPPFLAGS)

build/arrayBDT.o: arrayBDT.cxx
		$(CXX) $(CXXFLAGS) $(ROOT_FLAGS) -c $< -o $@ $(CPPFLAGS)

build/helpersBDT.o:  helpersBDT.cxx
		$(CXX) $(CXXFLAGS) $(ROOT_FLAGS) -c $< -o $@ $(CPPFLAGS)

build/unique_bdt.o:  ../src/unique_bdt.cxx
		$(CXX) $(CXXFLAGS) $(ROOT_FLAGS) -c $< -o $@ $(CPPFLAGS)

clean :
	$(RM) build/*.o *.o

distclean : clean
	$(RM) $(EXE)
