/********************************************************************
* EventDict.h
********************************************************************/
#ifdef __CINT__
#error EventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDict();
extern void G__cpp_setup_inheritanceEventDict();
extern void G__cpp_setup_typetableEventDict();
extern void G__cpp_setup_memvarEventDict();
extern void G__cpp_setup_globalEventDict();
extern void G__cpp_setup_memfuncEventDict();
extern void G__cpp_setup_funcEventDict();
extern void G__set_cpp_environmentEventDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "Event.h"
#include <algorithm>

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDictLN_TClass;
extern G__linked_taginfo G__EventDictLN_TList;
extern G__linked_taginfo G__EventDictLN_TObjArray;
extern G__linked_taginfo G__EventDictLN_TObject;
extern G__linked_taginfo G__EventDictLN_TString;
extern G__linked_taginfo G__EventDictLN_TNamed;
extern G__linked_taginfo G__EventDictLN_TDatime;
extern G__linked_taginfo G__EventDictLN_TClonesArray;
extern G__linked_taginfo G__EventDictLN_TAxis;
extern G__linked_taginfo G__EventDictLN_TAttLine;
extern G__linked_taginfo G__EventDictLN_TArrayF;
extern G__linked_taginfo G__EventDictLN_TH1F;
extern G__linked_taginfo G__EventDictLN_TLine;
extern G__linked_taginfo G__EventDictLN_TArrayI;
extern G__linked_taginfo G__EventDictLN_TRef;
extern G__linked_taginfo G__EventDictLN_TLorentzVector;
extern G__linked_taginfo G__EventDictLN___malloc_alloc_templatelE0gR;
extern G__linked_taginfo G__EventDictLN_string;
extern G__linked_taginfo G__EventDictLN_UShortVector;
extern G__linked_taginfo G__EventDictLN_vectorlEunsignedsPshortcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEunsignedsPshortcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlEunsignedsPshortcOlonggR;
extern G__linked_taginfo G__EventDictLN_EventHeader;
extern G__linked_taginfo G__EventDictLN_Event;
extern G__linked_taginfo G__EventDictLN_EventcLcLdA;
extern G__linked_taginfo G__EventDictLN_vectorlEintcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEintcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlEintcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlEshortcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEshortcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlEshortcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlEdoublecO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEdoublecO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlEdoublecOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlETLinecO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETLinecO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlETLinecOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlETObjectcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETObjectcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlETObjectcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlETNamedcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETNamedcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlETNamedcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlEstringcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEstringcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlEstringcOlonggR;
extern G__linked_taginfo G__EventDictLN_dequelETAttLinecO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_dequelETAttLinecO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlETAttLinecOlonggR;
extern G__linked_taginfo G__EventDictLN_dequelETAttLinecO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_listlEconstsPTObjectmUcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_listlEconstsPTObjectmUcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlEconstsPTObjectmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_listlEconstsPTObjectmUcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_listlEstringcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_listlEstringcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlEstringcOlonggR;
extern G__linked_taginfo G__EventDictLN_listlEstringcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_listlEstringmUcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_listlEstringmUcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlEstringmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_listlEstringmUcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslETNamedmUgR;
extern G__linked_taginfo G__EventDictLN_maplETNamedmUcOintcOlesslETNamedmUgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETNamedmUcOintgR;
extern G__linked_taginfo G__EventDictLN_maplETNamedmUcOintcOlesslETNamedmUgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlEintcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplETNamedmUcOintcOlesslETNamedmUgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslETStringgR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTListmUcOlesslETStringgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETStringcOTListmUgR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTListmUcOlesslETStringgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlETListmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTListmUcOlesslETStringgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTStringmUcOlesslETStringgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETStringcOTStringmUgR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTStringmUcOlesslETStringgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlETStringmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTStringmUcOlesslETStringgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslEEventHeadergR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringmUcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEEventHeadercOTStringmUgR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringmUcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringmUcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEEventHeadercOTStringgR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlETStringcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOstringcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEEventHeadercOstringgR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOstringcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOstringcOlesslEEventHeadergRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslETAxismUgR;
extern G__linked_taginfo G__EventDictLN_maplETAxismUcOintcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETAxismUcOintgR;
extern G__linked_taginfo G__EventDictLN_maplETAxismUcOintcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_maplETAxismUcOintcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_setlETAxismUcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_setlETAxismUcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlETAxismUcOlonggR;
extern G__linked_taginfo G__EventDictLN_setlETAxismUcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_multimaplETNamedmUcOintcOlesslETNamedmUgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_multimaplETNamedmUcOintcOlesslETNamedmUgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_multimaplETNamedmUcOintcOlesslETNamedmUgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_multisetlETAxismUcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_multisetlETAxismUcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_multisetlETAxismUcOlesslETAxismUgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_vectorlETAxismUcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETAxismUcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlETAxismUcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlEvectorlETAxismUcO__malloc_alloc_templatelE0gRsPgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEvectorlETAxismUcO__malloc_alloc_templatelE0gRsPgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlEvectorlETAxismUcO__malloc_alloc_templatelE0gRsPgRcOlonggR;
extern G__linked_taginfo G__EventDictLN_lesslEstringgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOvectorlEintcO__malloc_alloc_templatelE0gRsPgRcOlesslEstringgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEstringcOvectorlEintcO__malloc_alloc_templatelE0gRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOvectorlEintcO__malloc_alloc_templatelE0gRsPgRcOlesslEstringgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_bidirectional_iteratorlEvectorlEintcO__malloc_alloc_templatelE0gRsPgRcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOvectorlEintcO__malloc_alloc_templatelE0gRsPgRcOlesslEstringgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_pairlEfloatcOfloatgR;
extern G__linked_taginfo G__EventDictLN_dequelEpairlEfloatcOfloatgRcO__malloc_alloc_templatelE0gRsPgR;
extern G__linked_taginfo G__EventDictLN_dequelEpairlEfloatcOfloatgRcO__malloc_alloc_templatelE0gRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_random_access_iteratorlEpairlEfloatcOfloatgRcOlonggR;
extern G__linked_taginfo G__EventDictLN_dequelEpairlEfloatcOfloatgRcO__malloc_alloc_templatelE0gRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_Track;
extern G__linked_taginfo G__EventDictLN_BigTrack;
extern G__linked_taginfo G__EventDictLN_HistogramManager;

/* STUB derived class for protected member access */
