.TH xrdgsiproxy 1 "8 March 2011"
.SH NAME
xrdgsiproxy - generate a proxy X.509 certificate
.SH SYNOPSIS
.nf

\fBxrdgsiproxy\fR [\fB-h\fR] [\fImode\fR] [\fB-debug\fR] [\fB-f\fR [\fB-out\fR] \fIfile\fR]
.fi
.br
.ad l
.SH DESCRIPTION
The \fBxrdgsiproxy\fR utility displays, creates, and destroys X.509 user proxy
certificates used by the grid security infrastructure
(\fBgsi\fR) security protocol.
.SH OPERANDS
\fImode\fR
.RS 5
\fBinit\fR    create proxy certificate and related proxy file
.br
\fBinfo\fR    display content of existing proxy file
.br
\fBdestroy\fR delete existing proxy file
.RE
.br
.SH OPTIONS
.B -h
display help
.TP
\fB-f\fR [\fB-out\fR] \fIfile\fR
Non-standard location of proxy file
.TP
.BI init \0 mode \0 only:
.TP
\fB-certdir\fR \fIdir\fR
Non-standard location of directory with information about known CAs
.TP
\fB-cert\fR    \fIfile\fR
Non-standard location of certificate for which proxies are wanted
.TP
\fB-key\fR     \fIfile\fR
Non-standard location of private key to be used to sign the proxy
.TP
\fB-bits\fR    \fIn\fR
Strength in bits of the key [default 512]
.TP
\fB-valid\fR   \fIhh:mm\fR
Time validity of the proxy certificate [default 12:00]
.TP
\fB-path-length\fR \fIlen\fR
Max number of descendent levels below this proxy [default 0]
.SH NOTES
Complete HTML documentation can be found at
.ce 1
http://xrootd.org/doc/prod/sec_config.htm
.br
Documentation for all components associated with \fBxrdgsiproxy\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBxrdgsiproxy\fR command is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
