.TH xrdstagetool 1 "8 March 2011"
.SH NAME
xrdstagetool - stage one or more files
.SH SYNOPSIS
.nf

\fBxrdstagetool\fR [\fIoptions\fR] \fIpaths\fR

\fBxrdstagetool\fR [\fIoptions\fR] \fItarget\fR \fB-S\fR \fIsource\fR

.fi
.br
.ad l
.SH DESCRIPTION
The \fBxrdstagetool\fR utility stages missing files into an xrootd server;
optionally using a specific source server.
The \fBxprep\fR command provides a similar, though not identical, set of features.
Usage synopsis can be displayed by typing "\fBxrdstagetool\fR".
Currently, only the usage synopsis is available as documentation.
.SH NOTES
Documentation for all components associated with \fBxrdstagetool\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBxrdstagetool\fR command is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
