//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Wed May 17 16:09:48 2017 by ROOT version 6.09/03)
//      from the StreamerInfo in file /var/tmp/ExtHit/b2.root
//////////////////////////////////////////////////////////


#ifndef Belle2__RelationsInterface_TObject__h
#define Belle2__RelationsInterface_TObject__h
class TObject;
namespace Belle2 {
template <typename T0> class RelationsInterface;
template <> class RelationsInterface<TObject>;
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"

namespace Belle2 {
template <typename T0> class RelationsInterface;
template <> class RelationsInterface<TObject> : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.

   RelationsInterface();
   RelationsInterface(const RelationsInterface & );
   ~RelationsInterface() override;

   ClassDefOverride(RelationsInterface,0); // Generated by MakeProject.
};
} // namespace
#endif
