#!/bin/bash
# Name: addtest
# Desc: Updates the Makefile
# Args: $1 -> test Name
#	$2 -> test directory

printUSAGE() { 
		echo "" ;
		echo "Usage: addtest [test name] [test path]"  ;
	       	echo "  where test name is the name of the test to be added"
		echo "  where test path is the directory path for the test to be added"; 
	        echo "";
	        echo "addtest is a script to add test to the directories, update
		Makefile, create .ref, runTESTNAME.C and update cvs repository";
	        echo "" ;
		exit 1; 
	     }

printALREADY_EXIST() {
			echo "" ;
			echo "Test name already exists" ;
			exit 1 ;
		     }

printERROR() { echo "ERROR: $@." >&2 ;  }


check_target=`grep -F " $1 " $2/Makefile`
#echo $check_target


#if [ "$check_target" != "" ]; then
	#printALREADY_EXIST ;
#fi

check_target2=`grep -F "$1:" $2/Makefile`
#echo $check_target2


if [ "$check_target" != "" ]; then
	printALREADY_EXIST ;
fi

#printERROR ;

# check whether sufficient args are given

if [ $# -lt 2 ] ; then 
	printUSAGE ; 
fi

if [ ! -d "$2" ] ; then
	printERROR "The source $2 is not a directory, or does not exist"
	echo "use 'mktest $2' to add test directory"
	
	#mktest $2
	selection=
	until [ "$selection" = "0" ]; do
	    echo "1 - Create $2 and add test '$1'"
	    echo "0 - exit"
	    echo ""
	    echo -n "Enter selection: "
	    read selection
	    echo ""
	    case $selection in
	        1 )  mktest $2 ; addtest $1 $2; exit 1;;
	        0 ) exit ;;
	        * ) echo "Please enter 1 or 0"
	    esac
	done
fi


cd $2

sed -e "s/TEST_TARGETS += /TEST_TARGETS += $1 /g" Makefile > Makefile1
rm Makefile

mv Makefile1 Makefile

#sed -e "s/mytest/$1/g" Makefile1 > Makefile
#rm Makefile1

echo "" >> Makefile
echo "$1: $1.log" >> Makefile
echo "	\$(TestDiff)" >> Makefile

if [ ! -s $1.ref ]; then
    echo "" > $1.ref
    echo "Processing run$1.C..." >> $1.ref
fi

if [ ! -s $run$1.C ]; then
    echo "{"  > run$1.C
    echo "// Fill out the code of the actual test" >> run$1.C 
    echo "}" >> run$1.C 
fi

echo "Message: Test successfully added"
