#!/bin/bash
# Name: addtest
# Desc: Updates the Makefile
# Args: $1 -> test Name
#	$2 -> test directory

printUSAGE() { echo "Give the Directory  $@."  ;exit 1; }

# check whether sufficient args are given

if [ $# -lt 2 ] ; then printUSAGE "for the test" ; fi

cd $2

sed -e "s/TEST_TARGETS += /TEST_TARGETS += $1.* /g" Makefile > Makefile1
rm Makefile

#sed -e "s/testWithDiff/$1/g" Makefile1 > Makefile
#rm Makefile1

echo "$1 : $1.log" >> Makefile
echo "\$(TestDiff)" >> Makefile

touch $1.ref
