#!/bin/bash

# Error Message
printERROR() { echo "Error: $@." >&2 ; exit 1; }

PARENT_DIR=${1%/*}
echo $PARENT_DIR

count="'wc -m $1'"
r=`echo $1 | grep '/'`
echo $r

	if [ "$r" == "$1" ]; then 
	#	#printERROR "the source $1 is not dir, or does not exist"
		if [ ! -d "$PARENT_DIR" ] ; then
		mktest $PARENT_DIR
		fi
		
	fi

#Make Direcroty	
mkdir $1

#Copy Makefile.template to the new test directory
cp root/Makefile.template $1


#Add to CVS
#cvs add $1

# change directory and rename the Makfile.templete to Makefile
cd $1
mv Makefile.template Makefile

#Add & Commit Makefile to CVS
#cvs add Makefile
#cvs commit -m "Makefile" Makefile
