#!/bin/bash
# Name: mktest
# Desc: Add test directories, copies Makefiles and update CVS repository
# Args: $1 -> dest dir

# Saves the parent directory
PARENT_DIR=${1%/*}

# if this is the top directory or not
r=`echo $1 | grep '/'`

	if [ "$r" == "$1" ]; then 
		
		if [ ! -d "$PARENT_DIR" ] ; then
			mktest $PARENT_DIR
		fi
		
	fi

#Make Direcroty	
mkdir $1

#Copy Makefile.template to the new test directory
cp root/Makefile.template $1

#Add to CVS
#cvs add $1

# change directory and rename the Makfile.templete to Makefile
cd $1
mv Makefile.template Makefile

#Add & Commit Makefile to CVS
#cvs add Makefile
#cvs commit -m "Makefile" Makefile
