set(histv7_headers
    ROOT/RAxes.hxx
    ROOT/RBinIndex.hxx
    ROOT/RBinIndexRange.hxx
    ROOT/RHistEngine.hxx
    ROOT/RHistUtils.hxx
    ROOT/RLinearizedIndex.hxx
    ROOT/RRegularAxis.hxx
    ROOT/RVariableBinAxis.hxx
    ROOT/RWeight.hxx
)
