set(histv7_headers
    ROOT/RAxes.hxx
    ROOT/RBinIndex.hxx
    ROOT/RBinIndexRange.hxx
    ROOT/RBinWithError.hxx
    ROOT/RCategoricalAxis.hxx
    ROOT/RHist.hxx
    ROOT/RHistAutoAxisFiller.hxx
    ROOT/RHistConcurrentFiller.hxx
    ROOT/RHistEngine.hxx
    ROOT/RHistFillContext.hxx
    ROOT/RHistStats.hxx
    ROOT/RHistUtils.hxx
    ROOT/RLinearizedIndex.hxx
    ROOT/RRegularAxis.hxx
    ROOT/RVariableBinAxis.hxx
    ROOT/RWeight.hxx
)
