#ifndef ROOT_RVersion
#define ROOT_RVersion

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if ROOT_VERSION_CODE >= ROOT_VERSION(2,23,4)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define ROOT_RELEASE "5.15/06"
#define ROOT_RELEASE_DATE "Apr 24 2007"
#define ROOT_RELEASE_TIME "17:30:37"
#define ROOT_VERSION_CODE 331526
#define ROOT_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#endif
