/********************************************************************
* EventDict.h
********************************************************************/
#ifdef __CINT__
#error EventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDict();
extern void G__cpp_setup_inheritanceEventDict();
extern void G__cpp_setup_typetableEventDict();
extern void G__cpp_setup_memvarEventDict();
extern void G__cpp_setup_globalEventDict();
extern void G__cpp_setup_memfuncEventDict();
extern void G__cpp_setup_funcEventDict();
extern void G__set_cpp_environmentEventDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "Event.h"
#include <algorithm>

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDictLN_TClass;
extern G__linked_taginfo G__EventDictLN_TObject;
extern G__linked_taginfo G__EventDictLN_TNamed;
extern G__linked_taginfo G__EventDictLN_TList;
extern G__linked_taginfo G__EventDictLN_TObjArray;
extern G__linked_taginfo G__EventDictLN_TString;
extern G__linked_taginfo G__EventDictLN_TDatime;
extern G__linked_taginfo G__EventDictLN_TClonesArray;
extern G__linked_taginfo G__EventDictLN_TAxis;
extern G__linked_taginfo G__EventDictLN_TAttLine;
extern G__linked_taginfo G__EventDictLN_TArrayF;
extern G__linked_taginfo G__EventDictLN_TH1F;
extern G__linked_taginfo G__EventDictLN_TLine;
extern G__linked_taginfo G__EventDictLN_TArrayI;
extern G__linked_taginfo G__EventDictLN_TRef;
extern G__linked_taginfo G__EventDictLN_TRefArray;
extern G__linked_taginfo G__EventDictLN_TLorentzVector;
extern G__linked_taginfo G__EventDictLN_string;
extern G__linked_taginfo G__EventDictLN_UShortVector;
extern G__linked_taginfo G__EventDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlEunsignedsPshortcOlonggR;
extern G__linked_taginfo G__EventDictLN_EventHeader;
extern G__linked_taginfo G__EventDictLN_Event;
extern G__linked_taginfo G__EventDictLN_EventcLcLEEventType;
extern G__linked_taginfo G__EventDictLN_EventcLcLdA;
extern G__linked_taginfo G__EventDictLN_allocatorlEintgR;
extern G__linked_taginfo G__EventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEintcOallocatorlEintgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlEintcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEshortcOallocatorlEshortgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlEshortcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEdoublecOallocatorlEdoublegRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlEdoublecOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlETLinecOallocatorlETLinegRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETLinecOallocatorlETLinegRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlETLinecOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlETObjectcOallocatorlETObjectgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETObjectcOallocatorlETObjectgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlETObjectcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlETNamedcOallocatorlETNamedgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETNamedcOallocatorlETNamedgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlETNamedcOlonggR;
extern G__linked_taginfo G__EventDictLN_allocatorlEstringgR;
extern G__linked_taginfo G__EventDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlEstringcOlonggR;
extern G__linked_taginfo G__EventDictLN_allocatorlETAttLinegR;
extern G__linked_taginfo G__EventDictLN_dequelETAttLinecOallocatorlETAttLinegRsPgR;
extern G__linked_taginfo G__EventDictLN_dequelETAttLinecOallocatorlETAttLinegRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__RanitlETAttLinecOlonggR;
extern G__linked_taginfo G__EventDictLN_dequelETAttLinecOallocatorlETAttLinegRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_allocatorlEconstsPTObjectmUgR;
extern G__linked_taginfo G__EventDictLN_listlEconstsPTObjectmUcOallocatorlEconstsPTObjectmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_listlEconstsPTObjectmUcOallocatorlEconstsPTObjectmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlEconstsPTObjectmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_listlEconstsPTObjectmUcOallocatorlEconstsPTObjectmUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_listlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EventDictLN_listlEstringcOallocatorlEstringgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlEstringcOlonggR;
extern G__linked_taginfo G__EventDictLN_listlEstringcOallocatorlEstringgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_allocatorlEstringmUgR;
extern G__linked_taginfo G__EventDictLN_listlEstringmUcOallocatorlEstringmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_listlEstringmUcOallocatorlEstringmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlEstringmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_listlEstringmUcOallocatorlEstringmUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslETNamedmUgR;
extern G__linked_taginfo G__EventDictLN_maplETNamedmUcOintcOlesslETNamedmUgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETNamedmUcOintgR;
extern G__linked_taginfo G__EventDictLN_maplETNamedmUcOintcOlesslETNamedmUgRcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlEintcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplETNamedmUcOintcOlesslETNamedmUgRcOallocatorlEintgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslETStringgR;
extern G__linked_taginfo G__EventDictLN_allocatorlETListmUgR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTListmUcOlesslETStringgRcOallocatorlETListmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETStringcOTListmUgR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTListmUcOlesslETStringgRcOallocatorlETListmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlETListmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTListmUcOlesslETStringgRcOallocatorlETListmUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_allocatorlETStringmUgR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTStringmUcOlesslETStringgRcOallocatorlETStringmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETStringcOTStringmUgR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTStringmUcOlesslETStringgRcOallocatorlETStringmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlETStringmUcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplETStringcOTStringmUcOlesslETStringgRcOallocatorlETStringmUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslEEventHeadergR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringmUcOlesslEEventHeadergRcOallocatorlETStringmUgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEEventHeadercOTStringmUgR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringmUcOlesslEEventHeadergRcOallocatorlETStringmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringmUcOlesslEEventHeadergRcOallocatorlETStringmUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_allocatorlETStringgR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringcOlesslEEventHeadergRcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEEventHeadercOTStringgR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringcOlesslEEventHeadergRcOallocatorlETStringgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlETStringcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOTStringcOlesslEEventHeadergRcOallocatorlETStringgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOstringcOlesslEEventHeadergRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEEventHeadercOstringgR;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOstringcOlesslEEventHeadergRcOallocatorlEstringgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_maplEEventHeadercOstringcOlesslEEventHeadergRcOallocatorlEstringgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_lesslETAxismUgR;
extern G__linked_taginfo G__EventDictLN_maplETAxismUcOintcOlesslETAxismUgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlETAxismUcOintgR;
extern G__linked_taginfo G__EventDictLN_maplETAxismUcOintcOlesslETAxismUgRcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_maplETAxismUcOintcOlesslETAxismUgRcOallocatorlEintgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_allocatorlETAxismUgR;
extern G__linked_taginfo G__EventDictLN_setlETAxismUcOlesslETAxismUgRcOallocatorlETAxismUgRsPgR;
extern G__linked_taginfo G__EventDictLN_setlETAxismUcOlesslETAxismUgRcOallocatorlETAxismUgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlETAxismUcOlonggR;
extern G__linked_taginfo G__EventDictLN_setlETAxismUcOlesslETAxismUgRcOallocatorlETAxismUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_multimaplETNamedmUcOintcOlesslETNamedmUgRcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EventDictLN_multimaplETNamedmUcOintcOlesslETNamedmUgRcOallocatorlEintgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_multimaplETNamedmUcOintcOlesslETNamedmUgRcOallocatorlEintgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_multisetlETAxismUcOlesslETAxismUgRcOallocatorlETAxismUgRsPgR;
extern G__linked_taginfo G__EventDictLN_multisetlETAxismUcOlesslETAxismUgRcOallocatorlETAxismUgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN_multisetlETAxismUcOlesslETAxismUgRcOallocatorlETAxismUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_vectorlETAxismUcOallocatorlETAxismUgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlETAxismUcOallocatorlETAxismUgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlETAxismUcOlonggR;
extern G__linked_taginfo G__EventDictLN_vectorlEvectorlETAxismUcOallocatorlETAxismUgRsPgRcOallocatorlEvectorlETAxismUcOallocatorlETAxismUgRsPgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEvectorlETAxismUcOallocatorlETAxismUgRsPgRcOallocatorlEvectorlETAxismUcOallocatorlETAxismUgRsPgRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN__RanitlEvectorlETAxismUcOallocatorlETAxismUgRsPgRcOlonggR;
extern G__linked_taginfo G__EventDictLN_lesslEstringgR;
extern G__linked_taginfo G__EventDictLN_allocatorlEvectorlEintcOallocatorlEintgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_pairlEstringcOvectorlEintcOallocatorlEintgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__BiditlEvectorlEintcOallocatorlEintgRsPgRcOlonggR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_pairlEfloatcOfloatgR;
extern G__linked_taginfo G__EventDictLN_allocatorlEpairlEfloatcOfloatgRsPgR;
extern G__linked_taginfo G__EventDictLN_dequelEpairlEfloatcOfloatgRcOallocatorlEpairlEfloatcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_dequelEpairlEfloatcOfloatgRcOallocatorlEpairlEfloatcOfloatgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__EventDictLN__RanitlEpairlEfloatcOfloatgRcOlonggR;
extern G__linked_taginfo G__EventDictLN_dequelEpairlEfloatcOfloatgRcOallocatorlEpairlEfloatcOfloatgRsPgRsPgRcLcLreverse_iterator;
extern G__linked_taginfo G__EventDictLN_Track;
extern G__linked_taginfo G__EventDictLN_BigTrack;
extern G__linked_taginfo G__EventDictLN_HistogramManager;

/* STUB derived class for protected member access */
