#ifndef ROOT_RVersion
#define ROOT_RVersion

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if ROOT_VERSION_CODE >= ROOT_VERSION(2,23,4)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define ROOT_RELEASE "5.29/01"
#define ROOT_RELEASE_DATE "Dec 15 2010"
#define ROOT_RELEASE_TIME "15:00:43"
#define ROOT_SVN_REVISION 37585
#define ROOT_SVN_BRANCH "trunk"
#define ROOT_VERSION_CODE 335105
#define ROOT_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#endif
