#ifndef ROOT_RVersion
#define ROOT_RVersion

/* Version information automatically generated by installer. */

/*
 * These macros can be used in the following way:
 *
 *    #if ROOT_VERSION_CODE >= ROOT_VERSION(2,23,4)
 *       #include <newheader.h>
 *    #else
 *       #include <oldheader.h>
 *    #endif
 *
*/

#define ROOT_RELEASE "5.27/05"
#define ROOT_RELEASE_DATE "Jun 30 2010"
#define ROOT_RELEASE_TIME "09:14:45"
#define ROOT_SVN_REVISION 34195
#define ROOT_SVN_BRANCH "trunk"
#define ROOT_VERSION_CODE 334597
#define ROOT_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))

#endif
