#Disable until boost is not present in the headers
test:
	@echo nothing > /dev/null

clean:
	@echo nothing > /dev/null

#CLEAN_TARGETS += *.log dummy* *pcm *o *rflx.* $(ALL_LIBRARIES)
#TEST_TARGETS += execLibLoad

#ifeq ($(strip $(ROOTTEST_HOME)),)
#	export ROOTTEST_HOME:=$(shell expr $(CURDIR) : '\(.*/roottest/\)')
#endif

#include $(ROOTTEST_HOME)/scripts/Rules.mk
#include $(ROOTTEST_HOME)/scripts/Reflex.mk

#GENREFLEXCXXFLAGS += --interpreteronly -I ./ -I CoralBase
#CXXFLAGS += -I ./ -I CoralBase 

#execLibLoad.log: PyCool_rflx.$(ObjSuf)
