#!/bin/sh

# $Id: xrdcksum,v 1.1 2004/11/13 15:18:43 elmer Exp $
#
#  Simple wrapper script to calculate the 'cksum' of a file and print 
#  only the checksum value for use by xrootd
#

result=`cksum ${1?} 2> /dev/null `

if [ $? -ne 0 ] ; then 
    exit 1
else
    echo $result | cut -d' ' -f1
    exit 0
fi

