.\" 
.\" $Id: olbd.1,v 1.1 2005/03/21 21:42:21 rdm Exp $
.\"
.TH XROOTD 1 "Version 4" "ROOT" 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
olbd \- Open Load Balancer Daemon used by xrootd
.SH SYNOPSIS
.B oldb
.I [options] [exported directories]
.SH "DESCRIPTION"
This manual page documents briefly the
.BR olbd
program.
.PP
.B olbd
is the Open Load Balancer Daemon for the 
.B ROOT 
extended remote file server daemon.
.SH "SEE ALSO"
\fIxrootd\fR(1), \fIrootd\fR(1), \fIcmsd\fR(1)
.PP 
See also 
.I http://xrootd.slac.stanford.edu
for more on the extended \fBROOT\fR server.
.PP
For more information on the \fBROOT\fR system, please refer to 
.UR http://root.cern.ch/
.I http://root.cern.ch
.UE
.SH "ORIGINAL AUTHORS"
The ROOT team (see web page above):
.RS
.B Rene Brun 
and
.B Fons Rademakers
.RE
.SH "COPYRIGHT"
This library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of the
License, or (at your option) any later version.
.P
This library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
.P
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.SH AUTHOR 
This manual page was originally written by Christian Holm Christensen
<cholm@nbi.dk>, for the Debian GNU/Linux system and ROOT version 3.
