
/********************************************************
* G__header.h
*   Built in struct/union declaration
*   Automatically generated by makecint and cint -c1
*  Copyright : 1991 Masaharu Goto
********************************************************/


