#########################################

ARCH          = linux

CXX           =
ObjSuf        = o
SrcSuf        = cxx
ExeSuf        =
DllSuf        = so
OutPutOpt     = -o 

ROOTCFLAGS   := $(shell root-config --cflags)
ROOTLIBS     := $(shell root-config --libs)
ROOTGLIBS    := $(shell root-config --glibs)
ROOTLIBDIR   := $(shell root-config --libdir)

CXX           = icc
CXXFLAGS      = -O -g
LD            = icc
LDFLAGS       = -O -g -Wl,-rpath,$(ROOTLIBDIR)
SOFLAGS       = -shared

CXXFLAGS     += $(ROOTCFLAGS)
LIBS          = $(ROOTLIBS) $(SYSLIBS)
GLIBS         = $(ROOTGLIBS) $(SYSLIBS)

#########################################

ROOTSHOWERS  := $(wildcard *.cxx) RootShowerDict.$(SrcSuf)
ROOTSHOWERO  := $(ROOTSHOWERS:.cxx=.o)
ROOTSHOWER    = RootShower$(ExeSuf)

OBJS          = $(ROOTSHOWERO)

PROGRAMS      = $(ROOTSHOWER)

#########################################

.SUFFIXES: .$(SrcSuf) .$(ObjSuf) .$(DllSuf)

all:            $(PROGRAMS)

$(ROOTSHOWER):  $(ROOTSHOWERO)
		$(LD) $(LDFLAGS) $^ $(GLIBS) -lEG -lHtml $(OutPutOpt)$@
		@echo "$@ done"

RootShowerDict.$(SrcSuf): MyParticle.h MyDetector.h MyEvent.h RSLinkDef.h
		@echo "Generating dictionary $@..."
		@rootcint -f $@ -c $^

clean:
		rm -f *.o RootShowerDict.*

distclean:      clean
		rm -f RootShower

#########################################

.$(SrcSuf).$(ObjSuf):
		$(CXX) $(CXXFLAGS) -c $<

#########################################



