.TH xprep 1 "8 March 2011"
.SH NAME
xprep - prepare one or more files for access
.SH SYNOPSIS
.nf

\fBxprep\fR [\fIoptions\fR] \fItarget\fR [\fIpaths\fR]

\fIoptions\fR: [\fB-d\fR \fIn\fR] [\fB-f\fR \fIfn\fR] [\fB-p\fR \fIprty\fR] [\fB-s\fR] [\fB-S\fR] [\fB-w\fR]

\fItarget\fR:  \fIhost\fR[\fB:\fR\fIport\fR][,\fItarget\fR]

\fIpaths\fR:   \fIpath\fR [\fIpaths\fR]
.fi
.br
.ad l
.SH DESCRIPTION
The \fBxprep\fR utility prepares one or more files for subsequent access
by an application.  Usage synopsis can be displayed by typing "\fBxprep\fR".
Currently, only the usage synopsis is available as documentation.
.SH NOTES
Documentation for all components associated with \fBxprep\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBxprep\fR command is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
