.TH xrd 1 "8 March 2011"
.SH NAME
xrd - xrootd file and directory meta-data utility
.SH SYNOPSIS
.nf

\fBxrd\fR [\fIhost\fR] [\fIoptions\fR] [\fIcommand\fR]

\fIoptions\fR: [\fB-DS\fR\fIpname stringval\fR] [\fB-DI\fR\fIpname numberval\fR] [\fIoptions\fR]
         [\fB-O\fR\fIopaqueinfo\fR] [\fB-h\fR]
.fi
.br
.ad l
.SH DESCRIPTION
The \fBxrd\fR utility executes meta-data oriented operations
(e.g., ls, mv, rm, etc.) on one or more xrootd servers.
Usage synopsis can be displayed by typing "\fBxrd -h\fR". Command help
is available by invoking \fBxrd\fR with no command line options or parameters
and then typing "help" in response to the input prompt.
.SH OPTIONS
\fB-DS\fR\fIpname stringval\fR
.RS 3
set the internal parameter \fIpname\fR with the string value \fIstringval\fR.

.RE
\fB-DI\fR\fIpname numberval\fR
.RS 3
set the internal parameter \fIpname\fR with the numeric value \fInumberval\fR.

.RE
\fB-O\fR\fIopaqueinfo\fR
.RS 3
add opaque information \fIopaqueinfo\fR to any path.

.RE
\fB-h\fR    display usage information.
.SH NOTES
See XrdClientConst.hh for a list of parameters.
Documentation for all components associated with \fBxrd\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBxrd\fR command is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
