.TH xrdadler32 1 "8 March 2011"
.SH NAME
xrdadler32 - compute and display an adler32 checksum
.SH SYNOPSIS
.nf

\fBxrdadler32\fR [\fIfile\fR]

.fi
.br
.ad l
.SH DESCRIPTION
The \fBxrdadler32\fR utiliity
computes and displays an adler32 checksum value for a file.
Usage synopsis can be displayed by typing "\fBxrdadler32 -h\fR".
Currently, only the usage synopsis is available as documentation.
.SH NOTES
Documentation for all components associated with \fBxrdadler32\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBxrdadler32\fR command is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
