.PU
.TH FFT 3 
.SH NAME
fft.h \- FFT library for cint

.SH SYNOPSIS
.br
#include <fft.h>

fft << (array)time << (array)in >> (array)freq >> (carray)o1 >> \'\\n\';

fft << (array)time << (carray)in >> (array)freq >> (carray)o1 >> \'\\n\';

ifft << (array)freq << (carray)in >> (array)time >> (array)o1 >> \'\\n\';

ifft << (array)freq << (carray)in >> (array)time >> (carray)o1 >> \'\\n\';

spectrum << (array)time << (array)in >> (array)freq >> (array)o1>>\'\\n\';

cepstrum << (array)time << (array)in >> (array)freq >> (array)o1>>\'\\n\';


.SH DESCRIPTION
 <fft.h> is header file for a Fast Fourier Transfer calculation library for 
CINT.  
FFT calculation type object fft,ifft,spectrum and cepstrum are instantiated.
Operator << and >> are overloaded to specify input and output buffer to
the FFT calculation routine.
FFT calculation program can be written like below.

.nf
	array time=array(0.0  , 5*3.1415 , 1024);  // x is time
	array in,freq;
	c = sin(time);

	carray out1;
	fft << time << in >> freq >> out >> \'\\n\';

	array in2;
	ifft << freq << out >> time >> in2 >> \'\\n\';

	array out2;
	spectrum << time << in >> freq >> out2 >> \'\\n\';
.fi

.SH COMPATIBILITY
	HP-UX 8.0 or later
.SH SEE ALSO
	cint(1),array.h(3)
.SH AUTHOR
Masaharu Goto

Copyright (c) 1996~1999 Masaharu Goto
