#ifdef __CINT__ 
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ class RooRandomizeParamMCSModule+ ;
#pragma link C++ class RooRangeBinning+ ;
#pragma link C++ class RooRealAnalytic+ ;
#pragma link C++ class RooRealBinding+ ;
#pragma link C++ class RooRealConstant+ ;
#pragma link C++ class RooRealIntegral+ ;
#pragma link C++ class RooRealMPFE+ ;
#pragma link C++ class RooRealProxy+ ;
#pragma link C++ class RooRealVar- ;
#pragma link C++ class RooRealVarSharedProperties+ ;
#pragma link C++ class RooRefCountList+ ;
#pragma link C++ class RooScaledFunc+ ;
#pragma link C++ class RooSegmentedIntegrator1D+ ;
#pragma link C++ class RooSegmentedIntegrator2D+ ;
#pragma link C++ class RooSetPair+ ;
#pragma link C++ class RooSetProxy+ ;
#pragma link C++ class RooSharedProperties+ ;
#pragma link C++ class RooSharedPropertiesList+ ;
#pragma link C++ class RooSimGenContext+ ;
#pragma link C++ class RooStreamParser+ ;
#pragma link C++ class RooStringVar+ ;
#pragma link C++ class RooSuperCategory+ ;
#pragma link C++ class RooTable+ ;
#pragma link C++ class RooThreshEntry+ ;
#pragma link C++ class RooThresholdCategory+ ;
#pragma link C++ class RooTObjWrap+ ;
#pragma link C++ class RooTrace+ ;
#pragma link C++ class RooTreeData+ ;
#pragma link C++ class RooUnblindCPAsymVar+ ;
#pragma link C++ class RooUnblindOffset+ ;
#pragma link C++ class RooUnblindPrecision+ ;
#pragma link C++ class RooUnblindUniform+ ;
#pragma link C++ class RooUniformBinning+ ;
#pragma link C++ class RooSimultaneous+ ;
#pragma link C++ class RooRealSumPdf ;
#pragma link C++ class RooResolutionModel ;
#pragma link off class RooSimPdfBuilder ;
#pragma link off class RooErrorHandler+ ;
#pragma link off class RooNag+ ;
#endif 
 
