//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef CaloClusterMomentContainer_p1_h
#define CaloClusterMomentContainer_p1_h
class CaloClusterMomentContainer_p1;

#include "Riostream.h"
#include <vector>
#include "CaloClusterMomentContainer_p1.h"

class CaloClusterMomentContainer_p1 {

public:
// Nested classes forward declaration.
class ClusterMoment_p;

public:
// Nested classes declaration.
class ClusterMoment_p {

public:
// Nested classes declaration.

public:
// Data Members.
   short       key;         //
   float       value;       //

   ClusterMoment_p();
   ClusterMoment_p(const ClusterMoment_p & );
   virtual ~ClusterMoment_p();

};

public:
// Data Members.
   vector<CaloClusterMomentContainer_p1::ClusterMoment_p> m_store;     //(CaloClusterMomentContainer_p1::ClusterMoment_p)
   unsigned short                                         m_nMoments;    //

   CaloClusterMomentContainer_p1();
   CaloClusterMomentContainer_p1(const CaloClusterMomentContainer_p1 & );
   virtual ~CaloClusterMomentContainer_p1();

};
#endif
