//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef HepLorentzVector_p1_h
#define HepLorentzVector_p1_h
class HepLorentzVector_p1;

#include "TNamed.h"

class HepLorentzVector_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   double      m_px;        //
   double      m_py;        //
   double      m_pz;        //
   double      m_ene;       //

   HepLorentzVector_p1();
   HepLorentzVector_p1(const HepLorentzVector_p1 & );
   virtual ~HepLorentzVector_p1();

};
#endif
