//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef MuonFeatureContainer_tlp2_h
#define MuonFeatureContainer_tlp2_h
class MuonFeatureContainer_tlp2;

#include "Riostream.h"
#include <vector>
#include "MuonFeatureContainer_p2.h"
#include "MuonFeature_p2.h"

class MuonFeatureContainer_tlp2 {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<MuonFeatureContainer_p2> m_muonFeatureContainerVec;    //(MuonFeatureContainer_p2)
   vector<MuonFeature_p2>          m_muonFeatureVec;             //(MuonFeature_p2)

   MuonFeatureContainer_tlp2();
   MuonFeatureContainer_tlp2(const MuonFeatureContainer_tlp2 & );
   virtual ~MuonFeatureContainer_tlp2();

};
#endif
