//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigEFBjet_p2_h
#define TrigEFBjet_p2_h
class TrigEFBjet_p2;

#include "TPObjRef.h"

class TrigEFBjet_p2 {

public:
// Nested classes declaration.

public:
// Data Members.
   bool        m_valid;     //
   int         m_roiID;     //
   float       m_prmVtx;    //
   float       m_xcomb;     //
   float       m_xIP1d;     //
   float       m_xIP2d;     //
   float       m_xIP3d;     //
   float       m_xChi2;     //
   float       m_xSv;       //
   float       m_xmvtx;     //
   float       m_xevtx;     //
   float       m_xnvtx;     //
   TPObjRef    m_p4PtEtaPhiM;    //

   TrigEFBjet_p2();
   TrigEFBjet_p2(const TrigEFBjet_p2 & );
   virtual ~TrigEFBjet_p2();

};
#endif
