//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigVertex_p1_h
#define TrigVertex_p1_h
class TrigVertex_p1;

#include "Riostream.h"
#include <vector>
#include "TPObjRef.h"

class TrigVertex_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   float       m_x;         //
   float       m_y;         //
   float       m_z;         //
   float       m_mass;      //
   float       m_massVar;    //
   double      m_cov[6];     //
   float       m_energyFraction;    //
   int         m_nTwoTracksSecVtx;    //
   float       m_chiSquared;          //
   int         m_nDOF;                //
   vector<TPObjRef> m_tracks;              //
   int              m_algId;               //

   TrigVertex_p1();
   TrigVertex_p1(const TrigVertex_p1 & );
   virtual ~TrigVertex_p1();

};
#endif
