//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigPhotonContainer_p2_h
#define TrigPhotonContainer_p2_h
class TrigPhotonContainer_p2;

#include "Riostream.h"
#include <vector>
#include "TPObjRef.h"

class TrigPhotonContainer_p2 : public vector<TPObjRef> {

public:
// Nested classes declaration.

public:
// Data Members.

   TrigPhotonContainer_p2();
   TrigPhotonContainer_p2(const TrigPhotonContainer_p2 & );
   virtual ~TrigPhotonContainer_p2();

};
#endif
