//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigTauClusterDetailsContainer_p1_h
#define TrigTauClusterDetailsContainer_p1_h
class TrigTauClusterDetailsContainer_p1;

#include "Riostream.h"
#include <vector>
#include "TPObjRef.h"

class TrigTauClusterDetailsContainer_p1 : public vector<TPObjRef> {

public:
// Nested classes declaration.

public:
// Data Members.

   TrigTauClusterDetailsContainer_p1();
   TrigTauClusterDetailsContainer_p1(const TrigTauClusterDetailsContainer_p1 & );
   virtual ~TrigTauClusterDetailsContainer_p1();

};
#endif
