//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigTauClusterContainer_tlp1_h
#define TrigTauClusterContainer_tlp1_h
class TrigTauClusterContainer_tlp1;

#include "Riostream.h"
#include <vector>
#include "TrigTauClusterContainer_p1.h"
#include "TrigTauCluster_p1.h"
#include "TrigCaloCluster_p1.h"
#include "TrigTauCluster_p2.h"

class TrigTauClusterContainer_tlp1 {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<TrigTauClusterContainer_p1> m_TrigTauClusterContainers;    //(TrigTauClusterContainer_p1)
   vector<TrigTauCluster_p1>          m_TauCluster;                  //(TrigTauCluster_p1)
   vector<TrigCaloCluster_p1>         m_CaloCluster;                 //(TrigCaloCluster_p1)
   vector<TrigTauCluster_p2>          m_TauCluster_p2;               //(TrigTauCluster_p2)

   TrigTauClusterContainer_tlp1();
   TrigTauClusterContainer_tlp1(const TrigTauClusterContainer_tlp1 & );
   virtual ~TrigTauClusterContainer_tlp1();

};
#endif
