//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigRoiDescriptor_p1_h
#define TrigRoiDescriptor_p1_h
class TrigRoiDescriptor_p1;

#include "Riostream.h"
#include <vector>

class TrigRoiDescriptor_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   float       m_phi0;      //
   float       m_eta0;      //
   float       m_zed0;      //
   float       m_phiHalfWidth;    //
   float       m_etaHalfWidth;    //
   float       m_zedHalfWidth;    //
   float       m_etaPlus;         //
   float       m_etaMinus;        //
   unsigned int m_l1Id;            //
   unsigned int m_roiId;           //
   unsigned int m_roiWord;         //
   vector<unsigned int> m_serialized;      //

   TrigRoiDescriptor_p1();
   TrigRoiDescriptor_p1(const TrigRoiDescriptor_p1 & );
   virtual ~TrigRoiDescriptor_p1();

};
#endif
