//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigInDetTrackCollection_p1_h
#define TrigInDetTrackCollection_p1_h
class TrigInDetTrackCollection_p1;

#include "Riostream.h"
#include <vector>
#include "TPObjRef.h"

class TrigInDetTrackCollection_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   int         m_RoI_ID;    //
   vector<TPObjRef> m_trigInDetTrackVector;    //

   TrigInDetTrackCollection_p1();
   TrigInDetTrackCollection_p1(const TrigInDetTrackCollection_p1 & );
   virtual ~TrigInDetTrackCollection_p1();

};
#endif
