//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef TrigInDetTrackTruth_p1_h
#define TrigInDetTrackTruth_p1_h
class TrigInDetTrackTruth_p1;

#include "Riostream.h"
#include <vector>
#include "TPObjRef.h"
#include <utility>

class TrigInDetTrackTruth_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   int         best_match_hits;    //
   int         best_Si_match_hits;    //
   int         best_TRT_match_hits;    //
   vector<TPObjRef> m_true_part_vec;        //
   vector<TPObjRef> m_nr_common_hits;       //
   vector<pair<unsigned int,unsigned int> > m_family_tree;          //

   TrigInDetTrackTruth_p1();
   TrigInDetTrackTruth_p1(const TrigInDetTrackTruth_p1 & );
   virtual ~TrigInDetTrackTruth_p1();

};
#ifdef __MAKECINT__
#pragma link C++ class pair<unsigned int,unsigned int>+;
#endif
#endif
