//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef Trk__TrackParticleBase_p1_h
#define Trk__TrackParticleBase_p1_h
namespace Trk {
class TrackParticleBase_p1;
} // end of namespace.

#include "ElementLink_p2_unsigned_int_.h"
#include "ElementLinkContNames_p2.h"
#include "Riostream.h"
#include <vector>
#include "TPObjRef.h"

namespace Trk {
class TrackParticleBase_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   ElementLink_p2<unsigned int> m_originalTrack;    //
   ElementLinkContNames_p2      m_originalTrackNames;    //
   ElementLink_p2<unsigned int> m_elVxCandidate;         //
   ElementLinkContNames_p2      m_elVxCandidateNames;    //
   vector<TPObjRef>             m_trackParameters;       //
   unsigned int                 m_trackParticleOrigin;    //
   TPObjRef                     m_trackSummary;           //
   TPObjRef                     m_fitQuality;             //
   unsigned int                 m_fitter;                 //
   unsigned int                 m_particleHypo;           //
   unsigned long                m_properties;             //
   unsigned long                m_patternRecognition;     //

   TrackParticleBase_p1();
   TrackParticleBase_p1(const TrackParticleBase_p1 & );
   virtual ~TrackParticleBase_p1();

};
} // namespace
#endif
