//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Jun 14 15:33:00 2011 by ROOT version 5.31/01)
//      from the StreamerInfo in file http://root.cern.ch/files/atlasFlushed.root
//////////////////////////////////////////////////////////


#ifndef Trk__V0Hypothesis_p1_h
#define Trk__V0Hypothesis_p1_h
namespace Trk {
class V0Hypothesis_p1;
} // end of namespace.

#include "TPObjRef.h"

namespace Trk {
class V0Hypothesis_p1 {

public:
// Nested classes declaration.

public:
// Data Members.
   TPObjRef    m_extendedVxCandidate;    //
   int         m_positiveTrackID;        //
   int         m_negativeTrackID;        //
   int         m_constraintID;           //

   V0Hypothesis_p1();
   V0Hypothesis_p1(const V0Hypothesis_p1 & );
   virtual ~V0Hypothesis_p1();

};
} // namespace
#endif
