/* @(#)root/rootx:$Name$:$Id$ */

/*************************************************************************
 * Copyright (C) 1995-2000, Rene Brun and Fons Rademakers.               *
 * All rights reserved.                                                  *
 *                                                                       *
 * For the licensing terms see $ROOTSYS/LICENSE.                         *
 * For the list of contributors see $ROOTSYS/README/CREDITS.             *
 *************************************************************************/
/* XPM */
static char *rootlogo[] = {
/* width height num_colors chars_per_pixel */
"   360   240       31            1",
/* colors */
". c #020204",
"# c #3a1a14",
"a c #5a1204",
"b c #fe7204",
"c c #b61204",
"d c #b65a44",
"e c #fe4a04",
"f c #e22604",
"g c #de2a04",
"h c #966254",
"i c #feae6c",
"j c #6a4a44",
"k c #be2a14",
"l c #be6254",
"m c #8e0304",
"n c #c61a04",
"o c #fe9624",
"p c #fe5a04",
"q c #f67650",
"r c #96321c",
"s c #f64a1c",
"t c #e65a3c",
"u c #c62204",
"v c #be4a34",
"w c #622a24",
"x c #964a3c",
"y c #fe6a24",
"z c #fec68c",
"A c #fe964c",
"B c #fe7a24",
"C c #f53a04",
/* pixels */
"AiAiAiiiiizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzizzzzzziiiiiiz"
"ziziiAiAiAizziiiooyyBBBBByyBBBBByyyyyyyyyyBBBoByByyyyyyyyByyyyyyyyyyyyyyyyyyyy"
"yBAABqoAAioyyyyBAAoBBAAByBooByyyBByyyyBBBoyyyBByBoBoAAoBoooByyyyyBBByyyyBooBoo"
"ooyyyyyyyyyyyBooBBBByyyyyyyyyBByyyyyyByyyyyyBBByyyyyyyyBBBoooyyyyyyBBByyoAioBy"
"yBByyyyyyyyyyyBBBoooAoyyyyyyyyyyyyAAoyyyyyyyyyym",
"AAiAAAiiiiiiiiizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzizizzzziziiiii"
"ziziAiAAiAzzziiAAoyyBBoBByyBoByByyyyyyyyByBBBoBByyyyyyyyyByyyyyyyyyyyyByyyyyyy"
"yBqABAoAAiByyyyBAAABBAABBBooBByBBByyyyBBoBByBBBBBBBoAoooBoBByyyyyBBByyyyBoBoBo"
"ooyBByByyyyyBBBooBByyyyByyyyyBByyyyyyByyyyByByBByyyyyyyBBBAooyyyyyyBBBBbqAAoBy"
"yoyyyyyyyyyyyBBBooBAAoyyyysyysysyBAAoyyyyyyyyymm",
"ooAiAAAiiizzzzzizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzziizzzzziziiziziziiiiiii"
"iiiiiAAAAqiiiiiAABByyybyyybyyyBBBbyyybyByBBBBBbyyybyyybyyybyyybyyybyyyBbyyybyy"
"yoooBBooAAyyBoBBAABooAAbyoqAAbyyBbyyybBByoBbyyyBoooooboBoBBBbyyybyyybyyBBooboA"
"oooBbyyybyyybBBBoBoBbyyybyyybByybyyybyyybyyybyyybyyybyyybBooybysbyyBByyBAAAoby"
"yybyyybyyybyyooBBooAoybsyeyesyeyyooAobsybyByBmmm",
"AAoAAAiiizizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzizzziziiizziiiAAiA"
"iiiAAAAAAAiiiiAAoBBbyyyyyyybyyboBByyyyyBbBBbByyyyyyyyyyyyyyyyyyyyByybByyyyyyyb"
"yqBBBBbqoABbBoAoABBbAABBBBBBBByyyyyyyyByBBByybBBoBbooooooByyByyyByyyBBBByyyBBb"
"BBoBBByyyyyyyyBoooBByyyyyyyyyByyysyyyyyyyyyyyyyyyyyyyyyyyooyyyyyyybBByBAiAoByB"
"ByyyyyyyyyByboooBAoAoyyysysyyyybyoAAoyyyyybycmmm",
"ooABooooooAAAAAiiAAAAiiiiizzzzzzizzziiiAAiAiAAAAABqBBqBqBqBqBqBqByByytyBqspspy"
"yyeseeeCesyByyeCfgCguuggungggfeeCgggggCCCCCCCCguguuunnuunnnnnnugggunnggggggCfu"
"uCpggggnebfungpbnugeeCfggguggggnnnugggggggCgnuCeCCCeppeeeCggCggCCggggCegfgCCCC"
"CepeCgggngggggepeCeeeCCCCCCgggCCgggngggggggggggCCCgggCCCCeCfgggggngggCCpbbbfCp"
"eggCgggngggffepCeybbpfnnnnnnnnnnfebbbennunugmmmm",
"AoooooooAAAAAAiAiiiiiiiiizizzzzzziiiiiiiAAiqiqAAAAABqAABAAqABqABqyqByyyyByppys"
"yepeeeeffeyyypeCCgfggguggugggpegggegggCeCgCfgegguguggnguunugunuuuunnnnuugCueeg"
"uuggngpugbuuuufbpgufffgfeguuguuunuggguuuggfuguugnufCeeepeegeCCgCgCgggCCggggCCe"
"CCeegggugggfCfeeCgCpeCCCCCCCCgCCCggfgggggggggCCCCCgCCCCfCeCgfCCfgngCCepebpfgeb"
"egggggugnngufCCfepbefunuuunnnnnnfebbbgunugggmmmm",
"oAAAoooBAAAiAiiiiiiiiizzizizzzziiziiiiziiiAiAAAyAAqAqAAAqBAAqABqBqbyysstyyspsp"
"sspppfefnCyByppfCgggfguggnugggefgggeegegCegCgggufugugununcnuuuuuuucnnnuggfggCg"
"fguuguufuugunugufggugugpgfffgggggggfugguugCguufggffCCCeeCgCeegCCgufgggCgCgCfCC"
"eCCeCCfggggngfCCCCCeeCCgggfCCCfCCCggggfgggfggCCCggCCCCffCCfggggggggCepeeeefCbb"
"egggfggnfnguffCCebeCunnngffnnnnfepbbbeunuunummmm",
"AoAooooAAAAAAiizzzizzzzziiiiiziiiAiAAAiziqiiiAiAAAAAAAAqAAAAAqAqBqyyyyyyyseyep"
"pppbfCCggCyyypeCgggnguuggguugegggggCeeefCfCefggguuuguuuuuunuuuuununnuuuguuuugg"
"unuuuuuuuuuuuungggugufgepgpggugCggggufungCeguuuunggfffCefgeeeeCfgggCeeeeCfCCCC"
"CCCCgeCfggugggfCfggCCCefgggCCCgggggggCCgggCgCCCCCCCCCfnfeCCggggCgggfeeCfeeCebb"
"CgggugunggggCCfCpbpgncnnngfnnfCepbpobCuugfknmmmm",
"oABAoooooBAAABiizzzzzzzziiiAiAAiAiAiAiiiiiiqqAiqAAABAqqBqBAqAABAyqbtyyssysyepp"
"ppeCffggfCyyybenggugngugggfugugfgffegfgfgCCefeggfgguunuuuuuuuuuuuuuuguguuugfug"
"uucucccccnuuuguungfuuuneepgfepefgggnguuugeCuuuuugegguffggfCeCCCCgufCeeCCCCCCCC"
"ffCgCeeCggggugCCgCggCCCgggfggCffggfCCCCfCCCCCCCCCCCCCfnfeeffnfCgfgCepegfebpbbp"
"fugnnunuugebeCfCpbeeufnggCCffCebbepobenggnnnmcmm",
"oooAoboooAoAAAAiizzzzzzziAiiAiAiAiAAiiiiziiBiqAAAqAqAqAqAqBABqqqyytyyyeCeyysee"
"eseCCggCgCepppgggfuuugfggfgunuuguggegegCgCCeefpgufggguggfuuuunuuuuunuunnuunnfu"
"unccncccuuuunuuuuguncuuugepgfbggfCgggfgfCCCCngppggeunuCefgCCCeCCfggCCCCCCCCCCf"
"CgffgggCffgCggfCCfggffggnggffgggffgCCfCCCCCCCCCCCCCCCggeeCggfgCggnCppCngebbbbC"
"unnunnngugpbpCCCpbeCCCeeeCCCCepyefebopguguucmmmm",
"AoAoooooAoAAAAAAAiiziziiiiiAiAAAiAiBiyiiiiiiiiiiAAAAAAAAABAqqBBqyyyyyyeeeeyeeg"
"CsuggffCCCpbppeuuuggfungggggunufuegegfgfffCCeCfggfffgfuggunuuuuuuuuununnngnuug"
"unccnnnncnnnccnunguununugugeppegfggggggfngCpggppfngunngppfgfCCCgfgngfCCffCCCCf"
"gCgfgCfggggffufCCCfggfggugggfgCgguffgfgCCCCCCCCCCCCCffCeeCgngffgnuCbpgggpBbepC"
"nnnnnfuungpbpCCeppeeeeeeeCfCfCppCnCBbbeguuunmmmm",
"ooAoobbooAAoAAAAAiAiAAiAAAAAAABAAAAAqiBqiiiiiiiAiiiiiABAqBqBqByyyyseyyeCCsCCCC"
"effgggggfCeppeufuuuuugggggfuunuuggeCggeegCgggfgpggggggfguuuuuuuuuuuccuccnnnncn"
"nnnuuuucnnnncnnnnuuggunnunggeeCggfggguggufCefgeeguuuccfppCfCfCCCuggggffffCCffg"
"ggCCffggCffggugfCfggggfgfggCCCggufggggffCCCCCCCfffCCgCCeegfgfggggfCeeCggebpCeC"
"nnunfgfuggeeeCCCbpepeCCeCfungebegnCpBbpCununmmcm",
"AoBooooooBoAAABAAAAAAAAiABiAAAAAAAAiAqAAAAiiiiiiiiiiiqAqBAqqBqbysssyyseCCfCCCC"
"egffggfggCppeggunuggggugfuunuuufgefggepgeggegggggggugupffuggfffuuucunucnnnncnn"
"nuuggucnccnnncncnnfugguuggungCCuuuugnuuuunugggguuuucnuuCeggfffCgfgfgggCfgCCCff"
"gggCgggCCCCgfggfgCCCggggfggCCCCfggCCCgfCCfCCCCCCfCCCgfCeCgfgggCggCfCCCggebpCef"
"nnnnggfgCeeeeCCeepeeCunnnunufebCgugebbbennggmcmm",
"oAoAobooAoAAAAAABAAAABAAAAAAAAyAAAAqAAAAqAtAiiBiiiiiiiAqqqqABqysespsesCCeeCCCf"
"CCCgggugfCpeegggggfggggngguuunggCCgfggpbgffggpfpggunugpugunpppenuuncunccnnnncn"
"nufgCuccunuuuncnnnngunnugffnnunfgunuguuuuuugfgfuuuunguuuugnuggfCgggfgCCCffCeCg"
"ffgCgfCfCCgggCCCgfCCCggggffCeCeCggfCfCCCCCCCCCCCCCffCgfCCgggggfggfCCCCCCebppef"
"unggCCCCebpeeCCgeCffunnnnuunCpbeguneBbpegnugcmcm",
"ooooBoBooAAoAoAAAAAAAAAAAAAAAAAAABAAAqAqAAAAqAAAqAqqiiiAABAqyyysespBpeeCeeCCee"
"gCCCfggugeppfgngfgefgugguggunugffggefgCeggugfgfnegguuugguugebeeunnuuuncnuunncn"
"guuCgnccuuunncnunnnngnnnugnncuugeeuunuuuuuuuegpgffegegnugCggugfuggufggCCgCCCCg"
"gCfggCCCCCfgfgCCCffCCCfCCeCCCCCCCCfgfngCCCCCCCCCCCCCCCCCCCffggffgfCCeeCgebepbC"
"fgCCegCpbbpeeCfgfguggfnnnggugebeCfnCbobbefcfmcmm",
"ooAAooooqoBAoAAoAAoAoAAyAAABAAqAAAqAqAqqqqAAAAAtAAAAqiiiqBqByybseyyepseeeeCfeg"
"fCgfggfgCeeeepggggfgnfuuunuuugfggugngggfggnpgeggguunffuuuggpeeuncnnguunuunuccu"
"ggnnnucnununcnnuunnnnnncnnunccuneenuugfeeuugggunuCggggeCggCCfggfCgggffgfffCCgg"
"CCCfnfeCCnggufCCCggfCfgCeppfnfCeCCCCCeCCCCCCCCCCCCCCCfCCfgggCCgggCCCCCCCeeCpbe"
"gCeeeCebbbeeCCgfgnnCggnfngnnCppefgngpoobbCugmmmm",
"oAoooyBBoBAoAoAoABAoAAoqAAAAAqAqqqqBqBqAqqqqqqqAqqAqAAAiqqqysyyybyeseeCeefgCep"
"eCggfuffgepeeggpuguuuuuununufggufguggnggggpuguggfgggunueppgegucunuuguucuugunun"
"ugucnncnnnnccnnnnnnfnnccnuunccuuguuuuueeCnunuuguggCffgCeCCCefggeeugCgngggfCCff"
"CCCngCCeCgfggffCCCCCCCCCebpfgfepeeCeebbCfCCCCCCCCCCfffCffggffCggfCCCffggeeCebe"
"CeeeCepbbbeeCfggffnCCgufffffCppegfugeBbooefgmmmm",
"oBAAoBooooooABAAoBAAoqAooqABqAqBBBAqBqBqBBqAAAqqqqAqAAAiBttyyyyyysyeseepeCggeg"
"ffggguuggCpeeegggguguuununnuuggfggguuggfegppgegpppuggggepeguuggguuunuuuunuuuuu"
"uunccnunnucccunuunngunnnuuuuccnccuuunuCCCuugugpuggeCggCCCfCeeCCCCeggggggfgCegg"
"CCgffCCCCgCCCCCCCCCCfCCeepeCngCpeCCepobyffCCCCCCCCCfggfCggCgCfCCCCCCfgngepeeeC"
"CCCfCeypppCCfggCguggggggugggepppCgggebbbbbCCmmmm",
"oAoobBBoooboooooqoobAoqoBoqAoBoqBBBBqBBBqByyqqBBAAyqyAAiqyyybsysysyeesesCeefep"
"pCCggggffCppggffggggnuuunuuuugCgugefuuugegefpgfpgugggepefeguuufeuguuuuuuunuuuu"
"uunnnnunnunccuunnuunuuuuuuunccnccccuungCggugfuebggeCCfffCCCCeCCCCfugugCCffCCCf"
"CfgnffCCCgfCCCCeeCCCCCeCCeeCgCCeCfgCeobpffCCCCCCCCCgggggfggCCfCCCCCCCfggebbCCp"
"eCCfCepeeCfnnCCggggCCfgguugCpbeppCgfeBbeebpeccmm",
"oooAoBoBbBooBoBbBoBqoBBBBoBoBBBqoqABBBBqBqyBqqBqAqByqqqiABytyyysesseseeCCCCggC"
"eeggfggCCepeegggfCggguunuuuungggfgguuuuggfgppfgggeggepegguuuufggguuunCegguuuug"
"uuuuggunuuucnuunuuuuugCgguuucuunccccuggfguufugCCeeeCngCCgfCeeCCCCufggCCgggCCCC"
"fggfnfCCCCgCCCCepCfCCCCCCeeeCCCffggfeebpCCCCfCCCCCCCCgggCCCCgCCCCCCCCgngCppeeb"
"bCfCepeeCfnggCCnggfCCCgfuggCepeeeefngybCgCepgccc",
"oAooooboBoBBBBBBBBBoBoBBBBBBBBBBBBByqBBByyyqBBAqBqyyByqqiqbyyybyssssCfCfCCefCg"
"eeCgCfeeeeppfpggggfugunuuuuuunuunugugunugfgggggugfegegggnunuuuuuuuuggepeuuguun"
"uuugCCnnugnccnnuuuunuCCfununguuncnuuggCCfuuugnCepeguuCCCCCeCeeCeCgfgCCCgfffCCg"
"CCgggffCeCCCCCCppeffCCCfCepeCCCCfCeCCCeepeCnfCCCCCCCCCfCCCCCCCCCCCCCffufCeepeb"
"pCCCeeefgfngCCggngfCCfgcgffCeeeCCCggCpbgunCegffg",
"ooooobBBBBoBBoBBBBbBBBBBByBBqBBBBBBByqyyybBBqqqqByBqyBqAAqtysysysesCCgfCfCCeCC"
"fffgfCgCfepbpCuugnugfguuunguuuuuguggnugugguguuufegegfefugguuuncunggenCefgunnnu"
"unuggguuuununcnunfugggCCuuuuCguunuungCCfunuguuCeeeguugeppeCeeeeCeeeeeCeCCCCCCC"
"CCgfCggfeeeCCCeeeCCCffffCpbeCffCgfCCCCeebbegfCCfCCCCCCCfCCCCCCCCCCCCgnfCCCCeee"
"eCCeeeCgngnfCCCufngffgggnggggeCgfgfgebbeunugcngf",
"ooAoyobbobBBBBoBBBBBBBBBBBBBbBBbByyByyyyBBBBByyyBqyyyyBAABqBBstssssssCCfffCeCC"
"CggggCCgCeppefgnkugugpguuuunnngungggggggggnpggggeffgeupgggnuuuuuuggeguuuugnunu"
"uunnCCggfnuuncnnnuuuununuuufgucuuuuufCCuuuffungCCCpgCCeepCfCeeeeeCCCCCCCCCeCfC"
"eeCggfffCeeCCCCCeCCCCggfCepeCgfggfCffCeepbeCCffffCCCCCCCCCCCCCCCCCCfggCCCfCCCC"
"CfCepCgfgggffCfgnfgggggfggnggCCufCCCpbbfungnmccn",
"oooobbbobBBBBBBBBBBByBBBBBByyyybybbyybyyyqyyBybyyyyyyqqqqABqqBtyssesfCfCCCCCeC"
"fCgfCffgCeppguuugnggfggnkngugggugufefggfgbgpppgpgeggfpggeeguuffgunCufuunugpfuu"
"uncuegguuunuucnccnunguuuuuuuucuugnungCguggCguuufffepeeCeCCCfCCeeCCCCCCCCCCeCCe"
"begngugCCCeeCfCCeCCCCgggCepeCCggfgffgCeesbbpCfffffCCCCCCCCCCCCCCCCCffCCCCCCCCf"
"fCCeeffgggggggggcnngfggCfggugfCgCCeCebbeunnnmmmm",
"ooooobBBBBBBBboBBBBBbbybBBBbyByyBBbyyspbybyyyyyyyyessyyyqttsBqBtsssCssgCCCeCCe"
"ffCCgggCCbbpgfgnggugggefguugugggnggggggggpbppnpppguggfgegCeuugCuuuugfguuugenun"
"uuuugfnunuuunucuuuuuguuunuunucugeuugngggfCguunuggCeeppCCffngffCeCfffCCffffCCCe"
"peffnnffCfCeCffCCCfCffgfCeeeCgfggggfffCCebobegffffCCCffCCCCCCCCfCCCCCeCCCCCCfg"
"fffCgggCCCggnnfnufgggfggCgffCCCCCCCCepbCunnnmmmm",
"BooobbbbbBbBbBbBbbBbyBybBbyyyybBbyypyyybysepyyseseseeyssysyspqABssseCsCCsCeCee"
"eCCCCCffCpbpgugugngugggggnugegegguggggugnesypbpfpgfuggfgegeeuggfuuuuguunuuuguu"
"unuunuunccuguuucnuunuguuguuuucngCgpugufpgCguuuggeCCCCeeepguffCCeCeCffCfgfCCCCC"
"efgunfgCCCCeeCffffCfCggCCeeCffCgCCggggfCeooobCgggfCeffffCfCfCCCCCCCCCCCfCCCCgC"
"gguCggfCCfnfnfngggggfgggfCggCCCCCfggpbbennnnmmmm",
"oAoobbbobbBbBbBBbbBBbbyBbybybbybyypyppyypyppeeseeeespsyysysstqiBtysssCeeeeesCg"
"CCCCfeefeyybgguuuuuggggugggggfgepfggggguggysgpypeggpppeggggegnuuuuuuCuuccucuuu"
"uucccncnnuuggncuuuuguuuunuuunuuuggueepggfnguugCfCCCffCCebeCeCCCCCCeCfgfgffCffC"
"CgggggfCffCCpeeCCCCCCCCeCCfuggffgCCgggnfeBooopgffgCCCnffCeeCCCCCCCCCCCCCCeCCCg"
"CgggCgffgfgngnffgfggggfgCgfCeCCfgggebbbennncmmmm",
"oooobbbbbbBBBbbbbbybBBBBbbpybyyyypbpbBybypyeeseppypppssesyyytqqByysessssssseCe"
"CCCCeCgggpypunuuuggnfguuupbpepppggppgnppgbspppppfgpbbpepeefgguugnununuucncunuu"
"uunuuunucnuguuucuuCggnnuuuuuuuuuuupgpgfpggbbgCCfCCCffffCeegCCCffffCCgnCCCCCCgf"
"fggugffCCCCeppeeeCCCeeCCCCguggggffgggnfCCyyqABCnnffCeCeeebbyeCCCCCCCCfCCCeeCCC"
"CCgffgggCgffncgggggggfgCCCCebpCfnfCbpebpCgnnmmmm",
"oooobBbbbbbbBbbBbyBBbbBbBbbbyBByypppppbppypeeppepepyeseyssyyBAAqyyyysysesesess"
"CCCCCgggeeppgugunggugngupbppuegCgpfnpppugeguugpepbpbbbpeegffgugugguncccuuuuuuu"
"uuuguuunuuuuucunuuCeuuuuuunguuuuunugegeegpbpenggCCfggeeeCeeefnnunnfgnugCCffCgg"
"ngggggffffCCeeeeeCCCCeCCCCfgfggngnfgggCCeeypyoegufCepbbBobBoefffCCCCCCCCCCCCCC"
"CCggggnggggcuggfggCCCeCffCpbybgnnCebeCpppCgnmmmm",
"oooobbBbbbBbbbbbbbbbybbbbepbyyyByppppppyppsepbpeeeeeeCesessqqAqqBBtyyesyessCee"
"CCspefpgugCpgugggggeguuggpppgggfggppupgpuggggpgeeppppppeepugggggguunnccunuuunn"
"uunfgunuuunuunuuueCCgnuungggpgunuugnugggeeppgugCCCCpeeeeCCpeguuuuuugguCCfCCCgg"
"gggguggCfCCCfCCCCCCCCCCffCCCCCCgufgCeppppbbByBbeCCebobBbbppbeCfCCCCCCCCCCCCfCf"
"CCCCggngfnnggngCCCCCCCfgCebeppCnnCbpgCpbppCummmm",
"oooAbbbBbbBBbBBypbybBbyybppppbpybsppeeeeeeepppppeeCeesCesCesyBqBqqBBtyysyyesse"
"seppspeCgegCgfggggggenufpgpppppfpgggpggugngnpupgeppeppfggggpgfgfgguunnccuuugun"
"nnnnkunuuuuuuuuungCggguuuuggpppguuugunuugCCfufgfCCCpeeeefeppgunggCfgufCggfCCCg"
"CCfgCggCCCCCCffCCCCCCCfCCCCCCfffggCepBypboboBbBbpppBobpppepeeCeeeCCCCCfCCCCffC"
"CCCCfugncgggffCCCfffCCgnfepCCefnfebpggCpeCefmmmm",
"BooobbbbbbbBbbbbbpbpypppyppeeepppppbpeeeeppppypeeCCCeCCeCsessyABqqBqBqBqByyyss"
"seyssgegfCggngnugnufuugggpppnppppbppgfpfggggbueppppepppgpggufgggggunkuuunugCuu"
"cnncccnnnunuunuuufegenuunuueeepfugugugugugCgepffCfCeeCefgCCepuggCeegfeCCCCCCCC"
"eCgCCCgfCCCCCCCfCCffCCffCCffCCeppppeyybepboobpybbpebbpeCCepeCCpeCffCCCCCCCCCCC"
"CCCCggfnnngnggfCCgcgfgnngCCffeffCbbeugCpCfCCcccm",
"oooobbbbbbbbbpbpbpppppsyyybpeeepeepspeCeeeppppeeCCgCCCCCCeessyyyqbqqBqBqBqtyse"
"sesefespefugggggguguunggbsyspypppppuufpnugguupppepppybpeffngbpefguugunuuuugfuu"
"nnnunuunccnuuuuuunuCuuuuuuunuCCgugfpguffnggeCuununugfCCgefCCeefCCeeCCeeCfCCCCe"
"eCfCCCfCfCCCCCCCfCfffggCCCCCebbbbbpeeeCCgeBobppyyeeeeCgfgCeeCCeeCfffCCCCCCCCCC"
"CCCCfgfuffnngCCCCgnggnuffCgnfCggebbCunfeefngcccc",
"oooobbBbbbbbbbbbbbeeeepeppspgpeCeepppeeCeCCpppsCfgCgCeeeeCCeeeyssqsyyqqBAqBBss"
"sssCseespgggpugnuguguggepybykptfssypuggpgpgpfgpppppppspeeggueeggngunuucunfuunc"
"cnugunucunuuuunuuuuuguccunuuuggeggeeguggggCguguuguungugfCgneepgeCCeeeCCCCCfCCC"
"CCgfffCfCCCCCCCCfffCCffCCCeepbbppeCCgggnfCbBypybbbeCggfufgCffeCffCCCCeCCCCCCCC"
"CCCCgCCCggnffCCCfgggggngCfnngCgCbppCufgCeCucmccc",
"oooobbbbBbbBbbBbppppgpggebppbppgepeeeeeCgCgCeeeeCfgeeeeeCCeeeesseyyyysssqBqqts"
"essssessypyysgggnunuggfgssstssspggsspgguepppbpCsspyspeeeegppfCCguugguuuuununun"
"kuCguunuuuuuuuuuuuuucccuugguuufppgfCfuugfeguuuuuugggngufgugCeeppeeeeeCCCfCfCCC"
"ffgCgffCCffCCeeeeCCCCCeCCeepbbpeggggfCggngeyyyBbbbeCegugunngCegnuepCfCCCCCCCCe"
"eCCfgCCCggggCeCfCCnnuggCgffnnCCepppegnngeCnnmmmm",
"oooobbbbbbbbbpypbppppppppeppeeppgeeppeeepeCCCCCCCeeeeeeCCCCCeseesssssssssyAqBt"
"sssssssssybsssguguuggggefkkgsypkpgspvkpypeyysfseyyypepegugbpgngguuugunuuuuuunu"
"nfCguuununucnuuuggncccunungncngeeggfuuuggfffungugggguuguuufCCeeppeeeCCCfCCfCCC"
"CgCCCCfCfffeeeCepeCCCCCCCCeebpCgungngfguggepBobpppeeeggguffgeeggCebCfffCeefffe"
"eCfgfffffggCeCCgCCgfgCCefgnfCCCeeepegnnfCegnmmmm",
"oooobbbbpbbbeppsypbpbgpgpeepeeeepgeCeegepegCeeefeeeCCCeCCffCCeespsesssbsqqBqqq"
"tesystesssysfsppuuugfgfusgfesgsgsnptpyyppsstesgpsbyppeggppppggpfuunuuuuuuuuggu"
"unuuuuuuunnnunnunuuccnuuugguuuCfuuggnuuuugguguuggegggfuuugfCCfCCeeeeCCCCffCCCf"
"CCCCeCfgffCeeeeeeeffCCCCCCCCeeCfguuggCggCepBBbpeepppeCnugufCeCgCepefnnCCeCfnfC"
"ppeggguggngCeCCCCCCCCCCCCfgfCCCCCgeeCfungepgmmmm",
"AooobBbbBpbppeeepegpegpggCgegeegpegeeeeeCCCCCeeeeCCCCeeeCCggfCepseseessessqBqB"
"BqBBqBBtysssskyysggguuguppkgukgugpkssusyspesufbyyyyybpppegupbpgguuugguuuguuuun"
"cnuefuncnuuuuuuuuncccugguuuguununuuuugfuuuufuugnfggefgugggCeCgunfCCfCCffCgfeeC"
"CCfCCCuggfCeeCCCffnnffCCCCCCgCCgggnggCCCCpbbppbbbbpeCgnugCgCCCCCpegnffeeCnnnnC"
"CbpCggggggfCCCCCfCCCCCCCCgnfCCCCngfCCggnuebgmmmm",
"AAoobbbbbbppppggpgppppppCggggeeeegegeeegCfCCCeepeCCCCCeCCgCCgCesespssssstssstq"
"BqqqqqqsttsssssssksssgffkspugffpuupuggspspyspgsyyyyypgCpCeuueCgnuuuugfuuuucncc"
"ccnCuncccnnunuunnccccngguunguuunuugguCeguguunguuunugCCnugCeeeggufCCCCCfCffCpCf"
"fCCfggnuuCeeCCfggnfngfffCCeCgCCCfguufCCCeeppppbbbbeCCgnggeCfCCCpeCgngebegnnnfg"
"CpbeCggCCeeeeeeCCCCCCCCCCfnfCCegngCugCguugeCmmmm",
"AAAobbbppppbpppbgepgpgepgCggepfegfegeCeffCeCCCCCCCCeCCCCCCfCgfgCsesepessssssss"
"sqqiqqBBtbesesesssksfsgsessknubuggpfugpsspsggbsssbsbeeeCCupgepgugguuupnununcnc"
"ccuguunnnccnuuunncnccuuuuuuguuuuunfungCfgngguuugggggCCepeCCpCfggeCCeCfgCCgCeCg"
"fCCgfnggfCeeeCngnfuggguffCeCgffggnffCffCeeeppeebbeggngggCeCfCfepCfugCpbCfnnnnf"
"geppCCepbpppeeeCCCCfCCCffugCCCCggCCgugCunuCCmmmm",
"oAAoypybeeeppggpppppeppgpegCgCgfggggCggggfCCeeCffCCCffCCCgCCgfCgCCsCssCsssssst"
"stqqiqqqtssssssssesssskfsgggppkgnguugppppsupppsessspngfguCguCegegpnuuuuuuucunu"
"cuunuuuuucccnnuucnnnccnuuuuuuuuuuguuungggggugggfgeeeeeppCfCfguunCppeCCegfCCffg"
"CeeCnnggfeeeeggggggffuuffCCeeCCCggggCCfgCepbpeeepenggCCCeCfCeeepgugCebefugffgg"
"fCCCCepbbbeeCeeCCCCCCCCggngCeCCggCCnnnngufCemmmm",
"booAyybyegggegggbgggggCeggCfgCfgggfgCCggggfffCCCfffgfffffCfCCggCCCCeCCCgsessys"
"sstqiqqBqBssssssssssssepspsskefguugfugesggpgpssusspsuugunguuffeefgguuuuuccncun"
"unugucuunccccccufukcccuungunuuunguncuunngununuggepppbppbpCfguuuCCepeCeCCgfCfug"
"eeeeguggCCCCCgCggguggunggCeeeCfCgugCCCggCpbpeCeppCgufCCeeegCbbpCungCeeCunggCCg"
"gfCfCeyobbeCCCCCCCCeCCffggfCeCffCCCunnuggnCpcmmm",
"bByBppyybguguguegpgCCgffCfgCCCCgggffeggfgCggCfgCCgfgggggfgCfgCgCCCCCeseCssssss"
"ssyqiqqqqqBstfsesgsssssksskusspupupfgugggpppssfspssunnggunuuuuCgCCngununkcccug"
"uuuuuuuunncccccugfncnuuuuuuufuuuununuuuugguuunugepppbbeppCugngCCCCCCCCCfgfggff"
"feeeefffgCCCCCCCfugguggfffeeCCgnngCeeCCepbpeggCppCggfCCCeCfebbefuufepegnnfCCfg"
"CepeCebpbbCCCCCCCCeeCfgeeeCCCCgfCCefccuuguCpcmmm",
"bbbBppesggguggfgggggnCggfugffggffgggfffgCgCgffCCfCggCfggggfCeCCCCCgCspsssseess"
"sstqiqqqqBsBsssssssesessspusupnpufuufguggfpppgsbtppuucnguuugggfufuguguuuccccnu"
"cccuuuuugnccccunguuccuuucuufgguuguucuguggguguuuCeepeeppeeggggeeeefnnfffgfuuugu"
"ufCepgggfCCfCCCggnggfgugugCCgnnnfCepeCepBbeggCCepeCggfffCfgCppeunfgCeCcnngCCCg"
"gCpCfepeppCCCCCCCCCCCggCpeCCCCCCCCCgunuuunCegcmm",
"bbbbCCggguggfnungfgggggggggCCfCgCggggCefCfCggCCgfgCfgffgnggeCCCfggfCesesCCgsss"
"sssqqiqlqqqtstssessssskgCkgkgpsggguungpuppsssgeseseunuugenugnguuuuugegnunncnuc"
"cccnuuuuunncccnnuuncunuccnugfuuguguuuggngggngufgeeeeCeffunggeeCeefnnggggunnugg"
"gggeeggfCCeCfCfgugnguggnfnuungCeeeeeeepbbpguuuCCCeCugggnungCeeguunnCCCnncfCCCC"
"CeeeCeeCCCfCCCCCCCCCffCCeeCfCCCCCCefuunnugCCnccc",
"BBbpCgggugufngguugggngggffegfgggfCgCgggCfgfggffCggfgugguggfCCffgfggCeeCCegggss"
"ssstqiqqqqBttstsyssssbsssfsgksupuuugpugfpkggeeggeeeggeCegggugununuufpugnkuuuun"
"nunucnuuucnnnuccuuucccuncuugguunuuuuugguuuuuuuuueeggnuugggggCfeeeCgnfggguguggg"
"gCCCeCfufCCfffguguguufunnuufgepppeCeebbbbeggggggggfgfgCCuufCeCgfnnfCgnunuuCCCC"
"CeCCebefnfffCCCCCCCCggCCfCCCfCeeCCegguuunnCCccnn",
"bbpengnnunngnngggngggfgggggggggCCCfCgCgCggfgggfgfnnngnggggffggggfCCfeeegCesCey"
"ssssqiqqqqqtttetsyesyyyessusgussffuugppusppggfegggpgneegggnuuuununkggegegnucuu"
"upguuuguuuuunncccuncccunuununuuunuununuunuuunununuuugggCCfffgffCCggggegfnuugCe"
"CCCeeegffCCCgunnnggfgggugCeppbppeffCpbpebeCgnununnnnffCCggCepegnnnfegnugfnffCC"
"CCCCepeggCCffCCCCCCCffCCCCCCCCeCCeCgfCununffmmnn",
"epeefnggugngufgfnnggfgfgggfggffgffCfffgguggfgggggfnfnfngggggfgggCCCCgCCCespssy"
"sssqqiqqqqBBttBstBstsysssskkgkngupuggeupegseeeegCeegpeeguuuguggguuunuupguuunug"
"ggunknuuuuccnnccccccccuuunuuuuuuuuugguuuuuuucccuuuuungCeeegCggCffgggCCggugffCf"
"CCeCCCfggfCguunnfugCggggCpbbpbCgnuCCbbCCCefggugnununggggCCebbpCnnnfCgggunnnffC"
"CCCCCeeCffCffCCCCCCegfCCCCCCCeCCeeCngggunfffmmcm",
"eeeenfgnggngggunnnnggggCfggnggggCCgggfgfggngfnfnucgnfffgCggggCfgfCfgCCgggeppes"
"systqilqiqqqBqBBtsBtttysssgsgsgspngpfegpkeeegCgeggegepuufgununCguuuggeffuuunnn"
"uggnunnguuununccccccccuucccccuuunugguuuuucucuccnnuuugCCCCCCfCCgggggfnfCuggCCCf"
"ffCCCCCCgCfgnuuunggCfCgCCbbpeCfuggfpbpgugCCgnunuguugggugCCebbbenngfgCCggnnnuff"
"CffCCCCggfgCfffCCCCCCCCCCCCCeCCCepeugfgnugCCmmmm",
"eeeefngfugguufggnfuggugnggggggfggggggggufgfngcgfgnngggunffCgffgfgfgggCgggCssCs"
"ssssqqiiqiqqqqqBqBqBtttbsssssgsusupnggpppegeeeCepfeeefffCCguuggfungfuguuuunnnu"
"ununnuugucccccmcccccccncccccccccuugfuunucncunccnnnggffffgCCgfCCCCgnuggCCgCCCfn"
"ngfCfuCCCCguuunugugfggefCepCunuuunCppCgnggfgnnufggnnnfunfCebbbeCuuCeCCCfnnuggC"
"CfffffCgfgfCCCCCCCCCCCCCCfCCCCCCpbCCggugugeCmama",
"eeeefgggfggggfgugnnggguuunuggggfgfgggfngcgfgggnnnfnnngggungggegggggffCfgggggCf"
"sysstqiqiqqqqqqqqqqqBBqttsesssgsuggpggfsseCgCCfeggCCgguCeefuuuuuunuugguuunuung"
"nnnunugunnccncccccncncccccnnncccnuguuuunucnuucncnngCCgufnugCCCCfCeguCgCgfffgCf"
"ggfCCffffgnuunnuunnnffCfgCegnuuungeppgnnnuffugCeefnunnugfCCebpeCggCeCCCfnnffee"
"CCgCgfggggfCCCCCCCCCCeCCffCCCCCepeCepCggggCfmmam",
"eeeegfgfgggfgunggggugnucngnggggggggggnnnggggngnffuggfguguguuCegfugfggfCfgggCfC"
"CssssqqilqiqiqqqqqqqqqBBtyyvssfsgsspsegeggfeefefgeegCCgCeegfgguguuunuuuunnnnuu"
"ucccugnnnccccccccucuncccccucncnuuuunuuuccccnccnnnugCCggguuggeCCggCgggefCCCggCC"
"ffggfgggggguuunnuuknnguugeeeggggngppCfnnnnugfCeeeggggfgggfCCeeCgggfgffCgffgCee"
"CgggggfggCgfCCfCCCCeCCeCCCCffCCpeeCCepggfCCCmamm",
"eeeegugggggggngufgfugunngnfggggggggggngggnfnfngnngngungugugggggufggggggCgCCCCC"
"sssssstqqqqqqqqqqAiiiiqqBttesksskegsfgfgfgeCeeggpCeeeeeCeCggggfgnuuunnnnnnccnn"
"nccuuucnnccccncccncucnnccnccncuunuuccccccuuuncnugggfCCgunufCCCCfgggffCfgCgfCgC"
"gggguuuuuuuuuugnnnuggnnufepCgfgfuCpbeugnnnugfeeeCCeCCeeCCfCCpeCffunggCCggggCCf"
"gnnfgCCCfffCCeeCCCCeCCppCeeCfCCppeCfppCCCCfecmmm",
"eesCugugungfugngguunnnnngcgCggggggngggnggfnnnnncgngggnnggfffgfgfuggggfufefCCgf"
"fsssssssqttyqtqtqqqqiqqBqBstssssCssCegeguggesepegeCppppeCCggfgeuugggunccnucnnc"
"cccnunnncccccnnccucuuuunnucccncuuucncuncnuununugggnufCguugufCefgugngggggfCgffg"
"CCfunununugugguuuggffunngebCfCfgfepbeufguugCeeeCgCpbeeeeCCCCeefguggggffggfgffg"
"ngnggCCCCCCCCCCCCfepeebeepeCCCepppCCppCCeeCeccmm",
"eeeengngunncnnnugguuufffngfggfgfCggggggnncnfnnnnfgncggfugggfnguggffCgggfgegCgg"
"fsesysssssssyssssytqqzqqqBqyteksgkfgfefggfCgCgeeefeeppeefCfggggggufgununnunncc"
"nccnunnncnncccnnununugukuuucccuugucnugnkngCguunuggggfCCufungfCCuuuugngngfggugg"
"fgggguuuuuuggfggggggfuunfCpCugggCpbpeggungCeeCCngCbbeCeeCCCCeeCggugCggfgnfggfn"
"nnfffCfgCCCCCCCCCfCeCepeebpeeeepeCfepeffeeCCncmc",
"eeeeggunncnnnnggeggufgggufgggggggnfnngnnnnfugnunuuggugnfggguunuufggfgCgggfffgg"
"gCCssysssssyyttststqiiqqBttsysssspspgeggfpffgCffCgeCeppfggggngfgguguuunnnnnnnn"
"uucnnnnnnuuunnkuuuuuuuununnccnuuuucufguucggegunnnuCegfugguuuggffuggugggguguuun"
"guuguggggffggugngggguunngCeguugCpbbegggugCeeCCgCCpbpCCeeeeCCppeCCggfgggfggCggf"
"nnnggffCCCCCCCCCCfCCCCeeCeeCeppennfCpfugeeCfccnc",
"eeeeunnunnnunugCpgfguggggcfcnggcngugfnnfnnngnnguggggfugcnunngnngugCffgggggCfCg"
"efsCssssssssssyystsqiiqqqtstsyekssegsgfgggefeggCgeegeCCgfgggggCgnguugfnncnunuu"
"nucncnnuugggkfgnknknncgguuncncnnnnuuugnuuuCgnuuuugCCCfgungnuuggngCgggggunuuggu"
"uguugugCCgggugggguguuucngCCfgfgepbpeguggfCeCCCeCeppCCeeeCeCeepCCCfnnfuggcgCCgf"
"nfgCCCCCfCCCCffCCCCCffCeefCepbeCnnfeenunCCCCcmcc",
"egeCugncnunnnuffppgunnufngngfnfnuugngfnnnuugugnunfguunugnnunngnugggggffCgggCff"
"fgCCssssssssssststtqiiqqBBsbssssCssggggggggpfggfffCCfffgeCCggCCCgknuguunnnuuuu"
"unncncnunununugununnunuCuuncunccununuuuuugggguuuufCCeCfguguunugugfCggguuuunfCg"
"ffunugnCCgfunuugnunuunnufCfgCeepeeeCngugCeeeeeeeeeeCCeeeepeppeCCCCgfggCggCfCCg"
"CfCCCCCCCCCCCCnCeeeffnfeCgfepppCnngeCucuffnCcmmm",
"eeeCnuunnunuuuuggpggcnnfugfnnfuggngggcgfngnnfnnguunfnnunuuggngunugggggCfegCggg"
"CfgCessesssssssstssqiiqqqtttyssfggfgfggupgupgpgggfegggggCeeCCCCCCggfguuunuuggg"
"unnunuuuuuugunuguunuguugfunuuunnnunnuggCnueggfuuunggCegguuuuuuggggfggggugugggg"
"ggguuuunCgggunuuuunnnnuufgCpepppeCeggfguCpbbppCCCeCeppCCCeppeCCCeCCgfCCeCCffCC"
"CCCCCCCeCeCCCfnCeeCgnnnngffeCeeCnnfpenuuggnfccmm",
"fegCuunnnuunngufpggunfgngfggggggcgnfgngugucfnugnunfuungngugugugugfggggCggfgggg"
"fgggessssCssssssyttqiqqqBtstessssgsgggffggbgffuugpfgggfCCeeefCCCfCgguuuugnugng"
"guguuuugunuuuugugugnuuuuuuuuuuucunuccugCgfgguuufuuugCCfuuuuuuggCungCggnuuuugng"
"ggunfugggununnnnuuunnunuuCebpepbCCegfgunCpbbbpCCeeeeppCffepbCfCeepbCgfCCefugfC"
"fCfCCeeeCeeeefnfCCgnnnnugggCfCCuncCpCuuuggnncmmm",
"eefpufununnnuuuepppggngugnufgfuggugnngnguugnfggguuunnununugnugungggnnfgfgfgugC"
"CgggCCCCssCsCsssyttqizqqqttssssskgfgfggngegggguuggfggggffCeeCffgngguuggguuuuug"
"uuuunugfuuugCguuuuugufnguuuuugnuugununggufgggnuuunnngCguuuunggCCuggfggguuuguug"
"gggggnunuuunnuunnnununnunCppCCeeeeCgggggepeeeeCepeCppbpgfeeCnufepbpCgfgCCggnnf"
"ffnfCebeepeeeenfCCgnnnunnnfffCCnnnCpCuufggunmmmm",
"Cgeguuguguuuunufpppgggnnugggggfuufnunfngunggggggggnununnnugggguuggggfggggufffg"
"feggggCCCssCsCssstyqqqqqqBttsegssggggugugggegfgnggugggggufCCfnnnuuufgufuugunnu"
"gunncngunuufggunuuuunguugunuugununguuguuguenggungucnugngunuuufCggggunugguuugun"
"fguguuggguunnnncnuuguuuunfCCfeeCeeguufuCepCgfCeppCfCeppeeppegfeppbeCCCCCgCfunn"
"nnnfeppeepefppgfCCgnnnnfnnuggCCnnnCbCufufunnmmmm",
"fegeuugfgguuggggpppgggggungnuugngngggngnuunggCgggugngfnnnnngfuunnugggfgugguggg"
"efgggCfeCCeCCesssssqqiiqqqsBsvssfspeggungfguggguuufnngngungCfnnunuugnggunnucnu"
"nucnnuugunuugguunuugggguuuunuuguuguuunuuuugpgpguunnuuuuuuuununugnuuuggnugnguuu"
"uuugguuguuncnunuuuuunuuugfguCeeCeCfnugfepefgffepefnCCCCebpepeCeeppCngeeCfgngun"
"unfCppeCebCfeegCCffnnfnnnngngCffnfCpguuguucnmmmm",
"egefnugggnggguufgpfguguunguuuunuguugugngnggCggfgggugnuuuunuguguuuggggggngggufg"
"fggggfCegffCsCsssstsqqqiqqBtsssfssgggggggknggggfggukuuguuggnuunuuunugguuunnnnn"
"nnungfgCgnuffgggnunuuuunngnunugguuuuuggnuugggegguucnguunguuuuknuuguggnknuugguk"
"nuunuuggucccnuufgfugggfggunCepCgCnuuufepeCunCeeefugCffCbpeeepeCepegugebpCuuuuu"
"ungepppeepgnCCCCCgggfggnugugnfgnngCefuuuuuucmmmm",
"Cggeuuugggegggunggnufufgguuugnggggugunguuuunggngugngnuunuugcugnggggggguugggggg"
"gnufgggCggfCCeCssyssttAiqqtsssssgfkCfggffufggggnggfufguuuuucuuuuffgnufguunnnnc"
"nccuugCCCgggebegguugnunuuuuuugugfununugunuugpepggnuuuuuunuuunuuggnuuuuguuugnuu"
"nuuuuunucccccnugggunggCguugppefCguuuuCeefuuCeppCuufguepepegeeeCpbCunnCppCuunnu"
"ugeeeCebeeCCCCCCCggggCCgggggnugunuCegccuunncmmmm",
"eeefunuugfgggnuuugguuuugggguuguggfggggugfuguuuuuuuguugggunuuguggggggggggngfgng"
"ggggguufgggffCeCssysyyqiiBBtsssssggsgggggggfegggggggugununuunuuuuCgfuunuunnnnn"
"cncnugfCgfuCpbbguguunnunuguuuuggguuucuuuuunggpeeguununuuuuuuuuguggununununuunu"
"uuuuuuunccnnccnggfuuugfCguCbpCuCuuuuueeCuugCCeeuuugggppeeeCCCfCppgnnCebeCgnnnn"
"uCepCfepbeCeCCCCgngCfCCgguggnggunfCCgnnnnnccmmmm",
"pgeeuuuuunpgggugguugnugngggggugggngggugugggnguggnuffunugungffugngggnguguuggggg"
"gfggffgffgggCCsCssssssqiqqqBssssksgnggggggggggugggggguuuuuncnnnugfgguunnunncnn"
"uuuunungguuuebpguguuunnnnngufununnununnuuuuuugfuueCuuuuggunuununkuuuuuucuuuguu"
"uunucuuccccccccnugnuuunuunCpegfgguuuuefuguggCfgnggngCbeggCeeefCpeCugebpfuuunnn"
"CepCufebbeeeCCCCggggngCggunnnuuggfCfuununnnummmm",
"pppeggngggufguggggggugugugnfugnguggugfgugngugufuuuggggguggggggugngggggnunguggf"
"gggfgguggegCfCCsCssssytqqqBttesssksgggggeggggggggnngunguuunnccugnnunnunnuuuncu"
"uuuuguunnnungCCfuunuuunnnnunuunncncnuuccnunuununugCguuugguuuuuuuunuuuunnuuguuu"
"uuuncuunnucncccnuuuunuuugCCCfuCgununffuuugngnuuuCgugppggffebbpeeegnCppeeuuuuff"
"CeCungeppCCCCffCgffuugnnfgffungggCCgkngnunknmmmm",
"pybbgggggggggfgffgppugugnggguuguugfuunuuugggugnkngungggfugggggggggngguuguuungg"
"gnguggggCfffCfsCsssssstqiqtstssessggggpnggngnggnkuguuuuufnnccuuuununnunuuuuuuu"
"uguugunnnuuuuuunugnnnnnnuugununccnccnccccnuuuuuguggggfgffguuuuguccuuuununuuguf"
"uuucccuuuuuccccunuuuuugggegCngCguuuuuunuuguuunufgunCpCfuugepbppepeCepeguenugCe"
"CCnnnfeppeCCCffCCugunununngCgngCeCffgggguugnmmmm",
"bbybfpgfggggnugggfppunugguggfucguggfggunuuggnnnnucngggfgggggggggngggnguunnuguf"
"gggggfggfgggfgffCssssstqiqtssssssssknnuggggnggfgfungugguguunuugguguuuuuuungnug"
"pufuununcngunuuuuunnunnuuuguuuncucccnncncunuuugefungfgnuguunufgnuuuuuunuuuungu"
"unnnccuunuuncnccuuuuuggnCeeeegenuuuuuuuuuuguuuuufuuCepppgfgepppepbeeegufggueeC"
"fuuuugCepeeCgfgeCguuuugggugfgunCeCCCgCCggngummmm",
"bbpbgfgggggugnugpgppggguggnggggnugggguuunnguuunnnnuuugggfnggggngggguuuguuuuggu"
"ggffgefgguggfggfCfsssssiiBtssetsfksgkngnugguguggugggunuguuguugguncuuuuguugugun"
"ugguunnununnuuuuunuunuuuuuuunununununcuunnnnuugCeggugggggCuugguununungguuuuuun"
"uucnuuuuuuuucucuunuuuggugggpgupgnuuguunuungguuugCgneepppefuugebpebbeCfuuugppeg"
"nnungCCeepCeguCeefuugugggngggggCCCgCCgCgggugmmmm",
"ppeegugnggnguugggnpuugnggugguggugggguuunguggnuunnnugngggugggggggugugunnnnuuggf"
"guggggggugggCgggssssssqiqByssspggfkuuuuuggggngguugguuugggugfgegnnnnnuufuuuuuuu"
"gunuunuuuuuuuunnuuuuununnnnccuuunuuccnnnuccccufCCgngggggfCggggguuuuuuugunnknuu"
"unuuunuugnunucncuuuunuuungguggguuuuunuuuuugfuuugCggCCeepeguugebbbppefuugugepCu"
"nuugCCfCepCgneeeegggnuugguuungfCeeCCCufgggunmmmm",
"ppseuggngguuugguggnggggggggugfgfngngugnuuggugugunuugugggugngngugngguucunuugugg"
"uggfgggfgfgggfgegCsssqqiqtssfppguskfuggnggugggnugngngggguugfeguuncnnnnuugunugn"
"uuuuuunuufunnncuuuuuuuufnnnununnuuuuncnnuncccnugguuuuunuggfufuguuuuuufggunnuuu"
"uuuuuuuuuucunknuucuccccuguufnuuuufuuuunucuugunufggufgguCegunCpbbpCepeununCbpfu"
"uugfCffCeefgCpeeeegegggfuggguungppCCfungCegummmm",
"ppeeguguuuununguuugkngngnggfggugguuunuggggggfguuungugcnggugnuggguguguuggnnnnug"
"ngggngggggfgfggfefCsyqqqtysssppgunguuuuuggggggguugugugnCuuugCgunnuuunnngguunuu"
"uuuuuununguuununuuuuuuuuuuuunuuccnuncuununccuuunuuncuuuuunkngufgugnuugCCuuunuu"
"uuunuuunucccuuuuuccncccunfgpuuuuuunuuuuuuuufeuuggCuuuunuunugeeeeefCbegguuCppgn"
"nuCefufCCfggepeCCCggfgfuggguuuuepeffuuunCppummmm",
"bypefuuuugguugggugnguuguuggfuunuuuuugufuggggggfunuggungggguggugugnuguuuggngguu"
"gngugggggugggfgegfCCtqqsespgpfppgugunuuugggggugnguguguufnuuffgunnnngnnuuggnuuu"
"uguuuuuuuuuuuuncnnuunuuunnnnnnuncnucunnuunncuguuuuccnuufuuuunknuugguufCCguuuuu"
"uuguuuucccnucuunccucccccuugpgnunuuuuuuunucuugggfguunuuuuuuuCeCuuCnupeguunepbfn"
"ugeguuffgfCCeeCCeCggguCggfgunufCpgununuuCpeCmmmm",
"eeppugunuguuggfggugggguuungugcgngguuunkngnggfgguuggngugnggggngcgnungunuuuugucu"
"ggugngngngfggggggegsqqBsgCgpfpguunguuugngnggggguknggnunuuunguuugunnnnCfffguucu"
"unggnuuunggnguuuunnuuunnuncnnunccunnununuuuunuuuucnccuuuunuuuuunuugnuufCuuuunu"
"nuuunuucunuununccccncccnunueuuuuuuunuuuuccungfgggnuuuuuccuuCCucnguugCgugCeeggg"
"fCCgnuCgfgCeeCnfCCgungfCgCfnnnCeefunncnfeegCmmmm",
"eeppgugggugggCCfnggggngnnnnununnngggnguuugggCggufggggfugnggnunnfnnnnuuunggugun"
"uuuguugugggnggfggggeyqqsgkekpfpgggnguuuuungnggnuggguuuuuuuuguungunnngCpeeggncu"
"uguuuuunuggunuuunuuugnnunnccnnnnunkuuuuuuuuuuunuuunuuuuuuunuuuccuuuuunnunuccuu"
"uuuuuunuucuuucccccnccnuuuuuguuuuuuuuununcnuuufguuuuuunuucngCuucugggfufggeCCCgC"
"CCgungCggepefuufCfgggggCfCCncnfCggunnccfegnummmm",
"CeeengggngunggggggCgggknunungfggunnngngggfCgffgfgggugggunuggggngnfffggggggfugu"
"cunugunknggggfgfgggsyqtsgggegpfbuguggggfukngfggguguuuucnuununuuugnnnngepeeCuuu"
"ufugunuuggguuunuuuugugunuuccuunncuunguuuuunguucnggguuncuuuuuccccccccccuuuucccc"
"cncccccccucccccccccncuuuuuuuuucuuuunuuuccccuugunuuuuuuuncuugnnucuuCgngCCegneeC"
"ffunneCgfeefuuuuCCgggggfgCeuungfugnnuncgeCknmmmm",
"eeeeguuuuuggnugguCCCffguguggufpggggffffggggggggggggfggguuggnguggggguguugugnfgu"
"nnnuuuuugggggggugugCtqtsggggeepgpugnguggnuuuggnunuummmmmmmmmmmnuununnuggeCpppg"
"Cfguuuunuuuuuugggguugguuucccnnunggguuuuuuuununuugggguucuuuucnccmmmammrmcmccccc"
"cccccccccccccccccccnccuuuucccccnuuuuuuuccucnuguununuuuununuuucnunugggngCCggeeC"
"CgungeeCeCguunnugCCfggggfCpgnggfuuunuuugptunmmmm",
"epgeuungunuuufgggeeCggguugggngpppgggggggggCggggggnggCggggnfffuggggggffggfgngng"
"fnugggngngggguuffgggyABsgnppgeepggugugggguuraaa###.####.######.#.#aaamcnufebpe"
"peuunnuuunnnnuuugunfugunnnnunuuuCnuunuuuuuuuuuggggngunraaaa#.###.####.##.##.##"
"#aaaccccccccccccccccccuuncncccccuuunuuncccuugguuuuucunucnuuucnuuuuuunnuCfgCeCg"
"CeucfeeCefuuuuunffCgggguuCpguggufuununngyBkummmm",
"eepeuuua##.###.#.#.#.#.#.#.#.#..#.#.#.#.#.#.#.#.#.#.#.#.#.#.aaa#aaacrguggugugg"
"fgnggguugfggnggggggeyqqCggpgppfpgguununaa##.###.#.##.####.#.#.#.##.#.###aaueep"
"pCnunuununuuuuuuuuuunuunnuuuuuugguuuunguuuuuugfguuraa#.a#.#.#.#.##.#.##.##.##."
"#.####aacccmccmccnccccnccucnnnunuga#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#wlknmmmm",
"eeeeuuga.##.#.###.#.#.a.a.#.####.##.##.###.###.#.a.#.###.a.#.#.#.##.#.aamugggg"
"gggggguggggguuggfegstABsegppgppepngca####.###########################.#.##.#ac"
"gguuuuuuuunnnnnunuugunnnuuuufuuuuungguunuuunugera##.##.#######################"
"###..#.#.aaccccccccccuuufungguuugua#.##.##.##.#.#.#.#.###.#.#.#.###.a.###.###."
"#.###.#.###.#.a.a.###.###.a.###.###.a.#.wlscmmmm",
"eepegnga############################################################.#.###amng"
"uggugggggggggfggggCCAqtsffpgpgpgpra##.#.###################################.##"
"#anuuuuuuuuncuuuuunuunnuunugnuunuuufguunnnnuca#.#.############################"
"############aacccccccnggCCuugguugfa.##########################################"
"########################################jlkummmm",
"epeeuufa.###############################################################.#.##a"
"uggfCCCCggngggfgffgsqABsggpgpgpr#.#.##########################################"
".##accunuuucnugggunnnnunuuguuuncuuugguncncca.#.###############################"
"##########..##aacccncuugfuuuuncunfa###########################################"
"########################################wlkcmmmm",
"eeeeufnaa###################################################################.#"
"#aCgCeCCfgggggggggeCyqAtsppegr#.##############################################"
"##.#.acuunnuunCCguunncuuuguguuccnnuuuuunca#.##################################"
"#############.###mccnccucnccccccuCa###########################################"
"#########################################lkummmm",
"ppseggga#####################################################################."
"#.aceCeeguggegfggggeytABtspfa##############.####a.#a.#a.######################"
"#######muucuuggffuncncuuuuuuucnuccnnuuna#.#############################a.#a.#a"
".##############.##arccccccccccccuga###########################################"
"########################################jlkcmmmm",
"pepeunga.#####.a###########.a###########.a#.a#################################"
"##.#rCuggggggeggeCgsssyAABr#.#.############a##.###########.a#.a#.a############"
"######.#acuuuugCguunccuunuuuucnuucuuuca#.############.a#.a#.a#.a#.a#.a########"
"####.a##########.#.#accccccccccnufa.##########################################"
"#######.a########.a#.a#################.wlkcmmmm",
"eepeuuca########a.#a.#a.#####a.#a.#a.########a.#a.#a.#a.#a.#a.#a.#############"
"####.rksnngfCCCfefeesCeyqw###########a.######a##########a#########a.#a.#######"
"########.#mnuuggugucnunuununucnuununm##.########a.############################"
"##a################.#accccccccnuuna##a.#a.#a.#a.#a.#a.##a.##a.#a.#a.##a.##a.#a"
".#a.#####a.#a.#########a.#a.#a.#a.######jlknmmmm",
"eeeeunna##.a############a############a#############################.a#########"
"######kskgnegCgegeeeCCCs##.#######.a#####################################.a###"
"#########.#mnuufguuncununnunucuunuca#.#######.a###a###########################"
"#######.a############.amcccmcncccna.################################a.########"
"####a#########a###################a#.a###lsgmmmm",
"eeeeufCa.########################################################a####a.######"
"####..#sygCCgnfCggCefgna#.############a################################a###.##"
"##########.#agnuuuunnnunnnunnuuccca###########################################"
"###.#a####a.##########.#cuuccccccca###################################a#######"
"########################################jhkCmmmm",
"ppeengea#################.####################################################"
"#######wysCfggfgfffCeg#.##############.###########.a#######################a##"
"###########.#agknuunnnunuunnnnnuna#.#################################.a###.a##"
"#########.##a##########.#ckccccccna.##########################################"
"######.#############.a#################.wlggmmmm",
"ppeefCCa##a.############a###############a.#########################.######a.##"
"######.#tyCCuggnuuCgC#######a.#########a.#a.#a.#a####a.#a.###a.#############a."
"#a.#########.#mkknnnucnnnnnccnnnm.######a.####.###a.###a.##a.##a.#######a##.##"
"########a####.############cucccccca###################a.##a.##################"
"#####a##################################jlknmmmm",
"ppeeCfCm######.a##.a########.a##.a#.a#.######.a##.a###.a###.a######a#####.##a#"
".a######xtCguguuggfea#.####.##a##.a#######################a########.a#########"
"###############kkununnnnnuncnnuc#######.#a##########a############a#####.###a##"
"#############a##########.#aknccccca#####.a##.a##.a##########a##.a######.a##.a#"
"#.a######.a#.a#.a######.a##.a############hkummmm",
"eeepCCCa.###a#######a.####a#####################a#.#a####a###a.#########a#####"
"#######.wtsgggggnnfr#.############################.###########a.#####a.#######"
"###a.#########.#kkunnccnnncunun#.############a##############################a."
"##a.##########.#a.#######.#accccmca..##a###a######a.#############a.##a########"
"#############################.#a.#######jlknmmam",
"eeppffem##################################a##########################.a#######"
"#########dsfgggCggu.##############################a######.######a#############"
"###############.wksnnnuncnunuua.#####a##########.a##.###########.a############"
"####a#######################mcccnnm##a#######################a################"
"####.a#######################a###########lkcmamm",
"ybypCffa.###############a.##############################.#####################"
"#.#######xsugeeCCfa#####################################a##############a.#####"
"######a.#######a.kvkuuuccnnunm.##a.#####a.#a.#############a.#####.############"
"#####.####################.##cnfeCa.###############a##a.####.#######.#########"
"###############a.##a.#############a.###.jlknmmma",
"bbbpgfga######.a##.a#########.a#####a####.a##.a################.a#############"
"#a#######jsfegeCfm#.#########.a###.a###.a###.a#############################.a#"
"########a#########ssnnnncnknu########################a.a###a#####a###a########"
"######a#.a#########.a#######.aneena#####.a##############a##########a####.a##.a"
"####################a###################whkcmamm",
"ppppCCCm#############.#####a########a.##################a##.#a#######a.#######"
"#########wkgeCCCn#.####a.##a##############a######a.#a.###a.#####.#a.#####a####"
"a.#######.######.#wsknnnunnna#.#############a##########.############.#########"
"#################a##.########auuuna#######a.##a.###.###################a######"
"#########a.############a.###############jhkcmama",
"eeeeffea.############a##########.a#.##ajjjjjjw###.##.a##############.#####.a##"
"##.a####.wfuCpfga#######a############a########.a##########.###################"
"##a##############.#kknnncnuua.#######################################a.##.a##."
"a###########.a######a#######.#accca.###############a####.a####################"
"#.a##.a####a#.a##########a##.a#.#######.wlkcammm",
"eeeeggem#a.###########.###############hqqqyldtxvrra#.##############a####a#####"
"####.#####gCeeCfa.#######.####a.####.####.##########jhhvdvr#.##############.##"
"##a.#####a#########wkunuuuum.###a.#a.#######.##a.###############jxhdxr##.##a##"
"###########a#################.#ccca###########################a.##############"
"###a############.#a.##########a#########jhkcmmaa",
"eepyeCga###a##########a###.a##a#######hqCCngCgsgsCgc###.a####.a#.a############"
"####a#####feCCum#########a###.#a#########a#########xhdlssCsyr.#######.a####a##"
"##########.a######.#Cggnung#################a####a###a###.a###whiiysCkum######"
"##.a###.a####.a#######.a#######acca.###.###################.a#####.a#.a###.a##"
"################a#######################whkcammm",
"eppbeCCa###.##a.#############.########jBeCgffggguggnna.###a##############.#a.#"
"########.#CCCfga.#a.################a#############hhqvCpeufBbn#.###a##.#######"
"###########.########mnuugnc.#########a.################a##.##jhztpCnknknca.###"
"#####a#########.#######.######.amca###a###a.####a.#a.###########a#############"
"#####a.#############a.###########a.#####jdknmaam",
"byBpCCem.##a####a#####################htnnugfgggggggff###################a###a"
"########.#fnfCp###############################.##hhipCebeCeebbn#######a#######"
".####.a#############agunnna.#################.###.a########a#hhpbbbggnununa.##"
"#########.a####a####a###########rna.##########.a#############.a#########a#####"
"#.######################.a######.######.jlkcmmmm",
"ybbbCCer########.#####################hqCggggCCgCgggggm.#.#########a.########."
"##########nuner#.###a.#############.##a.#####a##jhipbbbbbpeeepbr.#########.###"
"###a#######a#######.#unnuna##################a######.#######hhlebbbeuuuunfc###"
"###.###########################.wuwwa#######a########a.##############a.#######"
"a#####a.##a.##########a###a.###a##a####jhhkcmama",
"pppyCfpa########a####.a########.a#####jtggCufffCCfCgggn#.#########.##a#######a"
"##########egefa.#########.a####.a##a######.a####jhtbbbooobpepbbb##########a##a"
"############.a#.a###.mnngc.###.a#######.a##################jhlkebbbCuuuuunca.#"
"#################.a#############wvdhhhxhhxhhhhhhhhxhhhhhxhha##############.a##"
"############a##xhxhhhxhhhhhhhxhhhhhxhhhhhxkcammm",
"eppbpeer.####################a###.####htppCggeeggCgfCgf##a####################"
".#a.#####abggf########a######a##################hieepbAooobpBppyr.############"
"##.##################annna#######a.###a#.##################jhtnebbpCuuuuccnn#."
"###a####################a.#####.#tttvvvvkvvvvvuvvvsvvkkkcnuna.#a.#######a#####"
".#############jltvttvvvvvvvvvvvvtstvvvvvvcccmama",
"eeybeeCa###############.a########a####jtCefggCfCgfngCgg###.a#.a########.######"
"#########aepCr#.############.##########a#######jhypeeeoAAobboobbb###########.#"
"##a###.a############.annfa.########a#######################hquuCpeeCgunucccca#"
"####.a######.a#######.a###a######dBCuccnccccccccnunnncccccnua#################"
"a##############lkcnguccccnguuccccnuncccccmccammm",
"eeppeeCm.#a.#a.#a.###a###a.###########jtCggfCgCgggunggf#.##############a######"
"#######.#mfCgm.####a.######a#######a.######.###jiybbbppAAobbooBbor..#a.####a##"
"####a#################ggc####a.#########a######a.###a.####jhdcnggCCeenccccccc."
"########.#a###############.######xACuccccccnnucungunncccccnfa#####a.####.#####"
"##a.#####a.###jlkcuuuuccuugggcccccckucccccccmmaa",
"ppppeeCa##########a###################jsCfgggggCcugCCgc.######################"
"#########uggCa####.#############.##########a###hqCbbbCeBAoobbobbbc#.##########"
"#####################.cpc.#########.a####.a#.a########a#.#jhvncuuepppuccccccca"
".#######a########.a#######a#####.jAeccccccnnncuuunncccccccfem#################"
"######.a#######hkuuunuccuCCppgccccccccccccccaamm",
"ybybepem##############.#######a.######wCfggCgffCCgfCCCa##########a.#########a#"
"##a.####wunCe####a###a.########a##############jhtepppCepoAooobpeey############"
"##.###a.####a.########aer#.#####################a#########jqnunugebbecccccccca"
"############a.###################wAscccccncugCgunnccccccccuCa############a.#a."
"####a#########jhkuuccununCeeeecmcccccccccmccamaa",
"bbpppbpr.########.####a####.a##########fgggCCgCfCgfgCc#.#####.a####a#.a#.a##.#"
"####a##argngC#.########################.a#####jdsCgggCeboooAoyeeep######.a####"
"###########.##########afa#######################.#########hdcugneeppncccmccccm"
".########.####a###################qsccccncnueeeuccccmccccggga.######.a########"
"##############wdkunccuuuufCgeeuccmcccmccccccmamm",
"ppepepea########a####################.aggfefeCCeeCgfm#.####a###############a##"
"#######jBfCeC.###########a.#a.####a.#########.jlsCeCngbbooAAoyybbyr.##a##.####"
"#########a##a##a.####.ana.################################hvnnuuuCeebccccccccc"
"##a.################a.####a.####.wdvnncnuuugepencccccccuCCuna#####a###########"
"########a.###.jhkuccccnunuugnencccmccccccmccaama",
"eepeCCfa#################a#######.a###aCCgggffCCfnra#.####.###################"
"######jhogfCc####################.##a####.a###jqggCfugpBbbboBBBobbr######a####"
"#######################na####.a#####.a#############.a####jhvnnnnnueeCnccccccmc"
"#.############.a##.######.########hsnncunuugeegccccccccnCenca##.a#############"
"####.a########whknuccckgggeggpfcccccccccmcccamam",
"ppybCena##a.######a.##a.####.##a#######cccrcraama#.######a####################"
"a.###jhAopCec#.#####a.##########a#############hqngfgggepBBBBppboooo.######a.##"
"a.##a.##########a####.#na.#a###a.#######a.#a.#############hkcncuufCCeCcccccccc"
"a##a#############a###a####a#######hvkuucuuuugCncccccccngeCuma.##############a."
"##############jhkknncunCgnegeefccccccmccccccamma",
"ppppfCem.###a#.#############a######.##.###.#.###.##.##########.a#.a######.a###"
"####jhdBopCea#########a#.a####################htnnnngfCpBybbbboAAod.##########"
"#a####a#.####.########.n#########a####.######a###a#######jdkccnngnepppcccccccc"
"a.###.a###########################xtgfcccucnugfnccccccngegcna####.###.a#######"
"a#############wdkuknngCeCgefgeeccccccccccmccmaam",
"epppCgCa##########################a#####.##################################.##"
"###jhlsbBbefa##a.#############################hqunugfCebAbbbbbyoooy###########"
"############a###.####.#f.############a########a.###.#####jlucccuggebbCcccccccc"
"a#######a.##########.#######a.####htCCncccccufCnccccccuCencna.##a#####a.######"
"#######.#######lknnugeeegCegfefnccccccmcccccaamm",
"ybypCfCm######################.a######################.a############.a########"
"##whhtCpbbeCa######################.a####.a###hvggguggeooobbbbbebbp.##########"
"##.#############a######c#.##.######################a####.jlkcccuueeppncccccccm"
"a.########a#########a######.######jtCCncccccngCncmccccneCucca######a#########."
"a#.a###a###.##jhknnugeCgCeegeeffncccmccmcccmmmaa",
"ppbpeega##############a.#################################a.###################"
"#hhlvgfCCebea.##########a.#a.#a.#a##.#########hvgfnnnfepybpbbeeCCCe#..#####a.#"
"#a####################.c###a####.#########a.#############jdcnccugCCeencccccccc"
"a############a.#############a#####htgguncccnnngnncccccgCfccca.#########a.#####"
"##########a####dkcnuuggunCpeCCCefccccccccmccaamm",
"eeppeebm.#####.a##.a#######################################a######a##########w"
"hhqkCgffCebbm####.a#.a##############a#########hsgffnngCCepbpeeCCfCC.######.###"
"########.a#############m########a#######################.jlccccnnepppncccccccc"
"a.###.a##.############.a##########jvnuccccnccnugnccccnCCnccca####.############"
"##############jhkcccccccugeeCnCbfcccccccccccmmaa",
"ppeyeepa#a.##a##########a.####a.##a.######a.#a.#a.###a.#####a.###.###a.######h"
"lqkggggfCCebr.#a#########################.####xvgggffgnffCeegCCffff##a###a####"
"######a#####a.##a.#####m###########.#a.###########a.#####jdcccccgebbefcccccccc"
"a################a.#a#############hdcncccnunnnufnccccfefcccca.###########a####"
"#######.#######luccccccccfppegfpecccccccccccmaam",
"pppbeeCm############.a################.a##########a####################a###adt"
"sgggCggffffCr##########################a######hvgCgggfgCCCCeCCCCCCf..#########"
"##.a#.####.############m###########a#########.a##########jvcccccneppefcmcccccc"
"a.#############.a############.a###jvccccnnuunuufnccccnCncccca#############.a##"
"###.a##a######jhkcnccccccnpbpffpfcccccccccccamma",
"ppppCCer.#################a.########a####################.###a###########akuss"
"gggfgfggCCCga########################.########xtgfgeCggCCCepeCCgfgna#.########"
"#########a############.m#a.#a.#############a###.########.wdnccccgpbbpenccccccc"
"a#########a.######################hvnccnnunnunugnmccnunnccmca.####a.##########"
"###############lkucncccccugeeggencccccccmcccmamm",
"eseeCepa######.a##################################.####a###############.##ankk"
"CgggggggCeggm.#######.a######.a###############jtCggfgCfCCCebeCCCCgg.##a#######"
"a#################.a###m.###############.a#####a#########wxkcccngpppbpnccccccc"
"a.##########a#########.a#.a####.##hdccnccnnnccnuuncnnncccccca#######a#.######."
"a#######.#####jdknccccccccnngguuncccmcccccccamaa",
"pppeepem####a###################a.####a.####################.####a.###a##.##aC"
"ggggCffCeeCCa###########a.##a#.#####a####a.###jqfgngCCeCnfCeeCfgfgf.##.####a.#"
"################a#####.n#####a#######a############a.######hnccccgepbbbfccccmcc"
"a####a.#######################a###hvccccccccncccnucnnccccccca.#######a########"
"#######a######whkcccmccccccnuuuncccccccccmccmamm",
"eeepeCCa###.###################.###########.a####a####.#####a##############.##"
"ngggggffCCffc.##.a###############.a###########jBggungCCCfngeCCfgCgn#.#####.###"
"###########.a##.######.f#.####.a#.a#######.a##############xkccccneebbbfccccccc"
"a.#####a#########.a###############hvcccccccccccccnnnnncccccca##############a##"
"####.a#########dknccccccccccnnunccccccccccccamaa",
"ppeeffCm.#a#####a.#a.#a.######a##########a#############a####################.#"
"#cggngggfCCCc#######a.###a#####a####.########.jtfgggfCCCggfCfgggfgr#######a###"
"##a.##a.#a####a########ca###########.#########.####a######xvccccugpbbbnccccccm"
"#########a.###############a.#####jhncmccccccccccnnuunccccccca.a.#a.#######.###"
"##############jhuccncccmcccnnnncccccccccccccmamm",
"ppypCfea#######.########a##.a#######.#########.a#.a###########.a##############"
".#kkCgggffffc.###############################.wtsgngfffgggfgfnnngfc.##########"
"#####################.#c######################a#####.a####xvccncnnpbbbbncccccc"
"a.#####.#####.a##########.######.jlkcccccnnccccccnunuccmcccca############a####"
"#######.a#.####lknccccccccccnncncccccccccccmamaa",
"ppbpCCCr######a######################a##.#########################a.##########"
"#.#ksggfgcgfn########################a.########dsfggCgngngggggfgufa##a########"
"###############a.#####aca.##########a##########.##########avccnccuebbeefcccccc"
".##########a#######a.###a########jhnccccnnnccccccuuncccccncca.######a.######a."
"#########a####jhuccccccccccncnnnccccccccccccmmam",
"epppCCea##########################a#####a#############.a#.a######.##a#########"
"##.#svuggnnng.##########.a#####################rvffngnnffgnffCgggga.##.a####.a"
"###########.#########.ana############.a########a#########.wvuccccuCbpeeenccccc"
"#.##############.a###a###########jqknccccnccnccccnuccccccccca#########a.######"
"a##############lknccccncccccnnnncnccccccccccaama",
"peeeCCCm..############a.#######a.###################a###########a#####a.######"
"###.rssngncgfa.#a.########a.###a.######a.######wsgnfnnncnggngfCCCC########a##."
"##a.######a###########anm.###a.#######.##############.#####rkccccgpbpepenccccm"
"##a.#############################hdcccccccccnnccnucccnccccnna.################"
"a.############jhkcccnnnnccnccnunnnncccccccmcamam",
"pyeeCCea#########.a##########.a######.####.a######.#########.a################"
"#####vsgfggffa######.a###########a#######a####.wtgfnffunfnngncnfff#.#####.###a"
"######.a############.#rnc###.##a#.a###a####################rvcncngbpeeppfcccca"
".###a######################.a####hdccmccccccnccccuncccnnccnna##############.##"
"##############wdkcccnnucncnnnuggncncccccmcccaama",
"pppeCCCa#a#####a##.#####a.##########a###a####a.##a##################.#########"
"####.wvfggugfa.###a##############.#######.######rsnnfCgnggfnnnuggm.###########"
"####a#################fgc#.a############a.###a.#####a#####.wkkncuCbbeebefcccc#"
"####.###a.#a.#####.##a.##a##.###jhvccccccccnccccunnccccnccnCa.##a.########a###"
"####a.#a.######lncccugnncnunuuCpgnnccnccccccamaa",
"ppppeeem###.a#####a#######a######.#####whhhxxww#.#########a###.#####a###.a#.a#"
"######ssnfnggc##############.a###a#######a#####.rskgCffgnggnnnngga############"
"#########.a###.a#####wngna#######################.a#########rkccuCppCeppecccm."
"####a##.#####a####a#############jhuccccccmcccccccunncccccnnna#####a###########"
"##############jhgncnuguncnuungepefnccnncccmcamam",
"ppeeeCCa########################a######jAyytttspr#.#a.###.###a########a#####.#"
"######xvgngggn#.#####a.##########################gCgggggnggnungfn.######a#####"
"###############.#####junna.####################a####.######.akucnebpfCpbeccca#"
".#####a######.##################hlncccccccccccccccunncccccnna######.#a.######a"
".##############lsnnuuuuununucueppCncccnmccccaama",
"pspeCCCm.####.a#######################.jigseefCCCfa####a######################"
"####.#wtgggggga###.#######a########.a###########.rCfgngucngggfgga.###########."
"a##.a########a#a###.jvgunn.###########.a#####################ccnuepefgebbecc.#"
"#############a##################hlccccnccccccmccccuCfncccccna.#####a##########"
"##############jhnnuunnuguncccnCeeeucccccccmcmmam",
"eeeefffa##########a.###a.##a.##########jqCeepCffufna.############a.###########"
"#####.wvsggngfm.#a#####a.########a######.########.ngnnnggngfCCCc.#a.##a.######"
"####.##############wjteegn######a.#######a.#a.######a#######.anugebeuuebbpn###"
"#################a.###a.#######jhvmcccccccccccccccnffncccccca############a.###"
"a#######a.#####dknuccnguuccccnCepencccccccccaaaa",
"eeeeffga###############################jqCCepefefnnc############.#########a###"
"#######vvcngcfn#.############.a#########a##########fgggggguCCfc############a##"
"########.a#########jhteppga.###.##a##################.a#.a###.angpppgngebpa#.#"
"##############.a########a######xlcccccccccccccccccnnfnnccccca.##########.#####"
"#.a#.a########jhkcnccuuuncccnnCeppfccccccmccammm",
"eeeeggfm.#####a.################a.####.jqfCCCCgCCufc#.##a.#a.##a####a.######a."
"#######xtnunugga#################.########a.#####.##nCfggggggc#.#######a##.###"
"##a###a##.###.#####jlsCebec#.#a################################agpbpfnuepa#.##"
"#########################a.####hlccccccccccccccccccnnCnncccca#########a#######"
"###############luccccuguuccnngCCppCnccccccccamam",
"eeeefgga############.a#########.#######jqfCCfnggunnnm#########################"
"#######wtfgnungc.#################a#.a############.##augunfna.#########.##a###"
"#############a####jhqfngppna###########.a######.a#############.#acbbfcnr######"
"#.a#.a##.a####################hhkcccccccccccccccccccnCCnnccna.###.a##.########"
"##############jlkccccnununncnfCeepennncccccmmamm",
"eeeecfgm.#a.####################a######jqfeeguggfnnun.##################a.####"
"########tsguggnfa.a.####a.#############.############.##aaaa.################.#"
"##################hhvuunCefm.#####a.#########a##.###############.##raaa.#.####"
"###############.##a.#a.######jhdncccccccccccccccmcccnCpennnna###########a#####"
"########a.####whknccuuunnuucnufeeeCfncccncccaama",
"eeCefgga##########a####.a##.a##########jquepCugunuggna.#######################"
".a####.wdkuuggngr#.####.##a#.a#########a##############.###.###########a#####a#"
"###############.ajhqnunnfCfn#.#######a######.###a#################.##.#.#####a"
"###############a#############hhdccmccccmccccccccccccnfepenuca#######a####.a###"
"###.a#.###a####dknccncnnnucuccueeeeefcncccccamam",
"eeeeggfm.######a.#####################.jqCpeggfgngnuna#############a.########a"
"#.######xtnfngCeea#####a#####.#############a.#################a.#a.###########"
"a.#a.############hhtnfnnngeum#a.#######.###a########a.####################a.##"
"#########a.#################jhlccccccccccccccccccccnnnCbegnma.##############a."
"#####a########jhuccnnnnununnunnfeepefnccccccamma",
"ppeefgga#########################.a#.a#jqCpffnguunngga.###.a##.a#.a###########"
"########xtgggnCebn.##########a##########.a###a#.##############################"
"#####a###.a#####jhqcgnnnnuggna.########a##########.#####.a####################"
"####.a##.##a############.a##hhkccccccccccccccccccccccnnepeuca#####.###########"
"a##########.a#wlkcccccnuuccccncfeppbfncccmccamam",
"ppeegffa###########a.#################.jqCegnfnnnnunnc###a##############a.####"
"#######.jtgfggCpbba.#############a.###########a#######################a.######"
"#######a########hlknugncnuungm###################a####a##.####################"
"##a###########a.######a####hhdcccccccccccmcccccccccnccngepnca.###a######a.####"
"##############whucnccnnuncnuncnneppeenccccccmamm",
"eeesngga##.a#.a###.#a###.a###.a########jqCfguggnnnnufc.##################a####"
"########wtkggfCpbpf############.a##########################.#########.#####.##"
"#####.#########xhqnnununcnngnua.#############################################."
"a######a####.########.####jhhkcccccccccccccccccccccccccngeena#################"
"###############lkccccnnncncncccnCCeppCncccccamaa",
"eeeegfna.##############a###############jqfgucgfunnncun#.#############a.#######"
"#a.######dsungebpCfr.####################.######a.#a.#a.##a#####a.########a###"
"####a####a.###hhqcnnnunnnncnunna..#a.##a.#################a.#a.###a.#a.#a.#a##"
"################a.##a#####hhvmcccccccccccccccccccccnccccnCeCa.####a.##########"
".#a.#a.#######jhucccccuucuunnccnnCCpbenccccnmmmm",
"eCeeCCfa###################a##########.jqugnuununnnnnca###########.a##########"
"##a######dvggfpbCfger.##############.a###a########################a###########"
"#############jhlknnnnnnnnnnnnncc###########.a#.a###############a##############"
"#.a######################xhlccccccccccccccccccccmccccccccneea################a"
"##############wlnnccccccnuunncccnnfebbfccmnfmmmm",
"eeeegCfm.#################.############jqgnnnuucnnnnnca.#a.##a.########a.#a.##"
"#########xtugCeCffCeya#.##a.######a########a.###############################a."
"#a.#########jhlvunnnuunuuncncnccc..######a########a.##########################"
"#####a.#################hhlccccccccccccccccmcccccccnnccccnfpm.a.########a.####"
"########a.####whuccccccnuuuucccccnuebbfccnuCcmmm",
"eeeegCfa######.a######.a######.a#.a####jqgunnnununnnnna########a############a#"
"##.a#####wtfgCfufgfebba#####a####.########################.a########a##.a#####"
"#######.###whlvcnnnnuugugunncccccm##################a###########.#############"
"#######################hhlkccccccmcccccccccccccccccnnnccccner#######.a########"
"###############dkccccnuungucnnccccnCppencnfecmmm",
"eeeenufa.###a####a.###################.jAgnnnnuungnncna.######################"
"####.###.jtpeCgnknfebeea#.######a####a.#################a##.#a.##########.####"
"######a###jhlvcnnngnuunuunccccccnnm#.##########.#####a.##################a.###"
"##.#####a.###a.####a.#hhluccccccccccccccccccccccccnccncccccna#####a##.########"
"##############jhuccnnncugCnuunccnngeeeeunnfCnmmm",
"eeeegnfa###.#######a#######a###########jqeggugnnuggnnnc###########.a##########"
"####a#####tBbCugggebbebba###.a###########.######.a################.###########"
"#########hhlcnnnnnnugununcnnncccnnkc#.#########a#########.a#.a#############a#."
"a########a####a###.#jhhlccmccccccccccccccccccccccnfCgccccccnm.########a###.a##"
"##.a###########lkccccnnuCegnnncccnfeeCegnnCCnmam",
"eseenngm.#a###############.#####a.####.jACCCgnnunuunnfm.##a.########.#####a.##"
"########.#dobpCfgCppeCboea#.###############a.#a#####a.##########a##a####a#####"
"#a.#####hhlkknncnnufgunnncnnnccnnnnuc##.#a.######.#####a############a.########"
"################a##jhhdkcccccccccccccccccccccccccneeCnccmccca###########a###.#"
"a####a.######.jhncccccngeCgnnnccccfeCCCCguffcmmm",
"eeeeugna################a##############jqfCeCunnunnnnnc#.#####.a####a####.####"
"##########xBepeeeeppeebbssu##.#########a###########.##a#######################"
"###a##whhqvnnnccnnnugunncncncccnccckkna##.#a#####a###############.a###########"
"########.#########hhllcccccccccccccccccccccccccccfepfccccccca#################"
"#######a#.a###whkcccccngeCnccnnnnnuCfngCCgngmmma",
"pppeuufa####a.#a.#a.#a.###############.jqgCepeuugnnnnnn#####a##############a##"
"###.#####.jyseeeeppeebbpfksfr#..#a.###############a###############a.######a.##"
"####jhhlvknnnnncnnnnunnncccncccccccckknr#######################a##############"
"##a.###a#####.##hhhlvccccccccccccccmcccccccccccccgbpfccccnnma.a.####a.#####a##"
"##############jhccccccuCeCuccuunuunnuuugfgncmmmm",
"ppeCfuga.###################.a#########jqnuepegugfnnnnna.##############a######"
"###a######wttgCpbbbbbbpCfgsssuw##.####.####################.a##.########.a####"
"##jxhlqgcncnccncnnuuunnnncnncccccccmckkkCr##.#####.a#########.a#######.a######"
"####a#########jxhllcccccccccmcccccccccccccccccmccfepgnccnfnna#################"
".a############wdkncmccnCCgnccuunnnnuunngguunmmam",
"epeeugfa#########################a.####jquggfCufgCggunna############a.#####a.#"
"#########.#lBeebbbbbbpCggfCgkssuw##.#a#######a.######a.##a####a###############"
"jhhhqteCuncncnnnnfCgugnnnnccnccccccccnckvCvr###.####a.#a.#########.#a##.######"
"############jhhllkcccccmcccccccccccccccccmccccccnfeCnnuugunca.#a#######a.#####"
"###a.########.jhncccccfCeucuuuunccnncnnuuuunmmmm",
"eCCenuca################.a####.a######.hlnnunugggCgunffa.######.a#############"
"###########hBepbbbBbbCnfgggCfgsttvrw#.####.a########.###############.a#####wjh"
"xhqvkcgCfcnncnuCCeeuuugnffnnnnncccccnuunugsvvra##.#######a########a#######.a#."
"a##.####.jxhhllkcccccccccccccccccccccccccccccccccgggknugggcca###.#############"
"#########.a###jlkccccnfeCunnuunnncncccnnguuummmm",
"CeCegffr###############a#############wjhqunuuugggggnnggra#a.#####.######.#####"
"a.#a.####wjhAeeeeebbCgggfgfCefgCCtttvxa####.#######a######a.######a#####jjhhhq"
"qsuggugCfcnnnfCCeeeuuuugegguugffnnnccuunccckuvvvxj####.#################a#####"
"#####wjhhhhldkccccccccccccccccccccccccccccccccccngfgncuugncka#################"
"############w#hhucccnnCeCnccnuunnccccnuguuunmmam",
"eeeCfkvdxhxhxhhxhxhxhxhhhhxhhhhhhxhhxhhhvnuuugffggggugtdhhhhhxhhhhhhxhhhhhxhhx"
"hhhhhhxdhhhhsCCCCeeeeggggggCeCCCeCfsttBqvxjj#######.##.###.######.#jjxhhhlqtvk"
"uuCggungfnnuuCeCCCnuccuuCggunugeuuccccnuncccnckkvtqdxjj######.a##.###.#######j"
"#jjhhhhllvkcccccccmccccccccccccccccccmccccccccccngCuuccuuucvxhhhhxhxhhxhhxhxhx"
"hxhhxhxhhhhhhhhvcncccfCeuucccuggnunnuuggguucmamm",
"eeCegkgsssvsvvsvvvvsvvvvsvsvvCttsbyyyvvtggguunuufugnnnsksvsvsvkvvevststevsvsvs"
"tsyyyvsysttsnCbbeeCgeggncgfCCCCCeCCffeyoytttddxxxjjhjjjjjjjjjjxhhhhhliiotkkccc"
"nuggguCeegungffefguncnnuguunnnnCgunnunncnunccnccfeyptdtdxxxjjjjjjjjjjjjjjxjhhx"
"hhqiAtvkkccccccccccnccccccccccccccccccccccccccccuCgucncnnckkkfvvkvstsvsvvkvvkv"
"kvvvkvkvuvkvvvvuccncnCeCncccnngCguuuugggfuncmmmm",
"epsenugugugucnnnnngnnccfugncngggcgCbpCcggggnnugggggguuuunnunnnnnfnggCffugugnnn"
"gepeggCfffggCbbbbCgfgnkufgfCfCCCeeCugCbbeffkssttttBqqqtqAiiyqqttdttsybbgnguuun"
"ncufuueeeggnuuCpeunnncnnguuncccuuuunuunnnuunccnnCeCucnkkkvvtvddqyiiAAoyqlvlvdv"
"kusppCgufCfncccccnccccccccccccmccccccccccccccmcngCncccncccccfkccccgsguggcccccc"
"cnnncccccmcccccccnncnCeunccnnuuCegungffeggunmama",
"ppbegnggggggucncnnnnnunnugguuuffufgepCuugfunuuggnuuggnggufunnnnngfnfCggnugfguu"
"CebegggggggCebbbpCfgggfggfgfuffCCeCgfCebCgggnnggCCCCgugeebbsnnfnnnngpbpCgnuuun"
"unnunugegfungfCegunnnnnnnnnnncccnuuuuunununcccugCfCunknuncncnccgpbybessucccccc"
"ccnpbCngCeeCffncnnnccccccccccccccccccccccccccccufgncccccnccgCnccccneuncunccccc"
"ngnccccccncccccccncnuCgnccccnnnufgguuugggugnmmmm",
"ppypgnnuugggunugnnufunuunuuunuuunngCeCgguggggfgCCgfuggugguugnnnfgnggggguungnuu"
"CpbeggnugCCepbpeCCgfgggggnnnnfnCeeCgfgCeCfCgCggCCCfggngCepbegugnnnngebpegunnun"
"nnucnnuuuunnuegnuuncccnnnncnnncnncnnnnnnnnuncnufgunuunnccncnnccCpbbbepCgufcccc"
"ccfppCuuCeeCeeefnccccccccccccccccccccccccccccccnguucccccccnfCucccnugncnncccccc"
"cuucccccccccccccccccnfnnnccnuuuuggguuuggggnnmmmm",
"ppppgngugnfgungnungunnnnnuugnnuunnugggunufgnfgugggguggfgungnnggggggfCgggcggfff"
"ebbCgnfggCCpeCCgCCCgggfgufuggufCpeeegfgffCeCCgffCCgCCCepCCppguugnuggfCpbgnnnnn"
"uuuunugunnugefuunnncccnnncccccnnnnnnnnnnnnnnncnnucnunnccnncnnngebbbbeefgCsnccc"
"ccgepgcccngfCCeeCnncccccmcccccccccccccccccccccuuunccccccccnuuccccncunnccccmccc"
"ngnncccccccccccccccnnnnnnnncnnnungCggnCCggucmmmm",
"eeeCunnuuguuuguggnunnnnununnnnunuugfgggggggggggffguugggffggggugfnnggfgggnfnngC"
"pbeCugffCfCCCggfgCgfguggCggufffeeeCCgggggCeCfgggCffCgCppfCebCungfgfnnuebpnucnn"
"nunncuCgungCCgunncccccnnccccccccnnnncnnnnnnunuuunccnnnnunncnnfepbbbeeefnCefccc"
"ccnCpfcccccnnfCeefncnnnnccccccccccccccccmccccnnuuccnnccccccnccccccnnuncccccccc"
"cnnccnccccccccccccccnnnccncnnnungfCCnnCeeCgnmmmm",
"eegCugnguufuuuggggnnnguunnfnuggufnugfgguggggfgggugncggCgCCggugngggggggggngggge"
"bpCgugggfgCCgCggCfguggnfCfgfgggCCCfCgggggfCfggfCgggfCCpbgfepeuuuuuuuuggebeCCfu"
"ununngpegggCgnunnnnncnncccccccnccccnnnnccuuunnunnnuunuununnnnfpbbbeepeguCeeccc"
"ccngCuncccnnccnCeCucnnnnccccccccccccccccccccccucccnnnncccnnnccccccnugucccccccc"
"ccncccccccmccccccccccnnncnnuunnufgfCnnCppeCgmmmm",
"CegCnuguguguugnggfgnuggnuucggngufngufgfgCggggggggggufgggCgggguggCggggnnffgcnfe"
"beCggggCgggggggCgfggggggCCgugfngfgfungufgfgngngefngffCCegCpbbpCgnnnuuuuCepeepf"
"nnncnfeeepguunnnncnnnnncccccnccnnnncnnnnunguuuunnnuggguununnffebbeCepeunfpeucc"
"cccnCgncccccccnCpCncugfncccccccmcccccccccccccccnccnnnccccnnnncccccnuuucccccccc"
"cccccnnccmcccccccccccnnncnnnunuungfgnnnCpbegmmmm",
"eeeeugnguggugggnnuunfgugfggfgfggnngggggfgggnggggffgfggfgfggfgggggffcncgngngfCp"
"bpefgggggggCffCfgggggggCCggggggeeCgggugnggggngCCCfggCgCggCbbbbbencnnnnngCeepeg"
"cnnnngCepenncncnnunnnnnnccccnnnnnnncnnunngguunnncnuguuuuunnnuuCbpCCepCunCbgccc"
"cccueCncccccccnCepucuugnccccccccccmcccccccccccnccccncccccngunnccccuunnccccmccc"
"ccccccccccccccccnnccccnnnnngnungncggnuugCepCmmmm",
"eCeegggggngfngnnuuggcggggCggggggunfCggggfgugcfggngnggCggfCgggggggggngfnnfnggeb"
"bpeCffgffffggCgfgggCfggCCCCfnnCeegfgnngggfgggCeCggCCgfgggebbbbbbCnunnnnufCfCgu"
"unnnnnfCCCuncnnnnnnnngcnccccnncnnnucnnugununnnncnnuuuuunnnnnnnCpeeepeguuCpgcnc"
"cccfeegcccccccnfeegcununcccccccccccccccccccmcnuncccccccccnuuucnnncnunccccccccn"
"ccccccccccccccccccccccnccnnnnncnngCfunfuugCpcmmm",
"eepegCggugngugggggunguggfeCCggggungCCgggggufnggfgcggfggggCggCfggnngngggngfggCp"
"bpCCggfCggggCffCgfCCgCCCCffCngfeeCgggfggggfCCfefgeegnuffgebbpeebbpCnnnuggnuunn"
"nnnnnnugunncccnnnnnnunnnccccncnnnunnnuunnnnnuunnnunnnuuunncccnCpbpeegungeeuccc"
"cccneeCncncnccngeeCuggnncmcccccccccccccccccccunncccccccccuunnccucucnncccccnncc"
"ncncccccccccccnccccccccnncnncnnnuCCgunnnunfCgccm",
"epeegffggguunnncugggfggggCCCCfggggggfgnggugngfgggfnfgggggCCCCCgfgnfgggunngffCe"
"eCCCgggCgngfCCCfCgCCffCCfggffgfCCgCggggeeCCfgCgCCeCgggggCebeeCCebbefnnuuuguuun"
"nnncnnnuunncccnnnnucnnnccnccnnnnugunnunnncnuggununnnnngunncccnCpbbeefnnfgunucn"
"cccnCbpfnncccccfeCepggenccccccccccccccccccccnuunccnccccccnncccccnuunncnnnccnnn"
"nnnncccccccccccccccnccccnnnccnuCCeeefnnuuungnncc",
"ppeengggucuunnggCgCCCgngCCCCCggnugngguggunnggngfggggggggffCfCggnnnggCggncfCCCC"
"fCCCCgggCffgggfCCCfggfCfggcnuggCfCCCungepbegnffCepmmnugfgebeCCgCbbbeggfgunnunn"
"nnnnnnuunccccccnugnccuccncnnnnnugugunnnnnugCegucccccnuuncccnugCpbpeegnnnuuucnn"
"cccnCpbencccmccuCCCeeCeCffnccccccccccccccccccnnncccnccccccccccccnuuuunnnnccnun"
"unnncnccnnnccccncnncccccnnccnnnfbpepeunnunnnmccn",
"eeeeggggr.agffgCffCCgggfCCCCCCu..Cfgcma#aangggggfCCggfgggCCCfggn#.geeggngCCeCC"
"fCCCCCffggggggggCfggggggguuaaaangCCCufgCebbeCgeepa.rsggggma#aceCCeepCeeguuuuun"
"ununnnuuc..acnnnugc#a##mcncugnnnugnunncnngCeguca##acnuncnccnggee#.geffnuncnuun"
"ncnnCebefnca.rccnfCCeeepefCCnncmccccccccccccccccccccccnccnnncccccuugnunnncccnu"
"uuncnnnnncccccccnnnccccccccnnnnCppeppfnnnnnnmmcm",
"eeeegggfa.wtgggfuuCCepfufCCCCCg.#qgfg#....#kgggguCgnnggnffnncggu.#lpCungCCeCCg"
"fCCCCCguCCgcgnffncgggggfggn.....rfCCcnnfCbbpeeebemrqsnugg#....recueepuegccuuuc"
"cuunnnnc.#w.wncnufc....wkncuCunccnccnnnuuCCguna.....rnncmnnuCCgg#.Bpeguncccccg"
"uccgCfCfncc..dkcnfCegfeeCnfCencccccccccccccccccnnnnnnnnncccuncccnnnuunucccccug"
"uuunccnnccncccccccnccncncccccnnCpeCepgnnnnnnmmmm",
"eseefggCm.wtggua.#angr.#aCfca.a.#lggfa.wlw.#ggm#.acaanc#rCm#.acf.#Apra.acecaaa"
".afCCa#.anc#aanm..mfnmggggu..lw.wsfa.#aCaaa##cppa###cfgun#.xx.#daaar#agc#am#a."
"#annuncc.#w.wvncnnc..xxdva#.acna.a#.anra.anuuuc..dw.wka..#cfca##..lya##acm.a#a"
"a.#cnca.#aca.hk.anga##afm.aafa.#mncmccccccccccccnnnnnnuccccuunncnnnuucnccccnnu"
"nuunncccnnnnncccncnnccccnncnnnnCbpCCCfnccnncammm",
"CCCCgnfCa.wtCf..w#.wpar#.vc..#..#qCgga.jtf#.xm.#w..#.da.xr..w..r..Ak..#..km..#"
"#.wfa.a#.#a..#r.#wxsa.rfggn..ir.jt..w#.r#..#.#Ba.##.#kfgn#.##.dd..#r.#Br.wr..#"
"..rnuunna..#qtcccuc.#dvva..#..ra.....s#.wwvunnm..qa.wtaww.wk..#..#Ba.##.#a...."
"...#kaax..ra.d#.wva.w#.w#..#x.w#xCccccccccnnncnnnnnnunncccnunuuunnuuunncnnccnn"
"nnuncccnncnccccccnfncccnncncnnnCybgngnnnccccmmam",
"CeeCnggfm.wtCr.wx.#ltarw.ja.xqv.#qggfa.wtf#.x.#x#.xd.###q.#x#.xd.#A#.dqv.wr.wq"
"d#.v.#x#.dx.wqx.#wvva#dsggc..#.#qr.wx.#d#.dB#.t.#x#.xqgfn#....db.#Ad.wAc.jr.wl"
"#.xknuua...wxaccnnc...#c..llw.wa.xl#.d..wvdncnm..#.#lvaaw.ww.wAd..x.#d..xw.wx."
"#l.#dcar##x#.#.#qr.wx.#la.wqw.#xtscncnncnnnnuunnnnnnnnncccnugguucnnnunnnnunncc"
"cnunccccnnnnnccccccnncnccccccnnfeyCuuunnccccmmmm",
"CCCegcgfa.wtum..#wqqa.##.w#.dsc.#ACgfa.jtu..x...#dqsa..xt...#vqt.#d#.qsc.#w.jq"
"Ca.x...aqqr.jtna..#gnvqgggn..w.wqa...rqt#.ds#.d...adqsngu#.xl.#j.wqc.#Ac.jr.xt"
"a.xvngu..xw...rnnnc..#wx.#lkm.##.xv..dr...kccnm..w.#lm.##.w#.dyf#.x..##lda.jr."
"wt.#d#.w..xa...jda...rqAa.xvc#..#nnnnnnnccnnnncnnccnnccnnnnuuufuunnuuuunnnnccc"
"nffccccnncnnccccnnnnnnnccccnnnnnCyCuuunnncccmmmm",
"CCeegggCa.#wmc..wdrn.#dr.jw.wka.#qCfc#.wr#.#q#.#drrnc.#qta.#dxrC.#ta.jca.wx.#t"
"c..q..wlwcm.wvncv#.xmanggCu#.d#.wc..xdrna.dk#.A..wlrcuuun#.xr.#r.#qn.#da.wx.xt"
"a.xeCeC..dr..wqfucc.#ldt..xca.jw.xk#.hkkw.wkccc..l#.r#.dx.wr.wvm..d#.wdwka.jr."
"#d.#r.#qw.x#.x..rc..xlrCa.xkcmx#.vuuuununcnuuncnnnnnnnnnnungguunuunnunnunucccu"
"uffcccnccnccnnncnnfnnnnncccncnnnfeCgnucnncccmmmm",
"eeeegCfCa....sw....ra.#..wv#.....BCgg#....#qqn#...#snaxqnc#...#s..dc#...#qr..."
"..dqc....wa.wtc...#l#.xCggn..qr..vw....r#.ds#.qk....wkgfC.....xd.#tp#....wr.xy"
"a.xyeeea...##.vunnc..xknm....#l#.xv..x#...dvcnm..qa..a....wv#.....qr....wa.wr."
"#d.#d#....xa.lr..ra....ra.xva...#qcnunnnccnunncnnuunguncnnnnnngnununuunncncncn"
"ugnnncnnnccncccnnnunfffnnnnncnnfgCCfuuuuncccamam",
"eeeeCgffnwxxxqfrwjxqvrwxrdtnwwxjxAgnfcwxxdqqufkwwxdtncdsgfkwwxdtrxlfkwwxdta.wx"
"jdAsnrwwxdvalvcwwwltkrqvgggaxqnmxlerwjxqawqsawiCrwwxdtgCCcxxxdqyahBepwjdwddwqt"
"rwqyCeenwwxqdxqsuncawlkncrwwxdtaahkawdrwwxqknncawqcwxdwwxxxtcwwxxjqbywwxdr#dva"
"xtajdcwwxjdwwlkwwdkrwwjqwwqscwwwldccnnnncnuugnncunuununncccnnnnnuunnnnnnncnccu"
"unnnnnfnncccnnncncnnfeCfnncnnnnnnfCnnfucncccmmmm",
"eeeeffgggCttytfCsttsnfttstkgsttstyCnnfstyysguunkttvsugCCggnftttsftskfftvvCa.jo"
"oqsfgfkttvnktknfvttkcksCeeCCtvgfvssCstvsCttffsyeCsvttkfCCCsttskeoByCebBtstpBtf"
"fstkfccunvttCsyeguncdtnccckvvvcnvtknvvnstdvnnunudvccvvktytvknfttsvybbsttvksvkk"
"tvntvnktvkvnvvnnvvkcktvknsqpnkvtvknnnnnnncnnnnunnnnnnnnccnnnnnnguuncnnnnnnunuu"
"unnnnffnnncnncnnnnnnfeeefnnnfnnnfggfnnnccnnnmamm",
"eeeCggggfCffggCnnfcngfCCnngffnnnCCCgnnfCCfggngngnugnfnggggunnffCgnfgggfgnncwdA"
"bpguncnnngfgnnnfgfnnffCeeeCfggggffCfnngcffggnfffffnnfCeCfCffgnnCbbeCCCpfngpbec"
"ncnucncncnccngCeCgunnccnnccccncccnnnncnnnnncncccccnnccnngfnuuepencCpbfggffnnnf"
"nnnnnnnnfunncnnnnnnnnnnunuebefnuncnnnnuunncnnnnnnnnnnnnncnnnnnnnnncccnnnnununn"
"nunnnnfnccnnnnnnnnnnfCCeCnnnnncnfCfnnuuuncncmmam",
"eeeegnnggggggCfgfugggCCfuffggfnffCCfungCCggnfgnfnggcngnngunnfgCCgcggCgnnfnneBB"
"beCffncnfnnncngcggnggCCCeefgggggggfggfngcgununggggnfCeeffCeCnguCbbpfnffggCbpgn"
"nnnnncccccnccuggCCffnnccncnnccnnuuuncncnunncccccncnnCgnnnuuugepfunCeCufCeCCnnu"
"nuuuunnngCnnncccnnnunnnunufeeuugnnnnnnnuncnnnnuunnnnnnnnnnnncnucnnnccccnnuuuun"
"cnnnnunfnfncnnffnnnnfffCefnnnnnnCpCcnnncnnunmamm",
"eesCnfgfgngggggguuncfeCgggggggngnnununffgfCggngnfgngnggggnuggfgggnnnnugggnfCfC"
"peCugnnnnccnnnnnnnfggCfnggfggggCfggggfugnfggggggggggepCggCeCggfgbbpguuuunebpnc"
"cnnccccmncccnnggfCpefnnnccnnccccuuncccnnnnnncccccnuepeunnuunCbeucnCeunuCeeegun"
"gnnnnnggfpgnnncncnnnnnnnncnfCguunnncnnnunnnnnnufnnccnnnguunncnnncuncnnnnnunnnn"
"nnnnnuncccnnnnCCnnnnnnnfggCfnnnfeyCccnuuunufmmmm",
"eCeCcngu.angmngcaaa.reggnggfgnguu..uncnCCeeeCgcfnngguggCgguua.aannaa##afggCC#a"
"eeumnffna.ma#a##agffCna..anngCgCggggCgfgfgggcggCgCCCeCCnffgCCucCbbpgguna#cbp##"
"cncncca.knnnggunnCebeggnnnnnnc###aa#.knnnnnnnnnccuCppeuunnugepeguuggnncuCeeCgn"
"nuunuuCCgeefncncnnnnnnncccncuufunnnncnnnnunnnnnnnnnnnngunnnnnnnunnnncnnnunncnn"
"nncccnnccccgnfCegnnnunncnufCgnugeygnunngggunmmmm",
"CCCeuuun..vC.#fm.#v#dsfcncnggfnnn.#dgnncgeppbegnfnnfucgCCCfa....rn....wtgCCn.x"
"ypu.annna.w.....#tgff..##.vgnggCnCgnCgggggngnnfCCCCnugguuggun.#spbbCggga.won.#"
"dkccnc..lfuuuuuuccCgeCgucngnuc....wawducnccuuuuccuebpennnuugppefufggununngeeCu"
"nnuungepguCgnncnnnnnnnncnccnnuuunununnnuuunnncnnnncnnugunnnunnnnnnnnnnnuunnnnn"
"nnncccccccnffCeggunnnnnnnnggugnfCegnnnnggfnnmmmm",
"CeCCnfnna.xr..ta.xd#xk#aa.anfca.#.#lka#.afc#rbrcn#aca.#nCec.#Ad.#r#.jxltffCm.l"
"spn..#nna.xvr.#xltgCu..lBdqa.kCa#raaa.#cCa#m.#aCCfa.#aug.#aaa.#rpuuegnun#.or.x"
"t#.#ana.lsc#.#ac##a.#rgc#aggfr..xddw#vm#a.#auna..#cepgunnunnCeCCggCegununuCeen"
"nnggnfebpCgfnnncccnngnnncnnunnnunugnnnnnnnfunnnnfnnnnnnnnnnnnnnnnunnnnncnunnnn"
"nnnncnncccnggeegununnfnnnnccnnngCgnnnungggncmmmm",
"eCeCnnnnc.w#..w#.lr.wk..#..rn..##.#da.##.#r.#o.wr.##.wwtCCc.#Ak.#d...#rggfga#A"
"seu...#c#.xvk.#qssuCp..#acsa.xs#.x#.##..ka..#..rC#.##.#f...r#..wv..bunnCa.x.#i"
"drr.#k#.qk..w..w...w.#sa.wtgfc..dvs#.xa..#..ka.#w..keCnnuncnggCegCpeguuggCCeeC"
"uuuunfeBbbeCgnnnncnfnnnnncnnnnunncnunnnnnufgnnunguccnnnnnnnnncnnnununncccnfnnn"
"ngnncnnncnnfCeCgnuuunnnfunncnnffuugnnnfggunfmmmm",
"CeCCnnncn#..ww..wqm.jv.#lx.wr.xqv.#x.#qtw.va.w..#.d#.wvtnfe#....wtrvx..vggn.wB"
"CCn.#w....xkc.#lCCCebk#...ra.ds#.d#.lBr.xa.xBv.#r.wqtw.t.#dqr.wqtawqpnuCn...jA"
"caw#.d#.la.xw.wl..xq#.x..lvfum....f#.da.jlw.x#.x#.xqsgnnunnnfCeefCeCugnufCCCCp"
"fuuungebbbpCgfufnnnngnnnncnunnnnnnncnnnnngnnunuugnnccnnnnnnnunuuunununnncnnnnn"
"ggnnccnnnnnCepCnngnnnfnnfnnnnnngnnnfnngfungnmmcm",
"eCeCcnnnna..qr..xta.wv.#lc.ww.dvn.#w.wtnm.xs..##.#qu#..rgnebx#..dtCys#.xfcn.xt"
"gCu..qx...xsm.#qeeeebbsd#.#r.dsa.x#.qsc.ja.lsf#.w.xqCa.d.#Byc.wBCftACgfCea..Ab"
"#.w.#xa.la..#vqv.#dkc.#.wqknuc..wwla.la.xva.x...#qqsCCnnnggCeCeCfeegunuungffeb"
"enncngeeeppeCgngunnffggnncnugfnnunnuunnngnnnggnugnnnnnnfnnnngguguunnugunnnnnnn"
"ngunnncnnnCeppCgnnnnfCffnnnffCnnfugnguuuncngmmmm",
"eeeCnnfnnm.jqn#.dsm.wv.#tc.wx.#km.#x#.xm#.ly#.dx.dqckw.wsgebf#.wqrama..dsgm.ds"
"ggc..qCr#.xtc.#ApeCCCmaca.ww.jk.#x#.xn#.xw.wka.wd.#vc..q.#qCn..vn#aeeCCeCc.wir"
".wA#.d#.qa..xxac#.dkn#..dvuunc..ltva.la.xka.l#.#dxanCCgnngepeCguepCncnnnnnugee"
"gncnnCCCggeeeCgnfgfCefnnnnunfnngnugfgnnffunfnngnnunnnnunnnnnguguuunnnuunnnnnnn"
"nufnnnnnngepppCCnnffCspffgggbfufnggggugnnnncmmmm",
"ppeCunggfc#dvcmwqka.wv.#dm.#ta.....dr....xipc#ib#As#...xvCbe#.#qta....wqkna.qk"
"gfc..qffk#xsm.#AbeeCn....#dv.....x#....wqa....#dta....dA..tCg#..k..tbCeeCc#lob"
"#....da.lf#....r..dkca.wqsnunm..lfn#.da.jva.xk#...#kCCCggCCeCnnnCpguunccnugfee"
"gccnCpegnggCeeCggguCefnnnnnunnnggguggnugfngnnnfugnunnnuunnnnnfuununnnnnnncnnnc"
"cnnnnnncnfCppeCgguggCssCgCfCeCunufggggunnnnnmmmm",
"BbbennnggncdgucrtfcwdvaxtkwddnxwxxxtkrxwdABeekAbuApcxwxqsCpfmxdtnfrxxxqtfcarqf"
"CenwxqeCfkdtnaxqbeeCCkxwxdAskjxdxd#.xjxAqa.jxxlqeCvxxdAyadqgCfxxqkdABpepCnctsp"
"kxxvxArxAgnrwxllaxlfna.dtngufcajlkuawqrwdvmwqspxjxdlCCCeeggfnunngeucncccnnngee"
"funfebpnnnfCCeeeegnCeggnunugfffgfngnugnnnunnnngfguuunnuunnnunnfgunnnnnnnnnnnnc"
"ccfnncncnffepCCCfggCCCeCCgCfgunnnnggCguuuuncmmmm",
"boBpgnguuncknncfknfktkfvsnfvsgfsttssCfsytsepeepppbbpBBtvfebenstkugCsstsggfftsg"
"CeCftyCCfgCCCeqyeCeeeesyttCCeyyyys..lyyypa.xtsyCCCCsyyyeeytCCCfsyCssppeeCnusfC"
"ebytsypyysgnvvvsfstkc.#qsggCnufvtnnnvvnkvknktypesvvffffCefnnnnncnunuuncccnnufe"
"pCgCppCgnnnnCeeppCunnuuunnnnggggfgffgunnnunnnnfgggugggnugffuggfngnfnffnnnnnnnu"
"nnnnnnnnnfCeefnggffffeCCfCCgnunnnnnnfgguguunmmmm",
"bbbpggnfnnnnnnnncgnfngcnngufnngfgffCeffCfCebbegfCeeepbeCCbbegugggfCffcnnggggff"
"CCCCCCCCggffCeeCCCCebeCCCgfCepCCCpmxqCCCerrqsgCCCCCebpCCeCCCfggfffCeeeeCggCfCf"
"fCeCfeCCeefkngfgfnnfcadlungCgnunnccncnncnnncCpefnfgnnggffunnnnccuuuncncnnncnug"
"eeeepCunnnnnffCeppfnnugugnnnnggggngggfnnnufnnngnuggnnnggggnnggnnunuuffncnfunuf"
"guunffnnfCeCfunncgnngCCCCeeCfnnnnnnnnggnunucmmmm",
"ppppgfunnnnngnfnunncnnnnguggggggeggCCgfgfCpbbeggfCCCebbCCbbCuggfgggugfffgCfggC"
"gfCCCCCCCCgCCeeCCfCbopefCCCepeCCCeetsfffCpytfffCCCCebbeeCCCCCfgggCCCCfffgfgCCg"
"ngCCCeeCppCgggggnunufstsccuggunnccccnncccnnfepguuunnnnnnnnnnuuncuunncuuuucccnn"
"gCepbCfnnnnngfeeeeennguuggnunnngggggggnunguffnnffngnfgnugfungngugugggugnuuugnn"
"unugffngfCCgfnnnggngCCCCeCCCncnncnnnfgggugunmmmm",
"eeeegufnnnnncnnncnnnnnncncnnnuufgCcfgggnufebbengffCeeeeepbegggnuggfgggggfCCCgf"
"fCCCCfCCCCgfCCCCCeeooBefCCCCpeCCCCCCCCCCCeeCgggffCCpobefCCCfgggfCCCCCgguggggnu"
"gufffCffepfgeCnunuggggnnnnngcccccnnnncnnnnCepCuuununnnfnnuunnunuffncununcccccu"
"ngeppeCfnncnngCeCCeCgguggggunffgugfCCCgfgfggfgngufnngnnfuuggnnnnunguugfggnngng"
"nunngfgfggnungnggggufCCCCffffunncnnnnCgugnnnmmmm",
"eepbggfgnca..afa.rcmnnnua.m#####annnfca#.#CbbCnggfCeeCepbbeggm.aCgggggggccfCCg"
"gCCCCCCCCCffCCCCCepBBbefCCeecceeeeCCfgCfCebeCfffffcnbeCncffCgggCCCepCggfgfCga."
"kgggfgugCCCfeeCungnnuuuunnca...accnnnnccggccenunnuuuunggunnnuunuCCCnnnnncccccu"
"unCppeCCfnccnfCCggCefCunngngggggCeeepppeeeCCfguggfnnnggnnfgffffgggfnuuggnfnfgn"
"fugnnngCCggnnfnnfgugCeCfgguuggunnnnngCCufggnmmmm",
"epBofgnnn#..##v#.xr.wgun..w.....wtnfga..#.deem#ufgCen#kbbpCffa.wtnfucfCf..sCgC"
"fnCCCnffCfugfCCfffCyypgcfCCr.wsCeefufffcfCpegCgggCa#peCa#sCCncfCCebnCfguccfC.."
"lkufgnumngCcgpncccgucuufuu...#..rknncccnCn.#sguucunnnnnggnunnnnnCeeCCncnnccccn"
"nnCpCgfCefnnnnCCfngCeeeeCguuggfCyyByybeeeeCCCgfgfggffggnfggngnnfgfnnfggnnfngff"
"gugnnngCfgfnnngngunfCeffggguuunnnnnnCgggnguummmm",
"ppboCncfa.#dddda.dr..auu..dvw.#lltggm..dqdqeea.vgfgCu.xBpCggga.wv.a#.aCa..#Cfa"
"..#ng.aam#aa.#nCa.awbr..#mn#.#rCn#..aga.aaergCgCffa.den..vfc..#cCa..wfg...wC#."
"#.#mgc..#mn###aa.kg.akgnga.#lqddqsm#..acg#.#wuc#..amnnfCunnnnccnCeepbgncnncncn"
"nnCefnnfeefnnnCgnnngCyebbpCgCeeytByBpeeeeeeCCgfgCCCgugggnnnfgngggfnnngnfnnfngn"
"nnnnnffgCCnunfnngngCeeCgCfufngnfnnggCCfnnngnmmmm",
"ppBbfnnna.xlsfk#.xr...#k..lsr.wtsggCa.wqsfsraa.wwccaa.#rmgggfa.wv..a..ra..#ta."
"ww.#r..#d..##.#s...dr.#r..w...xs..r#.wa..wr.asCCCu..#ya..dCmrw.#s.#rxtnmx#.va."
"##.#krmx.#r..#x#.tu.#tugu..dtaaaac#.##.#r#..wv..##.#kfgCfnnnnncnCeCebbgunncccn"
"unfenccnfeefnngnnnnneyBBBpeeeepyyybpCCCgffeCCCCgCCggCgggcggnfnnngggunfnnnfnfnn"
"gnnnnngufggnfnnnuunCsegfCgngnnnnfnnfffgffucnmmmm",
"ppbbgunc..xsnnc#.xr.#j.#..lfa.wtggffa.xvcnC##....xa#..#.wsfgca.jr.wqw.xk#.qq.#"
"x#.dd.#qt.#qqw.xa.di#.x#.xBr.wqr.ww.wq#.xqv#dtCCCc...w...jsraw#.d..wvsuawa.x#."
"dt#.dc#a#.v..qt.#qf.#lgun.#dk...#r.wqtw.vm.wqr.wqtw.vgCCfnnnncnfebCgeppgnncccn"
"nugegccnnfCeCuunnnnfCyBbpeeCppeepeCgugpCgfCCCeeCfgffggggnfggggfgnunngnfnnfgnfn"
"guufngggfgfgnfngCfnCeCgfgggnfnggnfngCeggggugmmmm",
"ppbpeeCna.wknnc#.xr.#Bw...lsm.wtCCCea.#vgcfpox.dqtssd.xAqtggga.wv.wta.jv..qf.."
".wqqk.wBn.#Bea.w#.ls...#tAtr.jtm..#xqta.dyCsqyCCCa.x#..w##r.#w.#lr#..k#.##.da."
"ds#.d.#w..x.#qn#.qg.#tggu#.wsnx.ww.xtna.dr.wtm.jtfa.xsfuggnnnnngCegnfCeennccnu"
"unfCfnncnnfCeCgnnnnnfpbeCggfCCCgCCgunCbeggfCfCefgfuufgggfggfcnncfngfnfngugcfug"
"ggfgugfCeCpCfggCeeCCCfnuugnnnngnngnCpeCCCgucmmmm",
"ppByebpCc..wmac#.dr.#qfr..lfa.wtCepef..#manpBa.lkfnnc.dofgCCCa.wv.jta.ws#.xna."
"wdrmn.wtu..xc..d#.tea.#dxaCr.#vc..xvana.dsc.mCCffa.lw.wq#.w.xv#.tcvw.x.#qw.d#."
"lf..w.wd#.d.#qn#.xa.wlgufc..ama.#x..rm..lr..xm..rm..qynnnffnnnnfCegnnfgggnnnnn"
"unufnnunnnnfebeeCfnuuCeCunnnnngguggnugeeggfgCCCggggunufgfggnnngggggfgngggngggg"
"ngggguCeppseCgCCpypCgnugngfffgfnggCyypeeggufmmmm",
"ppBbebbpfr....v..dr..tgfk#lsa.wtfCpeCk#...vsbbvqfffeerABbeCCCa.wr.wta.wta..vn#"
"...wv.wtn.....rq..lsf#...#sf#.#sr....v#.xsm.wsffc..qf#dta.x..#..d...#qa....d#."
"lg#.d#.#..x..qga....#tunufr#....wtr....xqC#..sr....xisunngCnnnngepfnnnnnfeCnnn"
"unnuugnncnngCppppeCfCggugggfnfufnggguggCgfggffggCgggggggngnffnggfgfgufnfunnngu"
"ugugngCppyyCfCCsyyBeggnnnggCsBpeCCyyyCCsenugmmmm",
"ppBoeebbCfkxjxqmrdrrdqgnfklfcwltfgCCffkxxxqsbbbsgnCebbyebbpeecwdvadtcwdtfrxqsC"
"xxxqtrdBu.#dxdqvmxqsffxxxlqCnxdqCvxxdqrrdsfrqtgffrxqsuBscvlvxhvdqkxxlqurxdxqrx"
"qsmxquxxdxlrdqfnrxdxdqggngcrxxxxqterxxdqvgnxxqgrxxlAygnnnfCgnnnCbpfnnncnnCpgnn"
"uunnugfnnnnnueeppeeeCggnnCCfgfnnffgnfnnngugggffgffggCgfggnggnfngugggcnngfnnuun"
"fngggngeCCeCCCsyBbeeCgngngCsyypeCCyypffsegugmmmm",
"ybbbeCppegfkssvnsvCstscgngCCfCvsgfCfggnfssvCebeCggCebbeCebbeCfstsftffgtCggssff"
"CsysCftsu.#qstsggssCgggsvsgfCsssfCstssnstkufsfggCeyyCCeCfsyCeyyssesytCfCssssCs"
"yCCysCsyssyCtsggfktsysngnfgfkksvsfCgkvsknnugvscfsvssggunfggfunnCbpgnncnnnCCgnn"
"gunnnuunnnfnunfCCCeepefgnfCCeCfnnnnnnfnuunfuguggggggfgggfucfngfgggggnnggugffnn"
"nnggunffCeeppeyyypCeCfnggCesyspefCCeCungCgucmmmm",
"pbyopCCCfgCCfggggCCCfugngggCffgggfgggngggfffebeeCfCeppfgCebbefgfnffgfgfnfggugC"
"fggfgggCfrdtfgngggCfgggggggCeefggCffgggnnfggCCCCCeeefffgCCCfCCCfCCeffgCfCCCfCC"
"CCfggCCffCCgfuggngfgCnnngugnfgcnfgfgngcnfngncnufngCgnnngngggugfCbbgnnnnnnngggf"
"nuncnugnfgugngfnuufCppeCufggCCfnfnnnffgunungcgnggggggggggggffgggcgCffffnggfgnf"
"nngfuuggfCyyyeeeseCCCfCCCsssCCuunggfgguggfunmmmm",
"pppbeCCCCCfCCCgggCffgggggfffCggggggcggggCgggCpbpeCCpeeCfffebbCgggggggggggggCfg"
"ggfCgCCfCCtsgCggCfgCgCggfcfCeeCgfgCCCCgfggffCeCfCepegggffCCgCCfgfCCgggCffCgfCC"
"CggggfgggfCgugugucgfngnnufggnfgcnncfnngnngugugnuggffnnngffggguuCbbCnnnnnnnueCg"
"ggfnnnugugnguugngggCeebegnnngCgfnnnnuggunnfgngnggfgnggggggguggfggffggnggnggfug"
"fngguggfCsByeeCCeCCfCCCCsyeCggfngggCfgnnnguummmm",
"eeepeCfgCCfgCeCffgCggnufggCgCffgggggnfggggcggpbbpCCCeCCggfCpbeCfggggggnggCCggg"
"gggggCeCffCgnggggggggfggggfepeCCfCgCCCggggggCegCfCeCggggfCCCfgfgCCfgffgCCCfcff"
"fgggggggggnggcgugugfgnnnnnfggguffngnnnnfgcggufggfggcnnfnggfgCgnCppCnnnnnnngCCg"
"ungnnnuuguuggngfunnggCpbeffnnngfnfcfgffnnnnngugnggngcfgggCgggCfgggguggcgunnngn"
"nggCgugCCyBpguCCffgfnCCCCeegfguugeCgCguuuggnmmmm",
"ppppeCgfegCffCCCgfgCgggggggggCgfffgnggggfngnfebppeeCCeCgggfepbpCggggffcgffCggf"
"CCCfgCCCggggggfCfgfggggfgCCebegggfffCCgggCgfffffgfCfCgggfCCfgCgfCgfCCCgfCCgggg"
"gfgggggggngunnggggggnnnnfcgnnngnngnfcnngnuguggggCCgnncgugCCCCugCeCfnnfufgCCfgu"
"uggunnunnuggnuggfgggngebbCggggggfnnnggnnunngcguggggfggfCfgggfggggggcfngnfucnnc"
"gfCCgfgCCsyegggfggggffCCCCggggngsyegCCggggggmmmm",
"byppeCCCCCggCCCCeeCffCgCggfgggggnffgggggfgnngepeebeffCeeCnngepbCfCggggnggggggg"
"fCCffCCCCCfgggggggCCfCCgfCCebeCcggCfffgggggCgggugfgCeCfggCCCfgCCCggCCCCffCggnn"
"ggcfgcnnggfnggggffncnnnuufnnfgnnnnfnnnnngggfgfgCgCnnugfnfgCCfCeeCguuggugCegnug"
"uuunnnnnnugugnugngnnnnCepegfgfggfngfncnnugnnnfugngnggggcgfggggggggggngnnfnnnnn"
"gffCgffCCCeCnggggfgpeffCCCfgggggyyCfCCCggggnmmmm",
"bbppeeCCfCfCfffCepCggfCgCggggggggggfncgfgfnngCeepbCggCebCgfgCeppggfggggcgggggg"
"CfCggffCggggggfugfgCCfCfgfCebpCgfggggggggggggCggggfCeeCgfCCggfCCCCCCCCCCgfgffc"
"nfnnfgggggggufggugnngngguugnngncnnnnnnnfngugugffCggngngfgCCfCeppfnnngnggCegugf"
"gnnnnnnnnnnggCuugnnnnnfgepCuuugfgguggnnuguunnggggngCCCuuugnggfgffnggfnnnngnunf"
"gggfggggngCggggnfgeyeCCffCCCseeyBefugfCCunggmmmm",
"eeeeCCCffgggggfgepegggfggggggggggggggnnfnfgnnCeebpCfngebegfgfCeeCggCffgffgCfgg"
"gggggfgfgfcfgggffggCCfgCgCfCeeCgfggggggfgggggCCggggCpbpeCfCCgffCCCCCCCfggfgnng"
"nngggngggggggffugfgnugfggugnfngnnnnngngnnggfgggnugugnfgcgfggCppefnfnfngCCguguu"
"gununcncnnnnggununnnnnnfCpefcnnugfgfggggnunnnnfnggfCCCgfngggggugnnnggffcnngugn"
"gggCCCgggngggggggfesCfggCCeCeyyyyegnnCCCggugmmcm",
"eeeeCCCCgggggggfCCeCCggggggggggggggffnggfgcnffCepefuggepCgnggfCeCCCCCgCggggfgC"
"ggfgggggCfngfCgCgfCggCgCCCCCCCCCCCggfggfgggggfCggfnfCbbbeCfgcgffCCCCffgfgnfngn"
"gggggggggggggggufguuggggunnnnnnnunnnuguggngngugggugnfgngCCfCeeCCgnnngfCCgggfnu"
"guunnncnnnnnggunnnnnnnfCCeyCgnuguugggggnnunnfgcggffCCCggcgggggguggggfnugnunggg"
"ggCCCCfungggfgggfgeefuffCCCCCesyBegunCeCgnCCmcmm",
"eepeCCCCCfgggggfffeCfgggcfcfgfggnggggggnnnfnnfCeeCguggCCegfgCffCCCCCggfgCgfggf"
"ggggggggggfggfgCgggfCCeCCCCfCCCffgggggfggCfggggggggfCebppeCgggffffCfggggggcgng"
"nggggggfggfgggnguggugununnungnununnngffgffgggggngnggggnfCeCfCCfggffngfeeCngnng"
"ggggnnnnnnnnnnuunnnnnngeCCppCfuggggugggngunfcngnngfCeCegufcnngggggfugfgfffggng"
"fgCeCCgfufnuuguguCCfgguffffgCggeeCufffCguggscmmc",
"eeeeCCfCCggfCCCgggfgggffgngcfcggggcffcgfnnnnfgCeeCggffCCCfgggggfffCCCCCCgggggg"
"ggggfCCggggggggggCCCCepeeeeCCCCCCCgfCCgfgCfggfgggfngCCeeeebpeCngfffgggggfggnfn"
"fnufggggCguggugufngnnugugggugfnngnnnuggggcgggfgfgnggfnngepCggCCggCguuCeegggggg"
"gggCgncncnnnnnfnnnnnunfCCgCpeCgngngnnnnfnnnngnfggnfCeeCCfgngngfggggfnnnnnnfggg"
"gCeeCCgggnnfffffffffffguggggCCgCCfgggCCCgfCscmmm",
"eeeeCfffCfgCCCgggggggggnnggnnnnfgnnngfnffnfngfCeCCfggffCCCffgCfggfffCCCCCfgufg"
"ggggggCfggggggggfCCCCeeeeeeCCCfffgCggCCCgCggfggggggfCeefgebbpCggggfgcgfggnfnfc"
"nfngngggfgnuugngcgnuugnggfgfgnungggfggfgggfggggfCffgffggeeCgfCCCgggggfCfggfggg"
"CCgCCffnnnnnncnnnngnnnfCfggCeeCgngguncnnfnfgnfnfngnCyeCCCfnfcgnfgggggfgnfgcgnf"
"fCeeCfggugugCggnfgguuufffuffCCgggfggfCfgggCfccmm",
"eCeeCgCCCCfCCCggggfgggfffngfnncgfgngnncgcfnfngfCCfgggggfCgggfgggfggfCCCCCffgCf"
"gfggfgggggfggfCgfCCCCCCCeeeCCCCgguggffCCCfgCgfggggffCeCggCbbbCgggggfgcggffgfng"
"nggCgggngggggugngnngfuggngnnnuununfucggggfgggnggCCgCggffCCCfCCCCggggfgfgggCCgf"
"CCCCCgnfnncnnnnfnfnnnfgfgunnCeeggggfngfcfngngcgggggCsCggCgfgngggggggfgcgnngngg"
"fCeefngfguggfCfugfuggfgggfgCCggggugngCCggfCCcmmm",
"eeeefgCeefgfffggngggfgggngngnnngnfnnfggngngfggffgggfgfgffgggggggggggCfCCCgffgg"
"gggfggCCfgCgfCgfgfCfCfffCCCffCCCCCCfgggCfCgufggcfggfCCgffCeeCCnggggggnggngnggf"
"fgCCfgngggggggfufnngugfngcnnngngnuuggnnggfgggggfgCfeCgCfCfggfCCfnffCegggfggCCf"
"epeggCgfnfnnnnnnnnnnggCguggngCegfgnfgnnufnfnggnggnfCCeffgCCggnggngggfgfuggfnfg"
"epeCCfgggfggggufggffufffuffffffngggufgfgCeeecmmm",
"eeeegffCCCgggggggncggggffnfffngcfngfnngnngggfngggCfgggggggggcggggfCffffCgggnfu"
"ggfugfgCCfCCfgCCfCfffffCCfffCCeCfCgCgfCCCCfCggfgggggfCfggCCCCeggfgggggcgggfggg"
"gCCCgggggggggfuguggugugugnnnnnfnnnnnfnngggggggggggCCfgCCCCgfgfCgcgCCeCgggfCCCg"
"CepCCCfgfggfnnnnfnfnnCggfgggngeCgcfgfggngngngffngfgfCegufCefgggggngggggffngggC"
"ypCfCCggggfgfffgfffgggggfgggfggggfgugngCeeesmmmm",
"eeeegggfunggcfcncnnnggggcmmffngnfnngfgnfnmmgcgggfgCfgggggCfgfnccuggCgCCCfgggCf"
"fggffgCCfggCgcnCncCCggfffCCfCeeCCCfgCCfgfggfCgggCfggfgggggffepCngfggggnncgfggC"
"ncfgfgcfgngggggnfgngcgngfnnfggfgguunncnnggggggugCCCeCggCfCgggfCCgggCCCfggfffCC"
"eepeeCfgugggggffgnnnfgfnufgnnfCeCguungfggufnngnfngnfCegngCeeCfgggggggggggfgcCt"
"ByCfgffCCCCfgffggffffffffffggfffgfgfgffCsseecccm",
"Ceeeggfg.akCmcgn.#kcggfnm.#ggfnnnncfnnnnn.#knmmngCgggggggfgCgfa.aCgfgfmcggfmcC"
"gggCgfggCfgfc.kC#asggfgggCffCCefffgfCCmcfgfgggCfgCffgggggCggebCgfgggfgnfggnnfC"
"#.rfCCggggngggfgggfngggggungCCggnnfnngfcfcggggffCCCCgnffCCCfCCCegfCCCfggggCCCC"
"eeyeepeCffCCggCggnfncfunnggnnnfeeCfuuggggfgngncnnnngfggnnfCeCgggCCfngcnngguuCB"
"AbCgggfCeCggfffgc..#ugfffgc..#ugfa..cuCeCeCCmmmc",
"eCeefggg..df.#sm.wtfcmnnm.wvmnfnfggnnmcnnaxtf.#sgfgccfggggCggga.xvcggc.#sgm.ws"
"fcnucggufggga.ls.wtmucggfcnCeCggccgCCc.asCgfgggncugggnmnfgcnCnucuccnffngnfcmcC"
".#dkcgffggggggggggfggnfgunugCCffnfnngnnnnfnfcgnCeCCCggggfggCCCCCCffCCfgggCeCfC"
"CepCeppCgfggggfCgnnnggfnngunnggeeeCgnuguguuunnnnc#annm.cgngCCfggCggfngc.afgfsA"
"AbCngugCCCfgfufu.#m..ffgfu.#m..fm.aa.cCCCCCCmccc",
"eeCCggfCc.xr..da.xt#...ca....#cnnfnc...mn##va..wnua...cgacfCgfa....afa..wc...r"
"u.a...ngcacfa#qc.dw.##nm...aeCc...#cn...wgCggna...rfa...au.#.aa.#..cggfgca...k"
"#....rCgggfgggggngggffnggunngCggngfgngfnnnffngffCfffgggfgfgCfCeCCCgCfngffCeCgf"
"fCCgCeegggggfggnnnungCguunfnnnggCCegnnnnuunnnnncc..vn..xsucnggngggnnnunaxtguCq"
"AyCununfgfgfgggc#nfa.ffggc#cfa.gkmga.mffgffgmmmm",
"eeeCggfgn.#...###l#.rw.#r..ww.#unffa.rwqk..da..wta.ww.#m.#kfgfm.#w..va..wv#..x"
"v..rw.#k..rn.wqa.qa..rv.#w#.wC..ww.#ka..xtCCga.#wwdr.ax..r..#x#.w#.wgggna.#wwt"
"#.#w.#sgggggfggcfggggggngguffCggggguugnfngnggngfggggCggggffgCffgCCfgggggffCCgu"
"ffCfgggfgfggnnfcnnnnfeguugunnfgungeefnnnnnnnnnnnnm.xk.#qw..arc.a#ca.#mu##sna#."
"#nCa#a.#ngmcfggfufu.agffgfggu.afggw#aggggfgncmcm",
"eCCegggfga..xw..wd..x.#lx.xqt#.vgnnm.#rvn#.qn.wqv..x.#dqaxqgfCa.jBw.df.wqtr.xA"
"r.wqtw.xkwqk.ds#aqa.dq#.dqy#.x.rqtw.vr.wqyCCC..qqyt..x.#dl.#qd#.lt.#tgfn.#lqtB"
"..dt#.lcgCCgggngngfggfnfggggggggfgggfgngngggcfnggggffCggggCCfggfgfngfncgggfgng"
"ggfggfnuCCCggfgunnnngCgunuggngggnfgegunnnnnncnnnnc.#a.dr.#w..a..wr.#wdk..ta.#w"
".#s..##.rr.#uffgfu..cfgfgfug..cgfgm#.kggfgngmccc",
"eeeefgggea.#qu..dv..#rqtc.jsca.dkcfnw#.#u.#tu.#qc..#rqqCntsgCCm.wta.dv.#tna.wB"
"m.wqfa.dCktm.ls.rqa.dsa.dsC..x.jtfa.dr.wtCefe..qsCC#..wtqk.#qn..qn.#qunn.#dfCC"
".#ds..qCfggCCggnngggggggcgggnggggfgggggggfgggfgfgnngfgfgggfCCggfgfcgfgngnngggn"
"gggggnufgCCfnfunnnnnugfuuuguufguufgCfnnnnnnnnncnnna..#q#.x.#dx.wqr.#wvk.#l.#ii"
"x.d.#dv.#v#xfgffu..cgggfffu..cggggfn.aggfggCcccc",
"CCeegfngCn.xlg##lsa.#x#mn..wa..lkngcmr.#t.#lf..wn#.#xarn.agCCem.xta.dk..wnc.#r"
"r..ra.#d##ra#qk.dya.dfm.#ra.wl..ra..qk..rn##ba.wrmfa.#xwac..qn#.lu.#x.afa.wmaf"
"#.dC..qgggfCCfgfgcggggfgggCgungugggggggnfgfggCCgfgcggggfnfgCCfgggnggggfffgngff"
"fgCfggggCCCgfgugnnnugnunnnugugfuuguuuuncnnnnnnnnnnm..xd...wtqa.wtnw#.#n.#d.#iA"
"r.d.#Bk.#qcdufufa.kgggffffa.kggg.#gu.afggCfgmccc",
"CeCCnggfgualsgmwtnc#...wsm....dqnnga...xt..qga..vn#...ws.wtCCea.wva.xsa..vf#.w"
"r.....dta.v.wqa.qCa.lsfw...#qqc....dqfa.#o.#Apw...rfa...#v..qu..ln.wv.#tn#...r"
"..ls..qfCfgCCCgngffgggfgffCCfnggggfggnugnggggfCgfgggfuggngffCgggnngggugnuggggC"
"gfgCgufngffggfunnnnggguunnunguuguunnnnnnnnnnnnncnnn#.qsa.#d#mm.wtnmr.#v..qa.xr"
"#.l..qn.#v.augfm.....fa.gc.....fa....kgfggCgmcmm",
"eCCCggfgggntsffktffkxxlqtnkdxdqknncnvxdqvmdqffvdqCkvdqqyuqtCCenrqtcrqsfvlqgnvl"
"d.wddqqfndqrdtcvqCcrqggfvddqBCfkddqqsncvdibqqppvddqsfvxdqtklqncdqsmltkqqgnvddq"
"kdqecdqCgCCCfgffgggfCCgggCCCngggggunguggngncfggggnfggCggnnnggfgffnngggugfgggge"
"eCgfgngufugCCgnnnnngggucnnnuuuggnnncnnnncnnnnnnnuuumrqnn#...wr.wtm...xd.#qn#.."
".dq.#Ac.#d.wfggaa.aaagaagaaaaaaggmaakgCgCfugcmmc",
"eeCCnggnfngnggggkgcungkkngfkgkkfcnfnfkskgcskgggssfgCsypeCCufCCfksfnsvgngssgufs"
"r.wBssCkfggusCCssffssgggggssfgfggssgcgnfyBeCsCCboysCgfssugCyCgfysCCssfCggggsss"
"fysCeysCCCCffggggggCfgCCgCCggfgggggguugngfggnfcnngfgggfguggggcgnnnnfgugggCuuCp"
"pgunCCunnggCeefufnngnuunncungfunnnnunnnnnnnnnnnnngncvkngnvxlqvrqtCvxdqvcdqgfdd"
"qqscdqnrqquqCggffCgggCfgCgfgggCggggCsggfggffmcmm",
"CCeCunncnggggfcffnggngggnfgnncnngfnngfcfnncgfncgggfggCCCCggfCggfnfncgCCggggggf"
"frltgCggggfgffCfCgggCCggggfCCggfncfgggffCeCCCffCbbpCgnggCCgggggCeeeCgggfCfggfC"
"CCCCCCeeeeCgggggfCCfgCCCfffCCgggfggngnguguggngngngngggggnfnngncgfngcgfngggnnCp"
"efunCeCucnfCepggngugngnunuugngunnunnunnnnnnnnnnnnncncgnggngscnksCeCgvkfcsCggfs"
"sggCssgfsggkffffgfggggfgfffgCCggggggsCCgfCCummcm",
"CeCefnugnfgggggnngfgfcfcnnnnnnnnnnncgggnnnfgggffggggggfCfnggfggggnnffggggggggg"
"CeyfggCfnggCCCCCgCfgCefgfCCCCfggggfgfggCCffCCfcCbbpCCgCCCCggCggCepeCfgggCCggfC"
"eeeeCepeCeCCCCgggCCgffCCCgfgggCCgggggugfnggCgnfnfggggcgugggfgggnggguunggfgunCb"
"efnngpegnnfCepCffufnnnggnguugnuunguuugnnnnnncnnnnnnnnnfnfncngcnnfefcnggnuCgggg"
"fspCCCgfugCgugunuggffCgCfggfssCfffgCsCCCspeCcmmm",
"CCCeuggfgggggggfgfgfngnggcccnnnnnnnggfnnnnggfggCggfggfgggggggggggfgggfgggggggg"
"feeCfggggfCCCfgfggfCCCggfCCeeCgggcgggggCfugffngfepeCCCCCfggfCCfCeppeCgggCCggfC"
"CeCfCeeeeeCCCCgfCggfgCCgCgCggfCgCgfgggggfufffgcggggffgnggfCCggnfgfgfgggnggnnCb"
"pgnngCegnnnnfCegnunnnnfnfnngguggnnngnnnnncnnnnnnnnnnncgnnnnnugnnfegnnfnggggfcf"
"CspCfCgugCffuffgguffCCCfgfggCCggffCpCeesyyefmmcc",
"eeeegggfgggggfgggngnnnnnnnnncnncnnnnfCfffgggggggggggCggCgcfggggggCggggggfgCgeg"
"gebCggggCffCCfgggfgCCCfngfCebeggngfgcnfCgfgggggfCpefCCCCCfgCCCfCCeeeCfgCCffCfC"
"CCfCCCCeeCeCCCfgfggggffgCCfggCfCCgggggggnggguugfggcggngggfgCCggggggCuuggunufeb"
"bCugfgggnnnnCCCfuunnnuuunnfgnngnnnnunnnnnnnnncnnnnnnnngnnnnnnnugfggnnnffgggufC"
"syCfgfggggggggugggfffCCfgfuggggggCptyeeqBypfmcmm",
"Cffmcccccccccccccccccccccccmmcmccmcccnncfnnnccncccnccccnnncnccccnncnnncncncnnc"
"nCefnccccncfgnccncncnucccnnCeCnncccccccnnncccccnCefnffnccccnnfnfCCCfnncnnnnnnn"
"ncnnnnCCffffnnncnccncccccgcccnncncccccccccccccccnccccccnncnccnncccccccccccccge"
"pnnncmccccmccnncccccccccmcmcccccmcmcmcmmmmmmmcmmccmcmnncmmcccccccccccccncccccC"
"CCnnccccccccccccncccnnccccccccnccnCyeCCssegucmcm",
"ggcmccccccccmmcccccccmmccmcccccccnccccCCfnfgnccccccnncnCCnccccccnnnncnnffgnncc"
"cfepgfnnnnnncnnnfgnnfncccnnfeCnncccncccnfgcccncnCeffcnnnnnccgfffCeCfngnncccccn"
"nccncfCeCfCncnnnnnccncccncncccnfnnncnncccccnncccccccccccccnnncccmcmcmcmccmcngC"
"CnnncccccmccccccccccmcmcccmccccccmcmcmcmcccmcmmcmccccccccmcmcccmcmmcmccnfncccC"
"CencccccccncccccccccncnccccccccccnseCCCeeeecncmm",
"fcmmcccccccmccccccmccmccccccmmcccccccngCgfgfncccccnncnnfCccccccnnnnnnnngnffnnc"
"cfCpggnncnnngnnugfnnfnncnnnfpCncccnccccnffnccccnCeCgnfnnnnccfggfCeCfffnnccnnnn"
"ccnnnnCCCfCnnnnnnnnccccnnnccccnnnfnnccccccnfcccccccmcccccnnnccccccccccccccccgC"
"CfnccmccmccccccccmccccccmcmcccccccmcmcmcmmmmcmcmccmcmcncmmccccmccmcccccfgccmnC"
"CennccccccnccccccccccnnccccccccccnCseCseeeegncmm"
};
