./makeoneimage.sh ellipse       ../../tutorials/graphics     $1 $2
./makeoneimage.sh piechart      ../../tutorials/graphics     $1 $2
./makeoneimage.sh arrow         ../../tutorials/graphics     $1 $2
./makeoneimage.sh crown         ../../tutorials/graphics     $1 $2
./makeoneimage.sh feynman       ../../tutorials/graphics     $1 $2
./makeoneimage.sh diamond       ../../tutorials/graphics     $1 $2
./makeoneimage.sh gaxis         ../../tutorials/graphics     $1 $2
./makeoneimage.sh gaxis2        ../../tutorials/graphics     $1 $2
./makeoneimage.sh latex         ../../tutorials/graphics     $1 $2
./makeoneimage.sh latex2        ../../tutorials/graphics     $1 $2
./makeoneimage.sh latex3        ../../tutorials/graphics     $1 $2
./makeoneimage.sh tmathtext     ../../tutorials/graphics     $1 $2
./makeoneimage.sh tmathtext2    ../../tutorials/graphics     $1 $2
./makeoneimage.sh pavetext      ../../tutorials/graphics     $1 $2
./makeoneimage.sh timeonaxis    ../../tutorials/graphs       $1 $2
./makeoneimage.sh timeonaxis2   ../../tutorials/graphs       $1 $2
./makeoneimage.sh graphpolar2   ../../tutorials/graphs       $1 $2
./makeoneimage.sh graphpolar3   ../../tutorials/graphs       $1 $2
./makeoneimage.sh polyline      ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh legend1       ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh legend2       ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh legend3       ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh greekletters  ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh mathsymbols   ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh subsupscript  ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh subsupscript2 ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh fractions     ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh splitline     ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh roots         ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh accents       ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh slash         ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh bars          ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh style         ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh alignment     ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh kerning       ../../graf2d/graf/doc/macros $1 $2
./makeoneimage.sh itbold        ../../graf2d/graf/doc/macros $1 $2

# Clean up local directory
rm c1.gif *.ps *.eps *.jpg *.png
