version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  apt_packages:
    - clang-16
    - cmake
    - libclang-16-dev
    - llvm-16-dev
    - llvm-16-tools
