version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - clang-13
    - cmake
    - libclang-13-dev
    - llvm-13-dev
    - llvm-13-tools