version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  apt_packages:
    - clang-18
    - cmake
    - libclang-18-dev
    - llvm-18-dev
    - llvm-18-tools
