all: tests
test: tests

SUBDIRS = arrayobject bigevent namespacedict newdelete \
	multipleInherit evolution references fakeClass tree treeForeign \
	longlong const newClassDef tclass rootcint rootcint/stl set heritstl \
	abstractclass


include ../Rules.mk



