#include "h1analysisTreeReader.h"
#include "TTreeReader.h"
#include "TTreeReaderValue.h"
#include "TTreeReaderArray.h"


Bool_t h1analysisTreeReader::Process(Long64_t /*entry*/){
	return true;
}

void h1analysisTreeReader::SlaveBegin(TTree *myTree){
	myTreeReader = new TTreeReader(myTree);

	nrun		= new TTreeReaderValue<Int_t>    (*myTreeReader, "nrun"    );
	nevent		= new TTreeReaderValue<Int_t>    (*myTreeReader, "nevent"  );
	nentry		= new TTreeReaderValue<Int_t>    (*myTreeReader, "nentry"  );
	trelem		= new TTreeReaderArray<UChar_t>  (*myTreeReader, "trelem"  );
	subtr		= new TTreeReaderArray<UChar_t>  (*myTreeReader, "subtr"   );
	rawtr		= new TTreeReaderArray<UChar_t>  (*myTreeReader, "rawtr"   );
	L4subtr		= new TTreeReaderArray<UChar_t>  (*myTreeReader, "L4subtr" );
	L5class		= new TTreeReaderArray<UChar_t>  (*myTreeReader, "L5class" );
	E33			= new TTreeReaderValue<Float_t>  (*myTreeReader, "E33"     );
	de33		= new TTreeReaderValue<Float_t>  (*myTreeReader, "de33"    );
	x33			= new TTreeReaderValue<Float_t>  (*myTreeReader, "x33"     );
	dx33		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dx33"    );
	y33			= new TTreeReaderValue<Float_t>  (*myTreeReader, "y33"     );
	dy33		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dy33"    );
	E44			= new TTreeReaderValue<Float_t>  (*myTreeReader, "E44"     );
	de44		= new TTreeReaderValue<Float_t>  (*myTreeReader, "de44"    );
	x44			= new TTreeReaderValue<Float_t>  (*myTreeReader, "x44"     );
	dx44		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dx44"    );
	y44			= new TTreeReaderValue<Float_t>  (*myTreeReader, "y44"     );
	dy44		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dy44"    );
	Ept			= new TTreeReaderValue<Float_t>  (*myTreeReader, "Ept"     );
	dept		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dept"    );
	xpt			= new TTreeReaderValue<Float_t>  (*myTreeReader, "xpt"     );
	dxpt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dxpt"    );
	ypt			= new TTreeReaderValue<Float_t>  (*myTreeReader, "ypt"     );
	dypt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dypt"    );
	pelec		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pelec"   );
	flagelec	= new TTreeReaderValue<Int_t>    (*myTreeReader, "flagelec");
	xeelec		= new TTreeReaderValue<Float_t>  (*myTreeReader, "xeelec"  );
	yeelec		= new TTreeReaderValue<Float_t>  (*myTreeReader, "yeelec"  );
	Q2eelec		= new TTreeReaderValue<Float_t>  (*myTreeReader, "Q2eelec" );
	nelec		= new TTreeReaderValue<Int_t>    (*myTreeReader, "nelec"   );
	Eelec		= new TTreeReaderArray<Float_t>  (*myTreeReader, "Eelec"   );
	thetelec	= new TTreeReaderArray<Float_t>  (*myTreeReader, "thetelec");
	phielec		= new TTreeReaderArray<Float_t>  (*myTreeReader, "phielec" );
	xelec		= new TTreeReaderArray<Float_t>  (*myTreeReader, "xelec"   );
	Q2elec		= new TTreeReaderArray<Float_t>  (*myTreeReader, "Q2elec"  );
	xsigma		= new TTreeReaderArray<Float_t>  (*myTreeReader, "xsigma"  );
	Q2sigma		= new TTreeReaderArray<Float_t>  (*myTreeReader, "Q2sigma" );
	sumc		= new TTreeReaderArray<Float_t>  (*myTreeReader, "sumc"    );
	sumetc		= new TTreeReaderValue<Float_t>  (*myTreeReader, "sumetc"  );
	yjbc		= new TTreeReaderValue<Float_t>  (*myTreeReader, "yjbc"    );
	Q2jbc		= new TTreeReaderValue<Float_t>  (*myTreeReader, "Q2jbc"   );
	sumct		= new TTreeReaderArray<Float_t>  (*myTreeReader, "sumct"   );
	sumetct		= new TTreeReaderValue<Float_t>  (*myTreeReader, "sumetct" );
	yjbct		= new TTreeReaderValue<Float_t>  (*myTreeReader, "yjbct"   );
	Q2jbct		= new TTreeReaderValue<Float_t>  (*myTreeReader, "Q2jbct"  );
	Ebeamel		= new TTreeReaderValue<Float_t>  (*myTreeReader, "Ebeamel" );
	Ebeampr		= new TTreeReaderValue<Float_t>  (*myTreeReader, "Ebeampr" );
	pvtx_d		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pvtx_d"  );
	cpvtx_d		= new TTreeReaderArray<Float_t>  (*myTreeReader, "cpvtx_d" );
	pvtx_t		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pvtx_t"  );
	cpvtx_t		= new TTreeReaderArray<Float_t>  (*myTreeReader, "cpvtx_t" );
	ntrkxy_t	= new TTreeReaderValue<Int_t>    (*myTreeReader, "ntrkxy_t");
	prbxy_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "prbxy_t" );
	ntrkz_t		= new TTreeReaderValue<Int_t>    (*myTreeReader, "ntrkz_t" );
	prbz_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "prbz_t"  );
	nds			= new TTreeReaderValue<Int_t>    (*myTreeReader, "nds"     );
	rankds		= new TTreeReaderValue<Int_t>    (*myTreeReader, "rankds"  );
	qds			= new TTreeReaderValue<Int_t>    (*myTreeReader, "qds"     );
	pds_d		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pds_d"   );
	ptds_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "ptds_d"  );
	etads_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "etads_d" );
	dm_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dm_d"    );
	ddm_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "ddm_d"   );
	pds_t		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pds_t"   );
	dm_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dm_t"    );
	ddm_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "ddm_t"   );
	ik			= new TTreeReaderValue<Int_t>    (*myTreeReader, "ik"      );
	ipi			= new TTreeReaderValue<Int_t>    (*myTreeReader, "ipi"     );
	ipis		= new TTreeReaderValue<Int_t>    (*myTreeReader, "ipis"    );
	pd0_d		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pd0_d"   );
	ptd0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "ptd0_d"  );
	etad0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "etad0_d" );
	md0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "md0_d"   );
	dmd0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dmd0_d"  );
	pd0_t		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pd0_t"   );
	md0_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "md0_t"   );
	dmd0_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dmd0_t"  );
	pk_r		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pk_r"    );
	ppi_r		= new TTreeReaderArray<Float_t>  (*myTreeReader, "ppi_r"   );
	pd0_r		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pd0_r"   );
	md0_r		= new TTreeReaderValue<Float_t>  (*myTreeReader, "md0_r"   );
	Vtxd0_r		= new TTreeReaderArray<Float_t>  (*myTreeReader, "Vtxd0_r" );
	cvtxd0_r	= new TTreeReaderArray<Float_t>  (*myTreeReader, "cvtxd0_r");
	dxy_r		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dxy_r"   );
	dz_r		= new TTreeReaderValue<Float_t>  (*myTreeReader, "dz_r"    );
	psi_r		= new TTreeReaderValue<Float_t>  (*myTreeReader, "psi_r"   );
	rd0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "rd0_d"   );
	drd0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "drd0_d"  );
	rpd0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "rpd0_d"  );
	drpd0_d		= new TTreeReaderValue<Float_t>  (*myTreeReader, "drpd0_d" );
	rd0_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "rd0_t"   );
	drd0_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "drd0_t"  );
	rpd0_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "rpd0_t"  );
	drpd0_t		= new TTreeReaderValue<Float_t>  (*myTreeReader, "drpd0_t" );
	rd0_dt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "rd0_dt"  );
	drd0_dt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "drd0_dt" );
	prbr_dt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "prbr_dt" );
	prbz_dt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "prbz_dt" );
	rd0_tt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "rd0_tt"  );
	drd0_tt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "drd0_tt" );
	prbr_tt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "prbr_tt" );
	prbz_tt		= new TTreeReaderValue<Float_t>  (*myTreeReader, "prbz_tt" );
	ijetd0		= new TTreeReaderValue<Int_t>    (*myTreeReader, "ijetd0"  );
	ptr3d0_j	= new TTreeReaderValue<Float_t>  (*myTreeReader, "ptr3d0_j");
	ptr2d0_j	= new TTreeReaderValue<Float_t>  (*myTreeReader, "ptr2d0_j");
	ptr3d0_3	= new TTreeReaderValue<Float_t>  (*myTreeReader, "ptr3d0_3");
	ptr2d0_3	= new TTreeReaderValue<Float_t>  (*myTreeReader, "ptr2d0_3");
	ptr2d0_2	= new TTreeReaderValue<Float_t>  (*myTreeReader, "ptr2d0_2");
	Mimpds_r	= new TTreeReaderValue<Float_t>  (*myTreeReader, "Mimpds_r");
	Mimpbk_r	= new TTreeReaderValue<Float_t>  (*myTreeReader, "Mimpbk_r");
	ntracks		= new TTreeReaderValue<Int_t>    (*myTreeReader, "ntracks" );
	pt			= new TTreeReaderArray<Float_t>  (*myTreeReader, "pt"      );
	kappa		= new TTreeReaderArray<Float_t>  (*myTreeReader, "kappa"   );
	phi			= new TTreeReaderArray<Float_t>  (*myTreeReader, "phi"     );
	theta		= new TTreeReaderArray<Float_t>  (*myTreeReader, "theta"   );
	dca			= new TTreeReaderArray<Float_t>  (*myTreeReader, "dca"     );
	z0			= new TTreeReaderArray<Float_t>  (*myTreeReader, "z0"      );
	covar		= new TTreeReaderArray<Float_t>  (*myTreeReader, "covar"   );
	nhitrp		= new TTreeReaderArray<Int_t>    (*myTreeReader, "nhitrp"  );
	prbrp		= new TTreeReaderArray<Float_t>  (*myTreeReader, "prbrp"   );
	nhitz		= new TTreeReaderArray<Int_t>    (*myTreeReader, "nhitz"   );
	prbz		= new TTreeReaderArray<Float_t>  (*myTreeReader, "prbz"    );
	rstart		= new TTreeReaderArray<Float_t>  (*myTreeReader, "rstart"  );
	rend		= new TTreeReaderArray<Float_t>  (*myTreeReader, "rend"    );
	lhk			= new TTreeReaderArray<Float_t>  (*myTreeReader, "lhk"     );
	lhpi		= new TTreeReaderArray<Float_t>  (*myTreeReader, "lhpi"    );
	nlhk		= new TTreeReaderArray<Float_t>  (*myTreeReader, "nlhk"    );
	nlhpi		= new TTreeReaderArray<Float_t>  (*myTreeReader, "nlhpi"   );
	dca_d		= new TTreeReaderArray<Float_t>  (*myTreeReader, "dca_d"   );
	ddca_d		= new TTreeReaderArray<Float_t>  (*myTreeReader, "ddca_d"  );
	dca_t		= new TTreeReaderArray<Float_t>  (*myTreeReader, "dca_t"   );
	ddca_t		= new TTreeReaderArray<Float_t>  (*myTreeReader, "ddca_t"  );
	muqual		= new TTreeReaderArray<Int_t>    (*myTreeReader, "muqual"  );
	imu			= new TTreeReaderValue<Int_t>    (*myTreeReader, "imu"     );
	imufe		= new TTreeReaderValue<Int_t>    (*myTreeReader, "imufe"   );
	njets		= new TTreeReaderValue<Int_t>    (*myTreeReader, "njets"   );
	E_j			= new TTreeReaderArray<Float_t>  (*myTreeReader, "E_j"     );
	pt_j		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pt_j"    );
	theta_j		= new TTreeReaderArray<Float_t>  (*myTreeReader, "theta_j" );
	eta_j		= new TTreeReaderArray<Float_t>  (*myTreeReader, "eta_j"   );
	phi_j		= new TTreeReaderArray<Float_t>  (*myTreeReader, "phi_j"   );
	m_j			= new TTreeReaderArray<Float_t>  (*myTreeReader, "m_j"     );
	thrust		= new TTreeReaderValue<Float_t>  (*myTreeReader, "thrust"  );
	pthrust		= new TTreeReaderArray<Float_t>  (*myTreeReader, "pthrust" );
	thrust2		= new TTreeReaderValue<Float_t>  (*myTreeReader, "thrust2" );
	pthrust2	= new TTreeReaderArray<Float_t>  (*myTreeReader, "pthrust2");
	spher		= new TTreeReaderValue<Float_t>  (*myTreeReader, "spher"   );
	aplan		= new TTreeReaderValue<Float_t>  (*myTreeReader, "aplan"   );
	plan		= new TTreeReaderValue<Float_t>  (*myTreeReader, "plan"    );
	nnout		= new TTreeReaderArray<Float_t>  (*myTreeReader, "nnout"   );
}

void h1analysisTreeReader::SlaveTerminate(){
	delete myTreeReader;

	delete  nrun;
	delete  nevent;
	delete  nentry;
	delete  trelem;
	delete  subtr;
	delete  rawtr;
	delete  L4subtr;
	delete  L5class;
	delete  E33;
	delete  de33;
	delete  x33;
	delete  dx33;
	delete  y33;
	delete  dy33;
	delete  E44;
	delete  de44;
	delete  x44;
	delete  dx44;
	delete  y44;
	delete  dy44;
	delete  Ept;
	delete  dept;
	delete  xpt;
	delete  dxpt;
	delete  ypt;
	delete  dypt;
	delete  pelec;
	delete  flagelec;
	delete  xeelec;
	delete  yeelec;
	delete  Q2eelec;
	delete  nelec;
	delete  Eelec;
	delete  thetelec;
	delete  phielec;
	delete  xelec;
	delete  Q2elec;
	delete  xsigma;
	delete  Q2sigma;
	delete  sumc;
	delete  sumetc;
	delete  yjbc;
	delete  Q2jbc;
	delete  sumct;
	delete  sumetct;
	delete  yjbct;
	delete  Q2jbct;
	delete  Ebeamel;
	delete  Ebeampr;
	delete  pvtx_d;
	delete  cpvtx_d;
	delete  pvtx_t;
	delete  cpvtx_t;
	delete  ntrkxy_t;
	delete  prbxy_t;
	delete  ntrkz_t;
	delete  prbz_t;
	delete  nds;
	delete  rankds;
	delete  qds;
	delete  pds_d;
	delete  ptds_d;
	delete  etads_d;
	delete  dm_d;
	delete  ddm_d;
	delete  pds_t;
	delete  dm_t;
	delete  ddm_t;
	delete  ik;
	delete  ipi;
	delete  ipis;
	delete  pd0_d;
	delete  ptd0_d;
	delete  etad0_d;
	delete  md0_d;
	delete  dmd0_d;
	delete  pd0_t;
	delete  md0_t;
	delete  dmd0_t;
	delete  pk_r;
	delete  ppi_r;
	delete  pd0_r;
	delete  md0_r;
	delete  Vtxd0_r;
	delete  cvtxd0_r;
	delete  dxy_r;
	delete  dz_r;
	delete  psi_r;
	delete  rd0_d;
	delete  drd0_d;
	delete  rpd0_d;
	delete  drpd0_d;
	delete  rd0_t;
	delete  drd0_t;
	delete  rpd0_t;
	delete  drpd0_t;
	delete  rd0_dt;
	delete  drd0_dt;
	delete  prbr_dt;
	delete  prbz_dt;
	delete  rd0_tt;
	delete  drd0_tt;
	delete  prbr_tt;
	delete  prbz_tt;
	delete  ijetd0;
	delete  ptr3d0_j;
	delete  ptr2d0_j;
	delete  ptr3d0_3;
	delete  ptr2d0_3;
	delete  ptr2d0_2;
	delete  Mimpds_r;
	delete  Mimpbk_r;
	delete  ntracks;
	delete  pt;
	delete  kappa;
	delete  phi;
	delete  theta;
	delete  dca;
	delete  z0;
	delete  covar;
	delete  nhitrp;
	delete  prbrp;
	delete  nhitz;
	delete  prbz;
	delete  rstart;
	delete  rend;
	delete  lhk;
	delete  lhpi;
	delete  nlhk;
	delete  nlhpi;
	delete  dca_d;
	delete  ddca_d;
	delete  dca_t;
	delete  ddca_t;
	delete  muqual;
	delete  imu;
	delete  imufe;
	delete  njets;
	delete  E_j;
	delete  pt_j;
	delete  theta_j;
	delete  eta_j;
	delete  phi_j;
	delete  m_j;
	delete  thrust;
	delete  pthrust;
	delete  thrust2;
	delete  pthrust2;
	delete  spher;
	delete  aplan;
	delete  plan;
	delete  nnout;
}
