test:

# CLEAN_TARGETS += *.log dummy* *pcm *o *rflx.* $(ALL_LIBRARIES)
# TEST_TARGETS += execLoadLibs
# 
# ifeq ($(strip $(ROOTTEST_HOME)),)
# 	export ROOTTEST_HOME:=$(shell expr $(CURDIR) : '\(.*/roottest/\)')
# endif
# 
# include $(ROOTTEST_HOME)/scripts/Rules.mk
# include $(ROOTTEST_HOME)/scripts/Reflex.mk
# 
# execLoadLibs.log: libOne_dictrflx.$(DllSuf) libTwo_dictrflx.$(DllSuf)
