// File Automatically generated by the ROOT Script Compiler

#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ class MyTop+;
#pragma link C++ class MyMulti+;
#pragma link C++ class MyInverseMulti+;
#pragma link C++ class A-;
#pragma link C++ class B;

#pragma link C++ function InheritMulti_driver;

#endif