name: 'cibuildwheel-impl'
description: 'Run cibuildwheel to produce a wheel depending on input tag'
inputs:
  build-tag:
    description: 'The tag for this build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build wheel
      uses: pypa/cibuildwheel@v3.0.1
      env:
        CIBW_BUILD: ${{ inputs.build-tag }}

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.build-tag }}
        path: wheelhouse/*
