name: 'cibuildwheel-impl'
description: 'Run cibuildwheel to produce a wheel depending on input tag'
inputs:
  build-tag:
    description: 'The tag for this build'
    required: true
  artifact-name:
    description: 'The name of the artifact to upload'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build wheel
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_BUILD: ${{ inputs.build-tag }}

    - name: Strip pre-built pcms
      shell: bash
      run: |
        python -m pip install --quiet wheel
        python .github/workflows/utilities/strip_wheel_pcms.py wheelhouse

    - name: Upload wheel
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: wheelhouse/*
