name: 'cibuildwheel-impl'
description: 'Run cibuildwheel to produce a wheel depending on input tag'
inputs:
  build-tag:
    description: 'The tag for this build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          binutils cmake dpkg-dev g++ gcc libssl-dev git libx11-dev \
          libxext-dev libxft-dev libxpm-dev python3 libtbb-dev libvdt-dev libgif-dev

    - name: Build wheel
      uses: pypa/cibuildwheel@v3.0.1
      env:
        PIP_NO_CACHE_DIR: "1"
        CIBW_BUILD: ${{ inputs.build-tag }}
        CIBW_TEST_REQUIRES: "-r test_tutorials/requirements.txt"
        CIBW_TEST_SOURCES: "test_tutorials"
        CIBW_TEST_COMMAND: "pytest -v"

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.build-tag }}
        path: wheelhouse/*
