name: 'cibuildwheel-impl'
description: 'Run cibuildwheel to produce a wheel depending on input tag'
inputs:
  build-tag:
    description: 'The tag for this build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt install -y binutils cmake dpkg-dev g++ gcc libssl-dev git libx11-dev \
        libxext-dev libxft-dev libxpm-dev libtbb-dev libvdt-dev libgif-dev libfftw3-dev

    - name: Build wheel
      uses: pypa/cibuildwheel@v3.0.1
      env:
        PIP_NO_CACHE_DIR: "1"
        CIBW_BUILD: ${{ inputs.build-tag }}

    - name: Test wheel
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r test_tutorials/requirements.txt
        python -m pip install wheelhouse/*.whl
        pytest -vv -rF test_tutorials/

    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.build-tag }}
        path: wheelhouse/*
