#!/bin/sh 
filelist=""
#echo `ls $1`
for file in `ls $1`
do
	#echo $file
        if [ -e SpecialDirs ] 
        then 
           if [ `grep $file SpecialDirs` ] 
           then 
               continue;
           fi
        fi
	if [ -d $file ] && [ -f $file/Makefile ]
	then
		
		filelist="$filelist$file "
	fi
done	
echo $filelist
