platform:
  - x64
  #- x86
configuration:
  #- Debug
  - Release

branches:
  only:
    - master

cache:
  - builddir
  - C:\projects\deps\ninja

clone_depth: 10

environment:
  VSTUDIO_VERS: Microsoft Visual Studio 14.0
  matrix:
    - CMAKE_GEN: Visual Studio 14 2015 Win64
    - CMAKE_GEN: Ninja

# matrix:
#  set this flag to immediately finish build once one of the jobs fails.
#  fast_finish: true 
#  allow_failures:
#  - platform: x86
#    configuration: Release
#  - platform: x64
#    configuration: Release

skip_tags: true
os:
  - Visual Studio 2015

build:
  parallel: true
  verbosity: detailed


install:
  - C:\"Program Files (x86)"\"%VSTUDIO_VERS%"\VC\vcvarsall.bat %platform%
  - set PATH=C:\projects\deps\ninja;C:\gnuwin32\bin;%PATH%
  - |-
    if exist "C:\projects\deps\ninja\" set GETNINJA=rem
    if not "%CMAKE_GEN%"=="Ninja" set GETNINJA=rem
    %GETNINJA% appveyor DownloadFile "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-win.zip" -FileName ninja.zip
    %GETNINJA% 7z x ninja.zip -oC:\projects\deps\ninja > nul
    %GETNINJA% ninja --version

build_script:
  - tools\packaging\cpt.py ^
        --current-dev=tar ^
        --with-cling-url=https://github.com/%APPVEYOR_REPO_NAME% ^
        --with-clang-url=http://root.cern.ch/git/clang.git ^
        --with-llvm-url=http://root.cern.ch/git/llvm.git ^
        --with-cmake-flags="-DLLVM_OPTIMIZED_TABLEGEN=ON -G\"%CMAKE_GEN%\"" ^
        --skip-cleanup

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- cmd: wmic os get osarchitecture
- cmd: echo platform is %platform%
- cmd: set

on_failure:
# Your RDP session is limited by overall build time (60 min).
# On every failing build, we have to wait for hours... Uncomment the next line if remote access to the machine is really needed (e.g. for debugging)
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
