.TH frm_admin 8 "8 March 2011"
.SH NAME
frm_admin - administer file residency parameters
.SH SYNOPSIS
.nf

\fBfrm_admin\fR [\fIoptions\fR] [\fIcommand\fR [\fIcmdopts\fR]]

.fi
.br
.ad l
.SH DESCRIPTION
The \fBfrm_admin\fR utility displays and alters data server space attributes
associated with file residency. These attributes are used by the
\fBfrm_purged\fR, \fBfrm_xfrd\fR, and \fBxrootd\fR daemons to manage
file residency.
Usage synopsis can be displayed by typing "\fBfrm_admin -h\fR".
Complete HTML documentation can be found at

.ce 
http://xrootd.org/doc/prod/frm_config.htm
.SH NOTES
Documentation for all components associated with \fBfrm_admin\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Configuration errors yield an error message and a non-zero exit status.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBfrm_admin\fR command is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
