.TH XrdCnsd 8 "8 March 2011"
.SH NAME
XrdCnsd - Cluster Name Space daemon
.SH SYNOPSIS
.nf

\fBXrdCnsd\fR [\fIoptions\fR]

.fi
.br
.ad l
.SH DESCRIPTION
The \fBXrdCnsd\fR daemon creates and maintains a file inventory for a data
server. This is known as a server-side inventory (\fBssi\fR) service.
The daemon can also be run as a one-time command to repair inventory problems.
Complete HTML documentation can be found at

.ce 
http://xrootd.org/doc/prod/cms_config.htm
.SH NOTES
The \fBcns_ssi\fR utility is used to display a server's inventory of files.
Documentation for all components associated with \fBXrdCnsd\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Configuration errors yield an error message and a non-zero exit status.
The daemon is normally started as piped command via an xrootd daemon
configuration directive.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBXrdCnsd\fR daemon is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
