.TH xrdpwdadmin 8 "8 March 2011"
.SH NAME
xrdpwdadmin - administer pwd security protocol passwords
.SH SYNOPSIS
.nf

\fBxrdpwdadmin\fR [\fB-m\fR \fImode\fR] \fIcommand\fR [\fIoptions\fR]

.fi
.br
.ad l
.SH DESCRIPTION
The \fBxrdpwdadmin\fR utility displays and maintains password and auto-login
files used by the password (\fBpwd\fR) security protocol.
Complete HTML documentation can be found at

.ce 
http://xrootd.org/doc/prod/sec_config.htm
.SH NOTES
Documentation for all components associated with \fBxrdpwdadmin\fR can be found at
http://xrootd.org/docs.html
.SH DIAGNOSTICS
Errors yield an error message and a non-zero exit status.
.SH LICENSE
License terms can be displayed by typing "\fBxrootd -H\fR".
.SH SUPPORT LEVEL
The \fBxrdpwdadmin\fR command is supported by the xrootd collaboration.
Contact information can be found at
.ce
http://xrootd.org/contact.html
