# --------------------------------------------------------------
# Makefile for examples module
# --------------------------------------------------------------

name = exampleN06
G4TARGET = $(name)
G4EXLIB = true
G4TMP = $(ROOTSYS)/montecarlo/g4root/test/exN06
G4BIN = $(ROOTSYS)/montecarlo/g4root/test/bin

.PHONY: all
all: lib bin

include $(G4INSTALL)/config/binmake.gmk
include ../flags.gmk
