#!/bin/sh

machine=`uname -m`   # 9000/7xx , 9000/8xx , 9000/3xx , 9000/4xx , Sun4c
LANG=C

case $machine in
9000/3*)
	makecint -dl hpib.sl -c hpib.c
	;;
*)
	echo 'HP-IB may not be supported on '$machine
	if test ! -r hpib.c
	then
		echo > hpib.sl
	fi
	;;
esac

