.\"
.\" $Id: g2root.1,v 1.1 2000/12/08 17:41:00 rdm Exp $
.\" 
.TH G2ROOT 1 "Version 3" "ROOT"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
g2root \- convert GEANT geomtry files to ROOT files
.SH SYNOPSIS
.B g2rootd 
.I [-f map_name] geant_name macro_name
.SH "DESCRIPTION"
You can convert a 
.B GEANT 
(see 
.I http://wwwinfo.cern.ch/asd/geant/index.html 
fore more on 
.BR GEANT )
geometry to 
.B ROOT 
geometry with the following steps
.TP 
1 
Run the interactive version of 
.B GEANT 
and produce a Zebra RZ file 
.IR detector.geom , 
by typing the command:
.sp 1 
.RS
Geant > rz/file 21 \fIdetector.geom\fR on
.RE
.sp 1
.TP
2 
Run the 
.B g2root 
program to convert the Zebra RZ file into a 
.B ROOT 
macro 
.I detector.C:
.sp 1 
.RS
g2root \fIdetector.geom\fR \fIdetector.C\fR
.RE
.sp 1
.TP 
3
Run the following 
.B ROOT 
session;
.sp 1 
.RS
.nf
root [1] .x detector.C
root [2] detector.Draw()
root [3] c1.x3d()   // (this invokes the 3-d Root viewver)
root [4] TFile f("detector.root","NEW") //open a new root file
root [5] detector.Write() //Write the geometry structure
root [6] f.Write() 
.fi
.RE
.sp 1
Note that the 
.I TNode 
structure currently in 
.B ROOT 
was not designed as a replacement for a true geometry package. The
idea was mainly to draw simple geometries in event display
programs. We are currently investigating several alternatives for a
true & efficient geometry package supporting;
.TP
- 
a disk data base with storage of multiple geometry versions
.TP 
- 
an interactive editor and viewer
.TP
- 
with 3-d views
.TP
- 
but also 2-d cut views
.TP 
- 
with interfaces to existing or future MC such as 
.B GEANT3 
or 
.B GEANT4
.PP
A second program called 
.B gh2root
(see 
.IR http://root.cern.ch/root/gh2root.html )
generates automatically C++ code corresponding to the 
.B GEANT3 Zebra 
structures 
.IR JSET , 
.IR JVERTX , 
.IR JKINE , 
.I JHITS  
and 
.I JDIGI.
.SH "SEE ALSO"
.RS
.IR root(1) ,
.IR h2root(1) , 
.RE
and
.RS 
.I The ROOT Users Guide
.RE
avaliable from the main 
.B ROOT
website:
.RS
.I http://root.cern.ch
.RE
.SH "ORIGINAL AUTHORS"
The ROOT team (see web page above):
.RS
\fBRene Brun\fR and \fBFons Rademakers\fR 
.RE
.SH "COPYRIGHT"
ROOT Software Terms and Conditions
.PP
The authors hereby grant permission to use, copy, and distribute this
software and its documentation for any purpose, provided that existing
copyright notices are retained in all copies and that this notice is
included verbatim in any distributions. Additionally, the authors grant
permission to modify this software and its documentation for any purpose,
provided that such modifications are not distributed without the explicit
consent of the authors and that existing copyright notices are retained in
all copies. Users of the software are asked to feed back problems, benefits,
and/or suggestions about the software to the ROOT Development Team
(rootdev@root.cern.ch). Support for this software - fixing of bugs,
incorporation of new features - is done on a best effort basis. All bug
fixes and enhancements will be made available under the same terms and
conditions as the original software,
.PP
IN NO EVENT SHALL THE AUTHORS OR DISTRIBUTORS BE LIABLE TO ANY PARTY FOR
DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
OF THE USE OF THIS SOFTWARE, ITS DOCUMENTATION, OR ANY DERIVATIVES THEREOF,
EVEN IF THE AUTHORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.PP
THE AUTHORS AND DISTRIBUTORS SPECIFICALLY DISCLAIM ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. THIS SOFTWARE IS
PROVIDED ON AN "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO
OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR
MODIFICATIONS.
.SH AUTHOR 
This manual page was written by Christian Holm Christensen
<cholm@nbi.dk>, for the Debian GNU/Linux system (but may be used by
others). 
.\"
.\" $Log: g2root.1,v $
.\" Revision 1.1  2000/12/08 17:41:00  rdm
.\" man pages of all ROOT executables provided by Christian Holm.
.\"
.\" 
