.\" 
.\" $Id: hadd.1,v 1.1 2002/07/31 20:44:26 rdm Exp $
.\" 
.TH HADD 1 "Version 3" "ROOT"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
hadd \- Merge ROOT histogram files into one file
.SH SYNOPSIS
.B hadd 
.I "outputfile inputfiles ..."
.SH "DESCRIPTION"
This program will add histograms from a list of 
.B ROOT 
files and write them to a target 
.B ROOT 
file. The target file is newly created and must not be identical to
one of the source files. 
.SH "SEE ALSO"
.SB
\fIroot\fR(1)
.PP
.\" .SE
For extensive documentation on the \fBROOT\fR system, see
.UR http://root.cern.ch
\fIhttp://root.cern.ch\fR
.UE
.PP
A \fBUsers Guide\fR is avaliable from
.UR http://root.cern.ch/root/UsersGuide.html
here.
.UE
.PP 
The classes of ROOT are all documented by the automatic documentation
system, and is available 
.UR http://root.cern.ch/root/html/ClassIndex.html
online.
.UE
.SH "ORIGINAL AUTHORS"
 Sven A. Schmidt 
.UR sven.schmidt@cern.ch
\fIsven.schmidt@cern.ch\fR, Dirk Geppert, and Rene Brun 
.UR Rene.Brun@cern.ch
\fIRene.Brun@cern.ch\fR
.SH "COPYRIGHT"
This library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of the
License, or (at your option) any later version.
.P
This library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
.P
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.SH AUTHOR 
This manual page was written by Christian Holm Christensen
<cholm@nbi.dk>, for the Debian GNU/Linux system (but may be used by
others). 
.\" 
.\" $Log: hadd.1,v $
.\" Revision 1.1  2002/07/31 20:44:26  rdm
.\" new Debian and RedHat package scripts. By Christian Holm.
.\"
.\" Revision 1.1  2001/08/15 13:30:48  rdm
.\" move man files to new subdir man1. This makes it possible to add
.\" $ROOTSYS/man to MANPATH and have "man root" work.
.\"
.\" Revision 1.2  2001/04/23 09:10:12  rdm
.\" updates by Christian Holm for making debian and RedHat packages.
.\"
.\" Revision 1.1  2000/12/08 17:41:01  rdm
.\" man pages of all ROOT executables provided by Christian Holm.
.\"
.\" 
