.\" 
.\" $Id:$
.\"
.TH PQ2-CACHE 1 "Version 5" "ROOT" 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
pq2-cache \- display or clear the local cache content of a remote dataset meta-repository based on ROOT files
.SH SYNOPSIS
.B pq2-cache
[action] [options] [datasets]
.SH "DESCRIPTION"
This manual page documents briefly the
.BR pq2-cache
program.
.PP
.B pq2-cache
is a script invoking the
.B pq2
ROOT application to display or clear the local cache content of a remote dataset meta-repository based on ROOT files;
the repository can be accessed via a remote file server daemon.
.PP
More details about the underlying 'pq2' application can be found in the man page \fIpq2\fR(1).
.SH ACTIONS
.TP
\fIshow\fR
Display cache content (default)
.TP
\fIclear\fR
Clear cache content
.SH ARGUMENTS
.TP
\fIdatasets\fR
Datasets to processed; wildcards are supported.
.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
Display help information.
.TP 
\fB-k\fR, \fB--keep\fR
Keep the temporary files created during the analysis under $TMPDIR
.TP 
\fB-v\fR
Verbose mode
.TP
\fB--dataset\fR=<\fIdataset\fR>
Alternative way to define the datasets to be removed.
.TP
\fB-u\fR <\fIserverurl\fR>, \fB--url\fR=<\fIserverurl\fR>
URL of the data server providing the information; it must include the directory.
Can also be specified via the environment variables PQ2DSSRVURL (see ENVIRONMENT VARIABLES)."
.TP
\fB-t\fR <\fIdir\fR>, \fB--tmpdir\fR=<\fIdir\fR>
Directory for temporary files; defualt is /tmp/<username>.
.SH "ENVIRONMENT VARIABLES"
See \fIsetup-pq2\fR(1).
.SH "SEE ALSO"
\fIpq2\fR(1), \fIsetup-pq2\fR(1), \fIpq2-ls\fR(1), \fIpq2-ls-files\fR(1),
\fIpq2-ls-files-server\fR(1), \fIpq2-info-server\fR(1),
\fIpq2-ana-dist\fR(1), \fIpq2-put\fR(1), \fIpq2-verify\fR(1), \fIpq2-rm\fR(1)
.PP
For more information on the \fBROOT\fR system, please refer to 
.UR http://root.cern.ch/
.I http://root.cern.ch
.UE
.SH "ORIGINAL AUTHORS"
Gerardo Ganis for the ROOT team.
.SH "COPYRIGHT"
This library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of the
License, or (at your option) any later version.
.P
This library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
.P
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.SH AUTHOR 
This manual page was originally written by Gerardo Ganis <gerardo.ganis@cern.ch>, for ROOT version 5.
