.\"
.\" $Id: rlibmap.1,v 1.1 2005/03/21 21:42:21 rdm Exp $
.\"
.TH RLIBMAP 1 "Version 3" "ROOT"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
rlibmap \- ROOT utility to create class to library maps
.SH SYNOPSIS
.B rlibmap
[-f] [[-r|-o] \fImapfile\fR] -l \fIlibrary\fR -d \fIdependecy\fR -c \fILinkdef\fR
.SH "DESCRIPTION"
Creates a map from classes to shared libraries that contain these
classes. 
.SH OPTIONS 
.TP 
.B --help
Gives a short list of options avaliable, and exit
.TP
.BI -f 
What!?
.TP
.BI -r mapfile
Read map file \fImapfile\fR
.TP
.BI -o mapfile
Output on \fImapfile\fR
.TP
.BI -l sofile
Library to inspect
.TP
.BI -d depsofile
Dependency library.
.TP
.BI -c linkdef
Specify \fBCINT\fR linkdef to use
.SH "SEE ALSO"
\fIroot\fR(1), \fIrootcint\fR(1)
.PP
See also the \fBROOT\fR webpages:
.UR http://root.cern.ch
\fIhttp://root.cern.ch\fR
.UE
.SH "ORIGINAL AUTHORS"
The ROOT team (see web page above):
.RS
\fBRene Brun\fR and \fBFons Rademakers\fR
.RE
.SH "COPYRIGHT"
This library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of the
License, or (at your option) any later version.
.P
This library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
.P
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.SH AUTHOR 
This manual page was written by Christian Holm Christensen
<cholm@nbi.dk>, for the Debian GNU/Linux system (but may be used by
others). 
.\"
.\" EOF
.\"
