.TH ROOTN.EXE 1 "Version 3" "ROOT"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
rootn.exe \- ROOT interpreter memory managed backend
.SH DESCRIPTION
This executable is linked with \fBlibNew\fR, unlike \fIroot.exe\fR,
which makes it appropriate for if one wants to use memory mapped file,
\fBTMapFile\fR, and so on. In all other aspects, it's the same as
the \fIroot\fR(1) executable.
.SH "SEE ALSO"
.SB
\fIroot\fR(1), \fIroot.exe\fR(1), and \fIcint\fR(1)
.\" .SE
.SH "ORIGINAL AUTHORS"
The ROOT team:
.RS
.B Rene Brun
and
.B Fons Rademakers
.RE
.SH "COPYRIGHT"
This library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of the
License, or (at your option) any later version.
.P
This library is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
.P
You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.SH AUTHOR
This manual page was written by Christian Holm Christensen
<cholm@nbi.dk>, for the Debian GNU/Linux system (but may be used by
others).

