.TH xprep 1 "2009 Jan 28" xrootd "xrootd prepare CLI"
.SH NAME
xprep \- xroot protocol prepare command line tool
.SH SYNOPSIS
.br
.B xprep
[-d n] [-f fn] [-p prty] [-s] [-S] [-w]
.I host
[:port][,...] [path [...]]

.SH DESCRIPTION
Used to issue staging or perpare requests towards an xroot/scalla stage pool.
.SH OPTIONS
Consult the source code or the author for further details.
.SH AUTHOR
\fBCERN IT-DM\fP based on 'xprep -h' <fabrizio.furano@cern.ch>

