.TH xrd 1 "2009 Jan 28" xrootd "xrootd admin CLI"
.SH NAME
xrd \- xroot protocol admin command line tool
.SH SYNOPSIS
.br
.B xrd
[host] [-DSparmname stringvalue] ... [-DIparmname intvalue]  [-O<opaque info>] [-h]

.SH DESCRIPTION
For further details execute
.B xrd
and type 'help'.
.SH OPTIONS
.BI -DS parmname \0 stringvalue
set the internal parm
.I parmname
with the string value
.I stringvalue.
See XrdClientConst.hh for a list of parameters.
.TP
.BI -DI parmname \0 intvalue
set the internal parm
.I parmname
with the integer value
.I
intvalue. See XrdClientConst.hh for a list of parameters.
.br
.BI -O opaque
add opaque information
.I opaque.
.BI -h
Display help on usage.
.br
 where:
.I parmname
is the name of an internal parameter
.I stringvalue
is a string to be assigned to an internal parameter
.I intvalue
is an int to be assigned to an internal parameter
.SH AUTHOR
\fBCERN IT-DM\fP based on 'xrd -h' <fabrizio.furano@cern.ch>

