.TH xrdcp 1 "2009 Jan 28" xrootd "remote file copy"
.SH NAME
xrdcp \- root protocol remote file copy
.SH SYNOPSIS
.br
.B xrdcp
.IR source
.IR dst
[-d lvl] [-DSparmname stringvalue] ... [-DIparmname intvalue] [-s] [-ns] [-v] [-OS<opaque info>] [-OD<opaque info>] [-force] [-md5] [-np] [-f] [-R] [-S] [-h]

.SH DESCRIPTION
.IR source
 can be:
   a local file
   a local directory name suffixed by /
   an xrootd URL in the form root://user@host/<absolute Logical File Name in xrootd domain>
      (can be a directory. In this case the -R option can be fully honored only on a standalone server)
.br
.IR dest
 can be:
   a local file
   a local directory name suffixed by /
   an xrootd URL in the form root://user@host/<absolute Logical File Name in xrootd domain>
      (can be a directory LFN)
.SH OPTIONS
.TP
.BI -d lvl
debug level: 1 (low), 2 (medium), 3 (high)
.TP
.BI -D proxyaddr:proxyport
use
.I proxyaddr:proxyport
as a SOCKS4 proxy. Only numerical addresses are supported.
.TP
.BI -DS parmname \0 stringvalue
set the internal parm
.I parmname
with the string value
.I stringvalue.
See XrdClientConst.hh for a list of parameters.
.TP
.BI -DI parmname \0 intvalue
set the internal parm
.I parmname
with the integer value
.I
intvalue. See XrdClientConst.hh for a list of parameters.
.br
.B Example:
 -DIReadCacheSize 3000000 -DIReadAheadSize 1000000
.TP
.BI -s
silent mode, no summary output, no progress bar
.TP
.BI -np
no progress bar
.TP
.BI -v
display summary output
.TP
.BI -OS
adds some opaque information to any SOURCE xrootd url
.TP
.BI -OD
adds some opaque information to any DEST xrootd url
.TP
.BI -f
re-create a file if already present
.TP
.BI -F
set the 'force' flag for xrootd dest file opens (ignore if file is already opened)
.TP
.BI -force
set 1-min (re)connect attempts to retry for up to 1 week, to block until xrdcp is executed
.TP
.BI -md5
calculate the md5 sum during transfers
.TP
.BI -R
recurse subdirectories
.TP
.BI -S num
use
.I num
additional parallel streams to do the xfer.
The max value is 15. The default is 0 (i.e. use only the main stream)
.TP
.BI -ML libname
use
.I libname
 as external monitoring reporting library.The default name if XrdCpMonitorClient.so . Make sure it is reachable.
.TP
.BI -h
Display help on usage.
.br
 where:
.I parmname
is the name of an internal parameter
.I stringvalue
is a string to be assigned to an internal parameter
.I intvalue
is an int to be assigned to an internal parameter
.SH EXAMPLES
.TP
local file upload:
.br
.B $ xrdcp /tmp/myfile root://foo.bar.com//data/myfile
.br
.TP
remote file download:
.br
.B $ xrdcp root://foo.bar.com//data/myfile /tmp/myfile
.br
.TP
remote-remote copy:
.br
.B $ xrdcp root://foo.bar.com//data/myfile1 root://foo.bar.com//data/myfile2
.br
.TP
local file upload to a Castor instance using a specific service class and stager:
.b
.B $ xrdcp /tmp/myfile root://<stagerhost>.cern.ch//castor/cern.ch/data/myfile -ODstagerHost=$STAGE_HOST&svcClass=$STAGE_SVCCLASS
.br
[ you need to escape the '&' in the shell ]
.TP
remote file download from a Castor instance using a specific stager:
.br
.B $ xrdcp /tmp/myfile root://<stagerhost>.cern.ch//castor/cern.ch/data/myfile -OSstagerHost=$STAGE_HOST
.TP
client-proxy copy to-/from- a Castor instance:
.br
.B $ xrdcp
.br
.B root://<stagerA>.cern.ch//castor/cern.ch/data/stagerA/myfile -OSstagerHost=<stagerA>
.br
.B root://<stagerB>.cern.ch//castor/cern.ch/data/stagerB/myfile -ODstagerHost=<stagerA>
.br
.br
[ you cannot copy between stagers using the same logical filename in the castor namespace! ]
.SH AUTHOR
\fBCERN IT-DM\fP based on 'xrdcp -h' <fabrizio.furano@cern.ch>

