.TH xrdstagetool 1 "2009 Jan 28" xrootd "xrootd prepare CLI"
.SH NAME
xrdstagetool \- xroot protocol third party staging command line client
.SH SYNOPSIS
.br
.B xrdstagetool [-h] ...

.SH DESCRIPTION
Used to issue staging requests towards an xroot/scalla stage pool from remote pools or backend MSS. Use the '-h' option for exact syntax.
.SH OPTIONS
Consult the source code or the author for further details.
.SH AUTHOR
\fBCERN IT-DM\fP based on 'xrdstagetool -h' <fabrizio.furano@cern.ch>

