#!/bin/sh

# HistFactory workplace setup script

if [ -z $ROOTSYS ]
then
  echo "Please set up ROOT before running this script."
  exit
fi

if [ $# -eq 1 ]
then
  DIR=$1
  echo "HistFactory workplace will be created in: " $DIR
else
  DIR=.
  echo "HistFactory workplace will be created in the current directory"
fi

echo "Creating directory structure..."
mkdir -p $DIR/config
mkdir -p $DIR/data
mkdir -p $DIR/results

echo "Copying skeleton configuration files..."
cp $ROOTSYS/etc/HistFactorySchema.dtd $DIR/config/
cp $ROOTSYS/etc/example.xml $DIR/config/
cp $ROOTSYS/etc/example_channel.xml $DIR/config/

#echo "Making skeleton data files..."
#cp $ROOTSYS/etc/makeExample.C $DIR/data/
#root -b makeExample.C

echo "Done!"
#echo "You can run the example with: hist2workspace $DIR/config/example.xml"

exit
