/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef ROOEXTENDEDBINDING
#define ROOEXTENDEDBINDING

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsPdf.h"
#include "RooAbsCategory.h"

class RooExtendedBinding : public RooAbsReal {
public:
  RooExtendedBinding() {} ;
  RooExtendedBinding(const char *name, const char *title, RooAbsPdf& _pdf);
  RooExtendedBinding(const RooExtendedBinding& other, const char* name=nullptr) ;
  TObject* clone(const char* newname) const override { return new RooExtendedBinding(*this,newname); }
  inline ~RooExtendedBinding() override { }

protected:

  RooRealProxy pdf ;

  double evaluate() const override ;

private:

  ClassDefOverride(RooExtendedBinding,1) // Your description goes here...
};

#endif
