#!/bin/sh
#############################################################################
# The WildCard interpreter
#############################################################################
# Shell script , setup
#############################################################################
# Description:
#  WildCard installation script
#############################################################################
#
# Copyright(c) 1996~1996  Hetlett-Packard Japan, All rights reserved
# Author                  Masaharu Goto (gotom@jpn.hp.com)
# Copyright(c) 1996~2001  Masaharu Goto (MXJ02154@niftyserve.or.jp)
#
#############################################################################

#############################################################################
# Set platform dependent parameters
#############################################################################

########################################
# For Linux1.2.13
########################################
#INCLD='-I/usr/X11/include -I/usr/local/include -I/usr/local/X11/include'
#LIB='-L/usr/X11/lib -L/usr/local/lib -lX11 -ltk -ltcl'
#MACRO='-DG__LINUX120'

########################################
# For Linux2.0.27
########################################
INCLD='-I/usr/X11/include -I/usr/local/include -I/usr/local/X11/include'
LIB='-L/usr/X11/lib -L/usr/local/lib -lX11 -ltk -ltcl'
MACRO=''

########################################
# For Linux2.2.14
########################################
INCLD='-I/usr/X11R6/include -I/usr/local/include -I/usr/local/X11R6/include'
LIB='-L/usr/X11R6/lib -L/usr/local/lib -lX11 -ltk -ltcl'
MACRO=''

########################################
# For HP-UX 9.05 
########################################
#INCLD='-I/usr/local/X11R6/include -I/usr/local/include'
#LIB='-L/usr/local/X11R6/lib -lX11 -L/usr/local/lib -ltk -ltcl'
#MACRO=''

#############################################################################
# Set other parameters
#############################################################################
# Order of HDR setting is important. TOP.h must be the first
HDR='TOP.h TCLTK.h TKMACRO.h TCLMACRO.h'
OBJ=wildc
MKFILE=Makefile
#MACRO='-DSIMPLE'
INIT='-B G__cinttk_init'

# Check if C++ compiler exists
ISCPP=`grep CPPPREP $CINTSYSDIR/MAKEINFO|awk '/^/{print $3;}'`
if test -n "$ISCPP"
then
  APPINIT='-m -C AppInit.c TkInit.c WildCard.c -C++ Main.cxx'
else
  APPINIT='-m -C AppInit.c TkInit.c WildCard.c Main.c'
fi

#############################################################################
# Run makecint 
#############################################################################
makecint $INIT -mk $MKFILE -o $OBJ $MACRO -I$CINTSYSDIR $INCLD $APPINIT -h $HDR -l $TCLTKLIB $LIB

#############################################################################
# Run make
#
# Don't mind about Warning message that TCLTK.h TKMACRO.h ... already loaded.
#############################################################################
make clean
make 
