name: Diff CppInterOp against upstream
on:
  pull_request:
    paths:
      - 'interpreter/CppInterOp/**'

jobs:
  cppinterop-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ROOT
        uses: actions/checkout@v4
        with:
          path: root
      - name: Check out CppInterOp
        uses: actions/checkout@v4
        with:
          repository: compiler-research/CppInterOp
          ref: 302fc67ae185db42d584557f9a08e12c409d8cb1
          path: CppInterOp
      - name: Drop directories that are not added to ROOT
        working-directory: CppInterOp
        run: |
          rm -rf .git .github
      - name: Compare
        run: diff -ur CppInterOp/ root/interpreter/CppInterOp/
