name: Diff LLVM and Clang against fork of monorepo
on:
  pull_request:
    paths:
      - 'interpreter/llvm-project/**'

jobs:
  llvm-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ROOT
        uses: actions/checkout@v3
        with:
          path: root
      - name: Determine tag in fork of monorepo
        id: determine-tag
        run: echo "tag=$(cat root/interpreter/llvm-project/llvm-project.tag)" >> $GITHUB_OUTPUT
      - name: Check out llvm-project
        uses: actions/checkout@v3
        with:
          repository: root-project/llvm-project
          ref: ${{ steps.determine-tag.outputs.tag }}
          path: llvm-project
      - name: Delete directories and files in llvm-project
        working-directory: llvm-project
        run: |
          for d in bindings benchmark benchmarks gn test tests unittest unittests; do
            find . -name $d -prune -exec rm -r "{}" \;
          done
          rm -r llvm/utils/vscode
      - name: Compare
        run: |
          for d in clang llvm; do
            diff -ur llvm-project/$d root/interpreter/llvm-project/$d
          done
