name: 'GetFixedIssues'

on:
  workflow_dispatch:
    inputs:
      major:
        type: choice
        description: Major
        options: 
        - 6
        - 7
        - 8
        required: true
        default: 6
      minor:
        type: choice
        description: Minor
        options: 
        - 26
        - 28
        - 30
        - 32
        - 36
        - 38
        - 40
        - 42
        - 44
        - 46
        - 48
        required: true
        default: 40
      patch:
        type: choice
        description: Patch
        options: 
        - "00"
        - "02"
        - "04"
        - "06"
        - "08"
        - "10"
        - "12"
        - "14"
        - "16"
        - "18"
        - "20"
        - "22"
        - "24"
        - "26"
        - "28"
        - "30"
        required: true
        default: "00"

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Generate list of closed issues for release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh project item-list `gh project list --owner root-project |grep ${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}|awk '{print $1}` --owner root-project -L 8192|grep "Issue"|sort -t$'\t' -k3 -n -r| awk -v FS='\t' -v OFS='\t'  '{print "  * [[#"$3"](https://github.com/root-project/root/issues/"$3")] - "$2}'
