name: 'ROOT Python wheels'
on:
  workflow_dispatch:
    inputs:
      major:
        type: choice
        description: Major
        options: 
        - 6
        - 7
        - 8
        required: true
        default: 6
      minor:
        type: choice
        description: Minor
        options: 
        - 26
        - 28
        - 30
        - 32
        - 36
        - 38
        - 40
        - 42
        - 44
        - 46
        - 48
        required: true
        default: 40
      patch:
        type: choice
        description: Patch
        options: 
        - "00"
        - "02"
        - "04"
        - "06"
        - "08"
        - "10"
        - "12"
        - "14"
        - "16"
        - "18"
        - "20"
        - "22"
        - "24"
        - "26"
        - "28"
        - "30"
        required: true
        default: "00"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build_Wheel:
    runs-on: macos-26 
    strategy:
      fail-fast: false
      matrix:
        target: [cp310-macosx_arm64, cp311-macosx_arm64, cp312-macosx_arm64, cp313-macosx_arm64, cp314-macosx_arm64]
    name: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/cibuildwheel-impl
        env:
            MACOSX_DEPLOYMENT_TARGET: 26.5
        with:
          build-tag: ${{ matrix.target }}
