name: 'ROOT Docs Nightlies'

on:
  schedule:
    - cron: '20 1 * * *'
    - cron: '20 12 * * 1-5'

jobs:
  Docs_6-32:
    if: ${{ github.event.schedule == '20 1 * * *' }}
    uses: root-project/root/.github/workflows/root-docs-ci.yml@v6-32-00-patches
    secrets: inherit

  Docs_6-36:
    if: ${{ github.event.schedule == '20 1 * * *' }}
    uses: root-project/root/.github/workflows/root-docs-ci.yml@v6-36-00-patches
    secrets: inherit

  Docs_6-40:
    if: ${{ github.event.schedule == '20 1 * * *' }}
    uses: root-project/root/.github/workflows/root-docs-ci.yml@v6-40-00-patches
    secrets: inherit
