name: 'ROOT Docs CI'

on:
  pull_request:
    paths:
      - '.github/workflows/root-docs-ci.yml'
      - 'documentation/doxygen/**'
    branches:
      - 'master'

  workflow_call:

  workflow_dispatch:
    inputs:
      eos_upload_directory:
        description: 'Make documentation available at <root-website>/doc/<directory>. Leave empty for skipping the upload to eos.'
        type: string
        required: false
        default: 'master'

env:
  PLATFORM: alma10
  DOC_DIR: ${{ case(github.base_ref == null, github.ref_name, 'PullRequest') }}
  DOC_LOCATION: /github/home
  EOS_DIR_NAME: |-
    ${{ case(
      inputs.eos_upload_directory != null, inputs.eos_upload_directory,
      github.base_ref != null, 'PR',
      github.ref_name
      )
    }}
  TAR_FILE: html${{ case(github.base_ref == null, github.ref_name, '_PullRequest') }}.tar.gz

jobs:
  build-docs:
    if: github.repository_owner == 'root-project'

    runs-on:
      - self-hosted
      - linux
      - x64

    permissions:
      contents: read

    container:
      image: registry.cern.ch/root-ci/alma10:buildready
      options: '--security-opt label=disable --rm'
      volumes:
        - alma10_ccache_volume:/github/home/.cache/ccache
      env:
        OS_APPLICATION_CREDENTIAL_ID: '7f5b64a265244623a3a933308569bdba'
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: 'v3applicationcredential'
        OS_AUTH_URL: 'https://keystone.cern.ch/v3'
        OS_IDENTITY_API_VERSION: 3
        OS_INTERFACE: 'public'
        OS_REGION_NAME: 'cern'
        PYTHONUNBUFFERED: true

    steps:
    - name: Prepare qhelpgenerator
      # Qt6's libexec executables are not in the PATH by default
      run: |
        QHELPGENERATOR=$(which qhelpgenerator) && echo "QHELPGENERATOR=${QHELPGENERATOR}" >> "${GITHUB_ENV}"
        PATH=/usr/lib64/qt6/libexec/:${PATH} QHELPGENERATOR=$(which qhelpgenerator) && echo "QHELPGENERATOR=${QHELPGENERATOR}" >> "${GITHUB_ENV}"

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Set up Python Virtual Env
      # if the `if` expr is false, `if` still has exit code 0.
      # if the `if` block is entered, the block's exit code becomes the exit
      # code of the `if`.
      run: 'if [ -d /py-venv/ROOT-CI/bin/ ]; then . /py-venv/ROOT-CI/bin/activate && echo ${PATH%:*} >> "${GITHUB_PATH}"; fi'

    - name: Build ROOT
      run: ".github/workflows/root-ci-config/build_root.py
                  --buildtype      Release
                  --platform       ${{ env.PLATFORM }}
                  --incremental    false
                  --source_dir     ${GITHUB_WORKSPACE}
                  --repository     ${{ github.server_url }}/${{ github.repository }}
                  --overrides      testing=Off roottest=Off
                  --upload_artifacts false
                  --binaries         false"

    - name: Run Doxygen
      shell: bash
      run: |
        source ${HOME}/ROOT-CI/build/bin/thisroot.sh
        export DOXYGEN_OUTPUT_DIRECTORY="/github/home/${DOC_DIR}"
        cd documentation/doxygen
        make -j "$(nproc --all)"

    - name: Clean temporary files
      # These files are used when doxygen runs incrementally
      shell: bash
      run: |
        cd "/github/home/${DOC_DIR}"
        rm html/*.md5
        rm html/*.map

    - name: Create documentation archives
      working-directory: ${{ env.DOC_LOCATION }}
      shell: bash
      run: |
        pwd
        ls -l
        ls -l ${DOC_DIR}
        tar -caf ${TAR_FILE} ${DOC_DIR}
        ls -l

    - name: Upload tar file to github
      if:   ${{ !cancelled() }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.TAR_FILE}}
        path: ${{env.DOC_LOCATION}}/${{env.TAR_FILE}}
        if-no-files-found: error
        archive: false
        retention-days: 8

    - name: Sync documentation to EOS
      env:
        RWEBEOS_KT: ${{ secrets.RWEBEOS_KT }}
        KRB5USER: ${{ secrets.KRB5USER }}
        KRB5REALM: ${{ secrets.KRB5REALM }}
        KT_FILE_NAME: /tmp/decoded.keytab
        EOS_BASE_PATH: /eos/project/r/root-eos/website/
        EOS_ENDPOINT: root://eosproject-r.cern.ch
        KRB5CCNAME: /tmp/krb5cc
      if: ${{ env.KRB5REALM != '' && env.EOS_DIR_NAME != null && env.EOS_DIR_NAME != '' }}
      working-directory: ${{ env.DOC_LOCATION }}
      # Because of https://github.com/xrootd/xrootd/issues/2235 , the xrd client can copy
      # only at most 65536 in one go. For this reason, we copy files in batches, dividing
      # them by extension. Once that is fixed in XRootD, a single command can be used
      # instead.
      run: |
        echo "Input eos directory: ${EOS_DIR_NAME}"
        EOS_DIR_NAME="${EOS_DIR_NAME%-00-patches}"
        EOS_DIR_NAME="${EOS_DIR_NAME/-/}"
        echo "Uploading to the directory: ${EOS_DIR_NAME}"
        failure=0
        echo "${RWEBEOS_KT}" | base64 -d > "${KT_FILE_NAME}"
        kinit -p ${{ secrets.KRB5USER }}@${{ secrets.KRB5REALM }} -kt "${KT_FILE_NAME}"
        cd "${DOC_DIR}/html/"
        xrdcp --parallel 64 -rf ./*.html "${EOS_ENDPOINT}/${EOS_BASE_PATH}/doc/${EOS_DIR_NAME}" || failure=1
        rm -rf ./*.html
        xrdcp --parallel 64 -rf ./*.svg "${EOS_ENDPOINT}/${EOS_BASE_PATH}/doc/${EOS_DIR_NAME}" || failure=1
        rm -rf ./*.svg
        xrdcp --parallel 64 -rf ./ "${EOS_ENDPOINT}/${EOS_BASE_PATH}/doc/${EOS_DIR_NAME}" || failure=1
        cd ..
        rm -r html
        xrdcp --parallel 64 -rf ./ "${EOS_ENDPOINT}/${EOS_BASE_PATH}/doc/${EOS_DIR_NAME}" || failure=1
        cd ..
        xrdcp -rf "${TAR_FILE}" "${EOS_ENDPOINT}/${EOS_BASE_PATH}/download" || failure=1
        exit "$failure"
